// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AugmentedReality;

public class ARGeoAnchor : Palforge.Sdk.Script.AugmentedReality.ARTrackedGeometry
{
    internal ARGeoAnchor(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ARGeoAnchor");
    }

    public static new ARGeoAnchor? New(UObject? outer = null)
    {
        return SdkEnv.New("ARGeoAnchor", outer) as ARGeoAnchor;
    }

    public static new ARGeoAnchor? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ARGeoAnchor;
    }

    public float GetLongitude()
    {
        return As<float>(Call("GetLongitude"));
    }

    public float GetLatitude()
    {
        return As<float>(Call("GetLatitude"));
    }

    public Palforge.Sdk.Script.AugmentedReality.EARAltitudeSource GetAltitudeSource()
    {
        return (Palforge.Sdk.Script.AugmentedReality.EARAltitudeSource)As<byte>(Call("GetAltitudeSource"));
    }

    public float GetAltitudeMeters()
    {
        return As<float>(Call("GetAltitudeMeters"));
    }
}
