// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AugmentedReality;

public class ARLightEstimate : UObject
{
    internal ARLightEstimate(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ARLightEstimate");
    }

    public static ARLightEstimate? New(UObject? outer = null)
    {
        return SdkEnv.New("ARLightEstimate", outer) as ARLightEstimate;
    }

    public static ARLightEstimate? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ARLightEstimate;
    }
}
