// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AugmentedReality;

public class ARTraceResult : UStructValue
{
    public float DistanceFromCamera
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public Palforge.Sdk.Script.AugmentedReality.EARLineTraceChannels TraceChannel
    {
        get => (Palforge.Sdk.Script.AugmentedReality.EARLineTraceChannels)ReadAt<byte>(0x4);
        set => WriteAt(0x4, (byte)value);
    }

    public Palforge.Sdk.Script.CoreUObject.Transform LocalTransform =>
        new Palforge.Sdk.Script.CoreUObject.Transform(Address + 0x10, Context);

    public Palforge.Sdk.Script.AugmentedReality.ARTrackedGeometry? TrackedGeometry
    {
        get => WrapAt(0x70) as Palforge.Sdk.Script.AugmentedReality.ARTrackedGeometry;
        set => WriteObjectAt(0x70, value);
    }

    internal ARTraceResult(nint address, UnrealContext context) : base(address, context, "ARTraceResult")
    {
    }

    private protected ARTraceResult(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ARTraceResult? Allocate()
    {
        return SdkEnv.AllocateStruct<ARTraceResult>("ARTraceResult");
    }
}
