// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.AugmentedReality;

public enum EARSessionType
{
    None = 0,
    Orientation = 1,
    World = 2,
    Face = 3,
    Image = 4,
    ObjectScanning = 5,
    PoseTracking = 6,
    GeoTracking = 7,
    EARSessionTypeMax = 8
}
