// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.AugmentedReality;

public enum EARServicePermissionRequestResult
{
    Granted = 0,
    Denied = 1,
    EARServicePermissionRequestResultMax = 2
}
