// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ClothingSystemRuntimeCommon;

public class ClothingAssetCommon : Palforge.Sdk.Script.ClothingSystemRuntimeInterface.ClothingAssetBase
{
    public Palforge.Sdk.Script.Engine.PhysicsAsset? PhysicsAsset
    {
        get => WrapAt(0x48) as Palforge.Sdk.Script.Engine.PhysicsAsset;
        set => WriteObjectAt(0x48, value);
    }

    public UnrealMap<string, Palforge.Sdk.Script.ClothingSystemRuntimeInterface.ClothConfigBase?> ClothConfigs =>
        new UnrealMap<string, Palforge.Sdk.Script.ClothingSystemRuntimeInterface.ClothConfigBase?>(this, 0x50, 0x18, 0x8, "ClothConfigs", static (context, element) => context.NameAt(element), static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.ClothingSystemRuntimeInterface.ClothConfigBase, static (context, value) => context.NameBytes(value), static (context, value) => Bytes<nint>(value?.Address ?? 0), null, null);

    public UnrealArray<Palforge.Sdk.Script.ClothingSystemRuntimeCommon.ClothLODDataCommon> LODData =>
        new UnrealArray<Palforge.Sdk.Script.ClothingSystemRuntimeCommon.ClothLODDataCommon>(this, 0xA0, 0x148, "LODData", static (context, element) => new Palforge.Sdk.Script.ClothingSystemRuntimeCommon.ClothLODDataCommon(element, context), static (context, value) => context.BytesAt(value.Address, 0x148), null);

    public UnrealArray<int> LodMap =>
        new UnrealArray<int>(this, 0xB0, 0x4, "LodMap", static (context, element) => context.ValueAt<int>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<string> UsedBoneNames =>
        new UnrealArray<string>(this, 0xC0, 0x8, "UsedBoneNames", static (context, element) => context.NameAt(element), static (context, value) => context.NameBytes(value), null);

    public UnrealArray<int> UsedBoneIndices =>
        new UnrealArray<int>(this, 0xD0, 0x4, "UsedBoneIndices", static (context, element) => context.ValueAt<int>(element), static (context, value) => Bytes(value), null);

    public int ReferenceBoneIndex
    {
        get => ReadAt<int>(0xE0);
        set => WriteAt(0xE0, value);
    }

    public Palforge.Sdk.Script.ClothingSystemRuntimeCommon.ClothingAssetCustomData? CustomData
    {
        get => WrapAt(0xE8) as Palforge.Sdk.Script.ClothingSystemRuntimeCommon.ClothingAssetCustomData;
        set => WriteObjectAt(0xE8, value);
    }

    internal ClothingAssetCommon(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ClothingAssetCommon");
    }

    public static new ClothingAssetCommon? New(UObject? outer = null)
    {
        return SdkEnv.New("ClothingAssetCommon", outer) as ClothingAssetCommon;
    }

    public static new ClothingAssetCommon? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ClothingAssetCommon;
    }
}
