// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.DiscordPartnerSDK;

public class DiscordUserMessageSummary : UObject
{
    internal DiscordUserMessageSummary(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("DiscordUserMessageSummary");
    }

    public static DiscordUserMessageSummary? New(UObject? outer = null)
    {
        return SdkEnv.New("DiscordUserMessageSummary", outer) as DiscordUserMessageSummary;
    }

    public static DiscordUserMessageSummary? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as DiscordUserMessageSummary;
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? UserId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "UserId", "DiscordUniqueID");
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? LastMessageId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "LastMessageId", "DiscordUniqueID");
    }

    public void Drop()
    {
        Call("Drop");
    }
}
