// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.DiscordPartnerSDK;

public class DiscordActivityInvite : UObject
{
    internal DiscordActivityInvite(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("DiscordActivityInvite");
    }

    public static DiscordActivityInvite? New(UObject? outer = null)
    {
        return SdkEnv.New("DiscordActivityInvite", outer) as DiscordActivityInvite;
    }

    public static DiscordActivityInvite? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as DiscordActivityInvite;
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.EDiscordActivityActionTypes Type()
    {
        return (Palforge.Sdk.Script.DiscordPartnerSDK.EDiscordActivityActionTypes)As<byte>(Call("Type"));
    }

    public void SetType(Palforge.Sdk.Script.DiscordPartnerSDK.EDiscordActivityActionTypes type)
    {
        Call("SetType", Bytes((byte)type));
    }

    public void SetSessionId(string sessionId)
    {
        Call("SetSessionId", StringArgument(sessionId));
    }

    public void SetSenderId(Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID senderId)
    {
        Call("SetSenderId", SdkEnv.StructBytes(senderId, 8));
    }

    public void SetPartyId(string partyId)
    {
        Call("SetPartyId", StringArgument(partyId));
    }

    public void SetParentApplicationId(Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID parentApplicationId)
    {
        Call("SetParentApplicationId", SdkEnv.StructBytes(parentApplicationId, 8));
    }

    public void SetMessageId(Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID messageId)
    {
        Call("SetMessageId", SdkEnv.StructBytes(messageId, 8));
    }

    public void SetIsValid(bool isValid)
    {
        Call("SetIsValid", Bytes<byte>(isValid ? (byte)1 : (byte)0));
    }

    public void SetChannelId(Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID channelId)
    {
        Call("SetChannelId", SdkEnv.StructBytes(channelId, 8));
    }

    public void SetApplicationId(Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID applicationId)
    {
        Call("SetApplicationId", SdkEnv.StructBytes(applicationId, 8));
    }

    public string SessionId()
    {
        return SdkEnv.Text(Call("SessionId"));
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? SenderId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "SenderId", "DiscordUniqueID");
    }

    public string PartyId()
    {
        return SdkEnv.Text(Call("PartyId"));
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? ParentApplicationId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "ParentApplicationId", "DiscordUniqueID");
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? MessageId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "MessageId", "DiscordUniqueID");
    }

    public bool IsValid()
    {
        return As<byte>(Call("IsValid")) is not 0;
    }

    public void Init()
    {
        Call("Init");
    }

    public void Drop()
    {
        Call("Drop");
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? ChannelId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "ChannelId", "DiscordUniqueID");
    }

    public Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID? ApplicationId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.DiscordPartnerSDK.DiscordUniqueID>(this, "ApplicationId", "DiscordUniqueID");
    }
}
