// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.DiscordPartnerSDK;

public enum EDiscordActivityTypes
{
    Playing = 0,
    Streaming = 1,
    Listening = 2,
    Watching = 3,
    CustomStatus = 4,
    Competing = 5,
    HangStatus = 6,
    EDiscordActivityTypesMax = 7
}
