// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.DiscordPartnerSDK;

public enum EDiscordCallStatus
{
    Disconnected = 0,
    Joining = 1,
    Connecting = 2,
    SignalingConnected = 3,
    Connected = 4,
    Reconnecting = 5,
    Disconnecting = 6,
    EDiscordCallStatusMax = 7
}
