// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AudioAnalyzer;

public class AudioAnalyzerAssetBase : UObject
{
    internal AudioAnalyzerAssetBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AudioAnalyzerAssetBase");
    }

    public static AudioAnalyzerAssetBase? New(UObject? outer = null)
    {
        return SdkEnv.New("AudioAnalyzerAssetBase", outer) as AudioAnalyzerAssetBase;
    }

    public static AudioAnalyzerAssetBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AudioAnalyzerAssetBase;
    }
}
