// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Water;

public class WaterZone : Palforge.Sdk.Script.Engine.Actor
{
    public Palforge.Sdk.Script.Engine.TextureRenderTarget2D? WaterInfoTexture
    {
        get => WrapAt(0x290) as Palforge.Sdk.Script.Engine.TextureRenderTarget2D;
        set => WriteObjectAt(0x290, value);
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint RenderTargetResolution =>
        new Palforge.Sdk.Script.CoreUObject.IntPoint(Address + 0x2A8, Context);

    public Palforge.Sdk.Script.Water.WaterMeshComponent? WaterMesh
    {
        get => WrapAt(0x2B0) as Palforge.Sdk.Script.Water.WaterMeshComponent;
        set => WriteObjectAt(0x2B0, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector2D ZoneExtent =>
        new Palforge.Sdk.Script.CoreUObject.Vector2D(Address + 0x2B8, Context);

    public float CaptureZOffset
    {
        get => ReadAt<float>(0x2C8);
        set => WriteAt(0x2C8, value);
    }

    public bool BHalfPrecisionTexture
    {
        get => ReadBoolAt(0x2CC, 0xFF);
        set => WriteBoolAt(0x2CC, 0xFF, value);
    }

    public int VelocityBlurRadius
    {
        get => ReadAt<int>(0x2D0);
        set => WriteAt(0x2D0, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector TessellatedWaterMeshExtent =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x2D8, Context);

    public uint NonTessellatedLODSectionScale
    {
        get => ReadAt<uint>(0x2F0);
        set => WriteAt(0x2F0, value);
    }

    public int OverlapPriority
    {
        get => ReadAt<int>(0x2F4);
        set => WriteAt(0x2F4, value);
    }

    public bool BEnableNonTessellatedLODMesh
    {
        get => ReadBoolAt(0x2F8, 0xFF);
        set => WriteBoolAt(0x2F8, 0xFF, value);
    }

    internal WaterZone(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("WaterZone");
    }

    public static new WaterZone? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("WaterZone", owner, at) as WaterZone;
    }

    public static new WaterZone? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as WaterZone;
    }
}
