// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Water;

public class WaterBodyExclusionVolume : Palforge.Sdk.Script.Engine.PhysicsVolume
{
    public bool BExcludeAllOverlappingWaterBodies
    {
        get => ReadBoolAt(0x2D8, 0xFF);
        set => WriteBoolAt(0x2D8, 0xFF, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Water.WaterBody?> WaterBodiesToExclude =>
        new UnrealArray<Palforge.Sdk.Script.Water.WaterBody?>(this, 0x2E0, 0x8, "WaterBodiesToExclude", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Water.WaterBody, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal WaterBodyExclusionVolume(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("WaterBodyExclusionVolume");
    }

    public static new WaterBodyExclusionVolume? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("WaterBodyExclusionVolume", owner, at) as WaterBodyExclusionVolume;
    }

    public static new WaterBodyExclusionVolume? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as WaterBodyExclusionVolume;
    }
}
