// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GameplayTags;

public class GameplayTagContainerNetSerializerSerializationHelper : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.GameplayTags.GameplayTag> GameplayTags =>
        new UnrealArray<Palforge.Sdk.Script.GameplayTags.GameplayTag>(this, 0x0, 0x8, "GameplayTags", static (context, element) => new Palforge.Sdk.Script.GameplayTags.GameplayTag(element, context), static (context, value) => context.BytesAt(value.Address, 0x8), null);

    internal GameplayTagContainerNetSerializerSerializationHelper(nint address, UnrealContext context) : base(address, context, "GameplayTagContainerNetSerializerSerializationHelper")
    {
    }

    private protected GameplayTagContainerNetSerializerSerializationHelper(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static GameplayTagContainerNetSerializerSerializationHelper? Allocate()
    {
        return SdkEnv.AllocateStruct<GameplayTagContainerNetSerializerSerializationHelper>("GameplayTagContainerNetSerializerSerializationHelper");
    }
}
