// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public class BakeMultiMeshInputToolProperties : Palforge.Sdk.Script.InteractiveToolsFramework.InteractiveToolPropertySet
{
    public Palforge.Sdk.Script.Engine.StaticMesh? TargetStaticMesh
    {
        get => WrapAt(0xA8) as Palforge.Sdk.Script.Engine.StaticMesh;
        set => WriteObjectAt(0xA8, value);
    }

    public Palforge.Sdk.Script.Engine.SkeletalMesh? TargetSkeletalMesh
    {
        get => WrapAt(0xB0) as Palforge.Sdk.Script.Engine.SkeletalMesh;
        set => WriteObjectAt(0xB0, value);
    }

    public Palforge.Sdk.Script.Engine.Actor? TargetDynamicMesh
    {
        get => WrapAt(0xB8) as Palforge.Sdk.Script.Engine.Actor;
        set => WriteObjectAt(0xB8, value);
    }

    public string TargetUVLayer
    {
        get => ReadStringAt(0xC0);
        set => WriteStringAt(0xC0, value);
    }

    public UnrealArray<Palforge.Sdk.Script.MeshModelingToolsExp.BakeMultiMeshDetailProperties> SourceMeshes =>
        new UnrealArray<Palforge.Sdk.Script.MeshModelingToolsExp.BakeMultiMeshDetailProperties>(this, 0xD0, 0x18, "SourceMeshes", static (context, element) => new Palforge.Sdk.Script.MeshModelingToolsExp.BakeMultiMeshDetailProperties(element, context), static (context, value) => context.BytesAt(value.Address, 0x18), null);

    public float ProjectionDistance
    {
        get => ReadAt<float>(0xE0);
        set => WriteAt(0xE0, value);
    }

    public UnrealArray<string> TargetUVLayerNamesList =>
        new UnrealArray<string>(this, 0xE8, 0x10, "TargetUVLayerNamesList", static (context, element) => context.StringAt(element), static (context, value) => context.StringValueBytes(value), static (context, bytes) => context.ReleaseStringValue(bytes));

    internal BakeMultiMeshInputToolProperties(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("BakeMultiMeshInputToolProperties");
    }

    public static new BakeMultiMeshInputToolProperties? New(UObject? outer = null)
    {
        return SdkEnv.New("BakeMultiMeshInputToolProperties", outer) as BakeMultiMeshInputToolProperties;
    }

    public static new BakeMultiMeshInputToolProperties? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as BakeMultiMeshInputToolProperties;
    }
}
