// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public enum EConvertToPolygonsMode
{
    FaceNormalDeviation = 0,
    FindPolygons = 1,
    FromUVIslands = 2,
    FromNormalSeams = 3,
    FromConnectedTris = 4,
    FromFurthestPointSampling = 5,
    CopyFromLayer = 6,
    EConvertToPolygonsModeMax = 7
}
