// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public enum EMeshGroupPaintBrushType
{
    Paint = 0,
    Erase = 1,
    LastValue = 2,
    EMeshGroupPaintBrushTypeMax = 3
}
