// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public enum ETransformMeshesSnapDragSource
{
    ClickPoint = 0,
    Pivot = 1,
    LastValue = 2,
    ETransformMeshesSnapDragSourceMax = 3
}
