// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public class PerlinLayerProperties : UStructValue
{
    public float Frequency
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public float Intensity
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    internal PerlinLayerProperties(nint address, UnrealContext context) : base(address, context, "PerlinLayerProperties")
    {
    }

    private protected PerlinLayerProperties(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PerlinLayerProperties? Allocate()
    {
        return SdkEnv.AllocateStruct<PerlinLayerProperties>("PerlinLayerProperties");
    }
}
