// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshModelingToolsExp;

public class RemoveOccludedTrianglesTool : Palforge.Sdk.Script.ModelingComponents.MultiSelectionMeshEditingTool
{
    public Palforge.Sdk.Script.MeshModelingToolsExp.RemoveOccludedTrianglesToolProperties? BasicProperties
    {
        get => WrapAt(0xB8) as Palforge.Sdk.Script.MeshModelingToolsExp.RemoveOccludedTrianglesToolProperties;
        set => WriteObjectAt(0xB8, value);
    }

    public Palforge.Sdk.Script.ModelingComponents.PolygroupLayersProperties? PolygroupLayersProperties
    {
        get => WrapAt(0xC0) as Palforge.Sdk.Script.ModelingComponents.PolygroupLayersProperties;
        set => WriteObjectAt(0xC0, value);
    }

    public Palforge.Sdk.Script.MeshModelingToolsExp.RemoveOccludedTrianglesAdvancedProperties? AdvancedProperties
    {
        get => WrapAt(0xC8) as Palforge.Sdk.Script.MeshModelingToolsExp.RemoveOccludedTrianglesAdvancedProperties;
        set => WriteObjectAt(0xC8, value);
    }

    public UnrealArray<Palforge.Sdk.Script.ModelingComponents.MeshOpPreviewWithBackgroundCompute?> Previews =>
        new UnrealArray<Palforge.Sdk.Script.ModelingComponents.MeshOpPreviewWithBackgroundCompute?>(this, 0xD0, 0x8, "Previews", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.ModelingComponents.MeshOpPreviewWithBackgroundCompute, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UnrealArray<Palforge.Sdk.Script.ModelingComponents.PreviewMesh?> PreviewCopies =>
        new UnrealArray<Palforge.Sdk.Script.ModelingComponents.PreviewMesh?>(this, 0xE0, 0x8, "PreviewCopies", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.ModelingComponents.PreviewMesh, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal RemoveOccludedTrianglesTool(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("RemoveOccludedTrianglesTool");
    }

    public static new RemoveOccludedTrianglesTool? New(UObject? outer = null)
    {
        return SdkEnv.New("RemoveOccludedTrianglesTool", outer) as RemoveOccludedTrianglesTool;
    }

    public static new RemoveOccludedTrianglesTool? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as RemoveOccludedTrianglesTool;
    }
}
