// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InputCore;

public class Key : UStructValue
{
    public string KeyName
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    internal Key(nint address, UnrealContext context) : base(address, context, "Key")
    {
    }

    private protected Key(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static Key? Allocate()
    {
        return SdkEnv.AllocateStruct<Key>("Key");
    }
}
