// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.PalModLoader;

public enum EPalModInstallType
{
    Paks = 0,
    Lua = 1,
    LogicMods = 2,
    Ue4ss = 3,
    PalSchema = 4,
    EPalModInstallTypeMax = 5
}
