// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.HeadMountedDisplay;

public class HeadMountedDisplayFunctionLibrary : Palforge.Sdk.Script.Engine.BlueprintFunctionLibrary
{
    internal HeadMountedDisplayFunctionLibrary(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("HeadMountedDisplayFunctionLibrary");
    }

    public static new HeadMountedDisplayFunctionLibrary? New(UObject? outer = null)
    {
        return SdkEnv.New("HeadMountedDisplayFunctionLibrary", outer) as HeadMountedDisplayFunctionLibrary;
    }

    public static new HeadMountedDisplayFunctionLibrary? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as HeadMountedDisplayFunctionLibrary;
    }

    public static void UpdateExternalTrackingHMDPosition(Palforge.Sdk.Script.CoreUObject.Transform externalTrackingTransform)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "UpdateExternalTrackingHMDPosition", SdkEnv.StructBytes(externalTrackingTransform, 96));
    }

    public static void SetWorldToMetersScale(UObject? worldContext, float newScale)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetWorldToMetersScale", Bytes<nint>(worldContext?.Address ?? 0), Bytes(newScale));
    }

    public static void SetTrackingOrigin(byte origin)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetTrackingOrigin", Bytes(origin));
    }

    public static void SetSpectatorScreenTexture(Palforge.Sdk.Script.Engine.Texture? inTexture)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetSpectatorScreenTexture", Bytes<nint>(inTexture?.Address ?? 0));
    }

    public static void SetSpectatorScreenModeTexturePlusEyeLayout(Palforge.Sdk.Script.CoreUObject.Vector2D eyeRectMin, Palforge.Sdk.Script.CoreUObject.Vector2D eyeRectMax, Palforge.Sdk.Script.CoreUObject.Vector2D textureRectMin, Palforge.Sdk.Script.CoreUObject.Vector2D textureRectMax, bool bDrawEyeFirst, bool bClearBlack, bool bUseAlpha)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetSpectatorScreenModeTexturePlusEyeLayout", SdkEnv.StructBytes(eyeRectMin, 16), SdkEnv.StructBytes(eyeRectMax, 16), SdkEnv.StructBytes(textureRectMin, 16), SdkEnv.StructBytes(textureRectMax, 16), Bytes<byte>(bDrawEyeFirst ? (byte)1 : (byte)0), Bytes<byte>(bClearBlack ? (byte)1 : (byte)0), Bytes<byte>(bUseAlpha ? (byte)1 : (byte)0));
    }

    public static void SetSpectatorScreenMode(Palforge.Sdk.Script.HeadMountedDisplay.ESpectatorScreenMode mode)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetSpectatorScreenMode", Bytes((byte)mode));
    }

    public static void SetClippingPlanes(float near, float far)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "SetClippingPlanes", Bytes(near), Bytes(far));
    }

    public static void ResetOrientationAndPosition(float yaw, byte options)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "ResetOrientationAndPosition", Bytes(yaw), Bytes(options));
    }

    public static bool IsSpectatorScreenModeControllable()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "IsSpectatorScreenModeControllable")) is not 0;
    }

    public static bool IsInLowPersistenceMode()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "IsInLowPersistenceMode")) is not 0;
    }

    public static bool IsHeadMountedDisplayEnabled()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "IsHeadMountedDisplayEnabled")) is not 0;
    }

    public static bool IsHeadMountedDisplayConnected()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "IsHeadMountedDisplayConnected")) is not 0;
    }

    public static bool IsDeviceTracking(Palforge.Sdk.Script.HeadMountedDisplay.XRDeviceId xRDeviceId)
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "IsDeviceTracking", SdkEnv.StructBytes(xRDeviceId, 12))) is not 0;
    }

    public static bool HasValidTrackingPosition()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "HasValidTrackingPosition")) is not 0;
    }

    public static int GetXRSystemFlags()
    {
        return As<int>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetXRSystemFlags"));
    }

    public static float GetWorldToMetersScale(UObject? worldContext)
    {
        return As<float>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetWorldToMetersScale", Bytes<nint>(worldContext?.Address ?? 0)));
    }

    public static void GetVRFocusState(out bool bUseFocus, out bool bHasFocus)
    {
        var arguments = new byte[][] { Bytes<byte>(0), Bytes<byte>(0) };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetVRFocusState", arguments, out var outputs);
        bUseFocus = As<byte>(outputs[0]) is not 0;
        bHasFocus = As<byte>(outputs[1]) is not 0;
    }

    public static string GetVersionString()
    {
        return SdkEnv.Text(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetVersionString"));
    }

    public static Palforge.Sdk.Script.CoreUObject.Transform? GetTrackingToWorldTransform(UObject? worldContext)
    {
        return SdkEnv.CallStaticForStruct<Palforge.Sdk.Script.CoreUObject.Transform>("HeadMountedDisplayFunctionLibrary", "GetTrackingToWorldTransform", "Transform", Bytes<nint>(worldContext?.Address ?? 0));
    }

    public static void GetTrackingSensorParameters(Palforge.Sdk.Script.CoreUObject.Vector origin, Palforge.Sdk.Script.CoreUObject.Rotator rotation, out float leftFOV, out float rightFOV, out float topFOV, out float bottomFOV, out float distance, out float nearPlane, out float farPlane, out bool isActive, int index)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(origin, 24), SdkEnv.StructBytes(rotation, 24), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<byte>(0), Bytes(index) };
        var destinations = new nint[] { origin.Address, rotation.Address, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetTrackingSensorParameters", arguments, destinations, out var outputs);
        leftFOV = As<float>(outputs[2]);
        rightFOV = As<float>(outputs[3]);
        topFOV = As<float>(outputs[4]);
        bottomFOV = As<float>(outputs[5]);
        distance = As<float>(outputs[6]);
        nearPlane = As<float>(outputs[7]);
        farPlane = As<float>(outputs[8]);
        isActive = As<byte>(outputs[9]) is not 0;
    }

    public static bool GetTrackingOriginTransform(byte origin, Palforge.Sdk.Script.CoreUObject.Transform outTransform)
    {
        var arguments = new byte[][] { Bytes(origin), SdkEnv.StructBytes(outTransform, 96) };
        var destinations = new nint[] { 0, outTransform.Address };
        var result = SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetTrackingOriginTransform", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public static byte GetTrackingOrigin()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetTrackingOrigin"));
    }

    public static void GetPositionalTrackingCameraParameters(Palforge.Sdk.Script.CoreUObject.Vector cameraOrigin, Palforge.Sdk.Script.CoreUObject.Rotator cameraRotation, out float hfov, out float vfov, out float cameraDistance, out float nearPlane, out float farPlane)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(cameraOrigin, 24), SdkEnv.StructBytes(cameraRotation, 24), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default) };
        var destinations = new nint[] { cameraOrigin.Address, cameraRotation.Address, 0, 0, 0, 0, 0 };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetPositionalTrackingCameraParameters", arguments, destinations, out var outputs);
        hfov = As<float>(outputs[2]);
        vfov = As<float>(outputs[3]);
        cameraDistance = As<float>(outputs[4]);
        nearPlane = As<float>(outputs[5]);
        farPlane = As<float>(outputs[6]);
    }

    public static bool GetPlayAreaRect(Palforge.Sdk.Script.CoreUObject.Transform outTransform, Palforge.Sdk.Script.CoreUObject.Vector2D outRect)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(outTransform, 96), SdkEnv.StructBytes(outRect, 16) };
        var destinations = new nint[] { outTransform.Address, outRect.Address };
        var result = SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetPlayAreaRect", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public static Palforge.Sdk.Script.CoreUObject.Vector2D? GetPlayAreaBounds(byte origin)
    {
        return SdkEnv.CallStaticForStruct<Palforge.Sdk.Script.CoreUObject.Vector2D>("HeadMountedDisplayFunctionLibrary", "GetPlayAreaBounds", "Vector2D", Bytes(origin));
    }

    public static float GetPixelDensity()
    {
        return As<float>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetPixelDensity"));
    }

    public static void GetOrientationAndPosition(Palforge.Sdk.Script.CoreUObject.Rotator deviceRotation, Palforge.Sdk.Script.CoreUObject.Vector devicePosition)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(deviceRotation, 24), SdkEnv.StructBytes(devicePosition, 24) };
        var destinations = new nint[] { deviceRotation.Address, devicePosition.Address };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetOrientationAndPosition", arguments, destinations, out var outputs);
    }

    public static int GetNumOfTrackingSensors()
    {
        return As<int>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetNumOfTrackingSensors"));
    }

    public static void GetMotionControllerData(UObject? worldContext, Palforge.Sdk.Script.InputCore.EControllerHand hand, Palforge.Sdk.Script.HeadMountedDisplay.XRMotionControllerData motionControllerData)
    {
        var arguments = new byte[][] { Bytes<nint>(worldContext?.Address ?? 0), Bytes((byte)hand), SdkEnv.StructBytes(motionControllerData, 224) };
        var destinations = new nint[] { 0, 0, motionControllerData.Address };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetMotionControllerData", arguments, destinations, out var outputs);
    }

    public static byte GetHMDWornState()
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetHMDWornState"));
    }

    public static string GetHMDDeviceName()
    {
        return SdkEnv.Text(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetHMDDeviceName"));
    }

    public static void GetHMDData(UObject? worldContext, Palforge.Sdk.Script.HeadMountedDisplay.XRHMDData hMDData)
    {
        var arguments = new byte[][] { Bytes<nint>(worldContext?.Address ?? 0), SdkEnv.StructBytes(hMDData, 96) };
        var destinations = new nint[] { 0, hMDData.Address };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetHMDData", arguments, destinations, out var outputs);
    }

    public static void GetDeviceWorldPose(UObject? worldContext, Palforge.Sdk.Script.HeadMountedDisplay.XRDeviceId xRDeviceId, out bool bIsTracked, Palforge.Sdk.Script.CoreUObject.Rotator orientation, out bool bHasPositionalTracking, Palforge.Sdk.Script.CoreUObject.Vector position)
    {
        var arguments = new byte[][] { Bytes<nint>(worldContext?.Address ?? 0), SdkEnv.StructBytes(xRDeviceId, 12), Bytes<byte>(0), SdkEnv.StructBytes(orientation, 24), Bytes<byte>(0), SdkEnv.StructBytes(position, 24) };
        var destinations = new nint[] { 0, 0, 0, orientation.Address, 0, position.Address };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetDeviceWorldPose", arguments, destinations, out var outputs);
        bIsTracked = As<byte>(outputs[2]) is not 0;
        bHasPositionalTracking = As<byte>(outputs[4]) is not 0;
    }

    public static void GetDevicePose(Palforge.Sdk.Script.HeadMountedDisplay.XRDeviceId xRDeviceId, out bool bIsTracked, Palforge.Sdk.Script.CoreUObject.Rotator orientation, out bool bHasPositionalTracking, Palforge.Sdk.Script.CoreUObject.Vector position)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(xRDeviceId, 12), Bytes<byte>(0), SdkEnv.StructBytes(orientation, 24), Bytes<byte>(0), SdkEnv.StructBytes(position, 24) };
        var destinations = new nint[] { 0, 0, orientation.Address, 0, position.Address };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetDevicePose", arguments, destinations, out var outputs);
        bIsTracked = As<byte>(outputs[1]) is not 0;
        bHasPositionalTracking = As<byte>(outputs[3]) is not 0;
    }

    public static bool GetCurrentInteractionProfile(Palforge.Sdk.Script.InputCore.EControllerHand hand, out string interactionProfile)
    {
        var arguments = new byte[][] { Bytes((byte)hand), StringArgument("") };
        var result = SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetCurrentInteractionProfile", arguments, out var outputs);
        interactionProfile = SdkEnv.Text(outputs[1]);
        return As<byte>(result) is not 0;
    }

    public static bool GetControllerTransformForTime(UObject? worldContext, int controllerIndex, string motionSource, Palforge.Sdk.Script.CoreUObject.Timespan time, out bool bTimeWasUsed, Palforge.Sdk.Script.CoreUObject.Rotator orientation, Palforge.Sdk.Script.CoreUObject.Vector position, out bool bProvidedLinearVelocity, Palforge.Sdk.Script.CoreUObject.Vector linearVelocity, out bool bProvidedAngularVelocity, Palforge.Sdk.Script.CoreUObject.Vector angularVelocityRadPerSec, out bool bProvidedLinearAcceleration, Palforge.Sdk.Script.CoreUObject.Vector linearAcceleration)
    {
        var arguments = new byte[][] { Bytes<nint>(worldContext?.Address ?? 0), Bytes(controllerIndex), SdkEnv.NameBytes(motionSource), SdkEnv.StructBytes(time, 8), Bytes<byte>(0), SdkEnv.StructBytes(orientation, 24), SdkEnv.StructBytes(position, 24), Bytes<byte>(0), SdkEnv.StructBytes(linearVelocity, 24), Bytes<byte>(0), SdkEnv.StructBytes(angularVelocityRadPerSec, 24), Bytes<byte>(0), SdkEnv.StructBytes(linearAcceleration, 24) };
        var destinations = new nint[] { 0, 0, 0, 0, 0, orientation.Address, position.Address, 0, linearVelocity.Address, 0, angularVelocityRadPerSec.Address, 0, linearAcceleration.Address };
        var result = SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "GetControllerTransformForTime", arguments, destinations, out var outputs);
        bTimeWasUsed = As<byte>(outputs[4]) is not 0;
        bProvidedLinearVelocity = As<byte>(outputs[7]) is not 0;
        bProvidedAngularVelocity = As<byte>(outputs[9]) is not 0;
        bProvidedLinearAcceleration = As<byte>(outputs[11]) is not 0;
        return As<byte>(result) is not 0;
    }

    public static void EnableLowPersistenceMode(bool bEnable)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "EnableLowPersistenceMode", Bytes<byte>(bEnable ? (byte)1 : (byte)0));
    }

    public static bool EnableHMD(bool bEnable)
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "EnableHMD", Bytes<byte>(bEnable ? (byte)1 : (byte)0))) is not 0;
    }

    public static void DisconnectRemoteXRDevice()
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "DisconnectRemoteXRDevice");
    }

    public static byte ConnectRemoteXRDevice(string ipAddress, int bitRate)
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "ConnectRemoteXRDevice", StringArgument(ipAddress), Bytes(bitRate)));
    }

    public static bool ConfigureGestures(Palforge.Sdk.Script.HeadMountedDisplay.XRGestureConfig gestureConfig)
    {
        return As<byte>(SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "ConfigureGestures", SdkEnv.StructBytes(gestureConfig, 6))) is not 0;
    }

    public static void ClearXRTimedInputActionDelegate(string actionPath)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "ClearXRTimedInputActionDelegate", SdkEnv.NameBytes(actionPath));
    }

    public static void CalibrateExternalTrackingToHMD(Palforge.Sdk.Script.CoreUObject.Transform externalTrackingTransform)
    {
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "CalibrateExternalTrackingToHMD", SdkEnv.StructBytes(externalTrackingTransform, 96));
    }

    public static void BreakKey(Palforge.Sdk.Script.InputCore.Key inKey, out string interactionProfile, out Palforge.Sdk.Script.InputCore.EControllerHand hand, out string motionSource, out string indentifier, out string component)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(inKey, 24), StringArgument(""), Bytes<byte>(default), Bytes<long>(0), StringArgument(""), StringArgument("") };
        SdkEnv.CallStatic("HeadMountedDisplayFunctionLibrary", "BreakKey", arguments, out var outputs);
        interactionProfile = SdkEnv.Text(outputs[1]);
        hand = (Palforge.Sdk.Script.InputCore.EControllerHand)As<byte>(outputs[2]);
        motionSource = SdkEnv.Text(outputs[3]);
        indentifier = SdkEnv.Text(outputs[4]);
        component = SdkEnv.Text(outputs[5]);
    }
}
