// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRigSpline;

public class RigUnitDrawControlRigSpline : UStructValue
{
    public Palforge.Sdk.Script.ControlRigSpline.ControlRigSpline Spline =>
        new Palforge.Sdk.Script.ControlRigSpline.ControlRigSpline(Address + 0x40, Context);

    public Palforge.Sdk.Script.CoreUObject.LinearColor Color =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x58, Context);

    public float Thickness
    {
        get => ReadAt<float>(0x68);
        set => WriteAt(0x68, value);
    }

    public int Detail
    {
        get => ReadAt<int>(0x6C);
        set => WriteAt(0x6C, value);
    }

    public Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext ExecuteContext =>
        new Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext(Address + 0x8, Context);

    internal RigUnitDrawControlRigSpline(nint address, UnrealContext context) : base(address, context, "RigUnit_DrawControlRigSpline")
    {
    }

    private protected RigUnitDrawControlRigSpline(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitDrawControlRigSpline? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitDrawControlRigSpline>("RigUnit_DrawControlRigSpline");
    }
}
