// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRigSpline;

public class RigUnitParameterAtPercentage : UStructValue
{
    public Palforge.Sdk.Script.ControlRigSpline.ControlRigSpline Spline =>
        new Palforge.Sdk.Script.ControlRigSpline.ControlRigSpline(Address + 0x8, Context);

    public float Percentage
    {
        get => ReadAt<float>(0x20);
        set => WriteAt(0x20, value);
    }

    public float U
    {
        get => ReadAt<float>(0x24);
        set => WriteAt(0x24, value);
    }

    internal RigUnitParameterAtPercentage(nint address, UnrealContext context) : base(address, context, "RigUnit_ParameterAtPercentage")
    {
    }

    private protected RigUnitParameterAtPercentage(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitParameterAtPercentage? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitParameterAtPercentage>("RigUnit_ParameterAtPercentage");
    }
}
