// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.WinDualShock;

public class DualShockSpatializationSettings : Palforge.Sdk.Script.AudioExtensions.SoundfieldEncodingSettingsBase
{
    public float Spread
    {
        get => ReadAt<float>(0x28);
        set => WriteAt(0x28, value);
    }

    public int Priority
    {
        get => ReadAt<int>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public bool Passthrough
    {
        get => ReadBoolAt(0x30, 0xFF);
        set => WriteBoolAt(0x30, 0xFF, value);
    }

    internal DualShockSpatializationSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("DualShockSpatializationSettings");
    }

    public static new DualShockSpatializationSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("DualShockSpatializationSettings", outer) as DualShockSpatializationSettings;
    }

    public static new DualShockSpatializationSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as DualShockSpatializationSettings;
    }
}
