// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.StreamlineBlueprint;

public enum EStreamlineFeatureSupport
{
    Supported = 0,
    NotSupported = 1,
    NotSupportedIncompatibleHardware = 2,
    NotSupportedDriverOutOfDate = 3,
    NotSupportedOperatingSystemOutOfDate = 4,
    NotSupportedHardewareSchedulingDisabled = 5,
    NotSupportedByRHI = 6,
    NotSupportedByPlatformAtBuildTime = 7,
    NotSupportedIncompatibleAPICaptureToolActive = 8,
    EStreamlineFeatureSupportMax = 9
}
