// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public enum EGizmoElementViewDependentType
{
    None = 0,
    Axis = 1,
    Plane = 2,
    EGizmoElementViewDependentTypeMax = 3
}
