// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class GizmoTransformSource : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal GizmoTransformSource(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GizmoTransformSource");
    }

    public static new GizmoTransformSource? New(UObject? outer = null)
    {
        return SdkEnv.New("GizmoTransformSource", outer) as GizmoTransformSource;
    }

    public static new GizmoTransformSource? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GizmoTransformSource;
    }

    public void SetTransform(Palforge.Sdk.Script.CoreUObject.Transform newTransform)
    {
        Call("SetTransform", SdkEnv.StructBytes(newTransform, 96));
    }

    public Palforge.Sdk.Script.CoreUObject.Transform? GetTransform()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Transform>(this, "GetTransform", "Transform");
    }
}
