// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class GizmoElementBase : UObject
{
    public bool BEnabled
    {
        get => ReadBoolAt(0x28, 0xFF);
        set => WriteBoolAt(0x28, 0xFF, value);
    }

    public bool BEnabledForPerspectiveProjection
    {
        get => ReadBoolAt(0x29, 0xFF);
        set => WriteBoolAt(0x29, 0xFF, value);
    }

    public bool BEnabledForOrthographicProjection
    {
        get => ReadBoolAt(0x2A, 0xFF);
        set => WriteBoolAt(0x2A, 0xFF, value);
    }

    public bool BEnabledForDefaultState
    {
        get => ReadBoolAt(0x2B, 0xFF);
        set => WriteBoolAt(0x2B, 0xFF, value);
    }

    public bool BEnabledForHoveringState
    {
        get => ReadBoolAt(0x2C, 0xFF);
        set => WriteBoolAt(0x2C, 0xFF, value);
    }

    public bool BEnabledForInteractingState
    {
        get => ReadBoolAt(0x2D, 0xFF);
        set => WriteBoolAt(0x2D, 0xFF, value);
    }

    public uint PartIdentifier
    {
        get => ReadAt<uint>(0x30);
        set => WriteAt(0x30, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.GizmoElementMeshRenderStateAttributes MeshRenderAttributes =>
        new Palforge.Sdk.Script.InteractiveToolsFramework.GizmoElementMeshRenderStateAttributes(Address + 0x34, Context);

    public Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementState ElementState
    {
        get => (Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementState)ReadAt<byte>(0x94);
        set => WriteAt(0x94, (byte)value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementInteractionState ElementInteractionState
    {
        get => (Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementInteractionState)ReadAt<int>(0x98);
        set => WriteAt(0x98, (int)value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementViewDependentType ViewDependentType
    {
        get => (Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementViewDependentType)ReadAt<int>(0x9C);
        set => WriteAt(0x9C, (int)value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector ViewDependentAxis =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xA0, Context);

    public float ViewDependentAngleTol
    {
        get => ReadAt<float>(0xB8);
        set => WriteAt(0xB8, value);
    }

    public float ViewDependentAxialMaxCosAngleTol
    {
        get => ReadAt<float>(0xBC);
        set => WriteAt(0xBC, value);
    }

    public float ViewDependentPlanarMinCosAngleTol
    {
        get => ReadAt<float>(0xC0);
        set => WriteAt(0xC0, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementViewAlignType ViewAlignType
    {
        get => (Palforge.Sdk.Script.InteractiveToolsFramework.EGizmoElementViewAlignType)ReadAt<int>(0xC4);
        set => WriteAt(0xC4, (int)value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector ViewAlignAxis =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xC8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector ViewAlignNormal =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xE0, Context);

    public float ViewAlignAxialAngleTol
    {
        get => ReadAt<float>(0xF8);
        set => WriteAt(0xF8, value);
    }

    public float ViewAlignAxialMaxCosAngleTol
    {
        get => ReadAt<float>(0xFC);
        set => WriteAt(0xFC, value);
    }

    public float PixelHitDistanceThreshold
    {
        get => ReadAt<float>(0x100);
        set => WriteAt(0x100, value);
    }

    internal GizmoElementBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GizmoElementBase");
    }

    public static GizmoElementBase? New(UObject? outer = null)
    {
        return SdkEnv.New("GizmoElementBase", outer) as GizmoElementBase;
    }

    public static GizmoElementBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GizmoElementBase;
    }
}
