// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class GizmoAxisTranslationParameterSource : Palforge.Sdk.Script.InteractiveToolsFramework.GizmoBaseFloatParameterSource
{
    public UObject? AxisSource =>
        WrapAt(0x90);

    public UObject? TransformSource =>
        WrapAt(0xA0);

    public float Parameter
    {
        get => ReadAt<float>(0xB0);
        set => WriteAt(0xB0, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.GizmoFloatParameterChange LastChange =>
        new Palforge.Sdk.Script.InteractiveToolsFramework.GizmoFloatParameterChange(Address + 0xB4, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector CurTranslationAxis =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xC0, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector CurTranslationOrigin =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xD8, Context);

    public Palforge.Sdk.Script.CoreUObject.Transform InitialTransform =>
        new Palforge.Sdk.Script.CoreUObject.Transform(Address + 0xF0, Context);

    internal GizmoAxisTranslationParameterSource(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GizmoAxisTranslationParameterSource");
    }

    public static new GizmoAxisTranslationParameterSource? New(UObject? outer = null)
    {
        return SdkEnv.New("GizmoAxisTranslationParameterSource", outer) as GizmoAxisTranslationParameterSource;
    }

    public static new GizmoAxisTranslationParameterSource? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GizmoAxisTranslationParameterSource;
    }
}
