// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class InteractiveToolNestedAcceptCancelAPI : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal InteractiveToolNestedAcceptCancelAPI(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("InteractiveToolNestedAcceptCancelAPI");
    }

    public static new InteractiveToolNestedAcceptCancelAPI? New(UObject? outer = null)
    {
        return SdkEnv.New("InteractiveToolNestedAcceptCancelAPI", outer) as InteractiveToolNestedAcceptCancelAPI;
    }

    public static new InteractiveToolNestedAcceptCancelAPI? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as InteractiveToolNestedAcceptCancelAPI;
    }
}
