// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class InteractiveToolsContext : UObject
{
    public Palforge.Sdk.Script.InteractiveToolsFramework.InputRouter? InputRouter
    {
        get => WrapAt(0x58) as Palforge.Sdk.Script.InteractiveToolsFramework.InputRouter;
        set => WriteObjectAt(0x58, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.ToolTargetManager? TargetManager
    {
        get => WrapAt(0x60) as Palforge.Sdk.Script.InteractiveToolsFramework.ToolTargetManager;
        set => WriteObjectAt(0x60, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.InteractiveToolManager? ToolManager
    {
        get => WrapAt(0x68) as Palforge.Sdk.Script.InteractiveToolsFramework.InteractiveToolManager;
        set => WriteObjectAt(0x68, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.InteractiveGizmoManager? GizmoManager
    {
        get => WrapAt(0x70) as Palforge.Sdk.Script.InteractiveToolsFramework.InteractiveGizmoManager;
        set => WriteObjectAt(0x70, value);
    }

    public Palforge.Sdk.Script.InteractiveToolsFramework.ContextObjectStore? ContextObjectStore
    {
        get => WrapAt(0x78) as Palforge.Sdk.Script.InteractiveToolsFramework.ContextObjectStore;
        set => WriteObjectAt(0x78, value);
    }

    public string ToolManagerClass
    {
        get => ReadSoftPathAt(0x300);
        set => WriteSoftPathAt(0x300, value);
    }

    internal InteractiveToolsContext(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("InteractiveToolsContext");
    }

    public static InteractiveToolsContext? New(UObject? outer = null)
    {
        return SdkEnv.New("InteractiveToolsContext", outer) as InteractiveToolsContext;
    }

    public static InteractiveToolsContext? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as InteractiveToolsContext;
    }
}
