// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class MeshDescriptionProvider : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal MeshDescriptionProvider(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MeshDescriptionProvider");
    }

    public static new MeshDescriptionProvider? New(UObject? outer = null)
    {
        return SdkEnv.New("MeshDescriptionProvider", outer) as MeshDescriptionProvider;
    }

    public static new MeshDescriptionProvider? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MeshDescriptionProvider;
    }
}
