// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class RepositionableTransformGizmo : Palforge.Sdk.Script.InteractiveToolsFramework.CombinedTransformGizmo
{
    public Palforge.Sdk.Script.InteractiveToolsFramework.GizmoTransformChangeStateTarget? RepositionStateTarget
    {
        get => WrapAt(0x330) as Palforge.Sdk.Script.InteractiveToolsFramework.GizmoTransformChangeStateTarget;
        set => WriteObjectAt(0x330, value);
    }

    internal RepositionableTransformGizmo(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("RepositionableTransformGizmo");
    }

    public static new RepositionableTransformGizmo? New(UObject? outer = null)
    {
        return SdkEnv.New("RepositionableTransformGizmo", outer) as RepositionableTransformGizmo;
    }

    public static new RepositionableTransformGizmo? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as RepositionableTransformGizmo;
    }
}
