// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class SelectionSet : UObject
{
    internal SelectionSet(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SelectionSet");
    }

    public static SelectionSet? New(UObject? outer = null)
    {
        return SdkEnv.New("SelectionSet", outer) as SelectionSet;
    }

    public static SelectionSet? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SelectionSet;
    }
}
