// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.InteractiveToolsFramework;

public class StaticMeshBackedTarget : Palforge.Sdk.Script.InteractiveToolsFramework.AssetBackedTarget
{
    internal StaticMeshBackedTarget(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("StaticMeshBackedTarget");
    }

    public static new StaticMeshBackedTarget? New(UObject? outer = null)
    {
        return SdkEnv.New("StaticMeshBackedTarget", outer) as StaticMeshBackedTarget;
    }

    public static new StaticMeshBackedTarget? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as StaticMeshBackedTarget;
    }
}
