// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.WebBrowser;

public class WebJSCallbackBase : UStructValue
{
    internal WebJSCallbackBase(nint address, UnrealContext context) : base(address, context, "WebJSCallbackBase")
    {
    }

    private protected WebJSCallbackBase(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static WebJSCallbackBase? Allocate()
    {
        return SdkEnv.AllocateStruct<WebJSCallbackBase>("WebJSCallbackBase");
    }
}
