// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshDescription;

public class ElementID : UStructValue
{
    public int IDValue
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    internal ElementID(nint address, UnrealContext context) : base(address, context, "ElementID")
    {
    }

    private protected ElementID(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ElementID? Allocate()
    {
        return SdkEnv.AllocateStruct<ElementID>("ElementID");
    }
}
