// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshDescription;

public class Uvid : UStructValue
{
    public int IDValue
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    internal Uvid(nint address, UnrealContext context) : base(address, context, "UVID")
    {
    }

    private protected Uvid(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static Uvid? Allocate()
    {
        return SdkEnv.AllocateStruct<Uvid>("UVID");
    }
}
