// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MediaAssets;

public class MediaSourceCacheSettings : UStructValue
{
    public bool BOverride
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    public float TimeToLookAhead
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    internal MediaSourceCacheSettings(nint address, UnrealContext context) : base(address, context, "MediaSourceCacheSettings")
    {
    }

    private protected MediaSourceCacheSettings(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MediaSourceCacheSettings? Allocate()
    {
        return SdkEnv.AllocateStruct<MediaSourceCacheSettings>("MediaSourceCacheSettings");
    }
}
