// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.AkAudio;

public enum AkActionOnEventType
{
    Stop = 0,
    Pause = 1,
    Resume = 2,
    Break = 3,
    ReleaseEnvelope = 4,
    AkActionOnEventTypeMax = 5
}
