// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AkAudio;

public class AkAssetPlatformData : UObject
{
    public Palforge.Sdk.Script.AkAudio.AkAssetData? CurrentAssetData
    {
        get => WrapAt(0x28) as Palforge.Sdk.Script.AkAudio.AkAssetData;
        set => WriteObjectAt(0x28, value);
    }

    internal AkAssetPlatformData(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AkAssetPlatformData");
    }

    public static AkAssetPlatformData? New(UObject? outer = null)
    {
        return SdkEnv.New("AkAssetPlatformData", outer) as AkAssetPlatformData;
    }

    public static AkAssetPlatformData? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AkAssetPlatformData;
    }
}
