// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AkAudio;

public class AkReverbZone : Palforge.Sdk.Script.AkAudio.AkSpatialAudioVolume
{
    internal AkReverbZone(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AkReverbZone");
    }

    public static new AkReverbZone? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("AkReverbZone", owner, at) as AkReverbZone;
    }

    public static new AkReverbZone? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AkReverbZone;
    }
}
