// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AkAudio;

public class AkWwiseObjectDetails : UStructValue
{
    public string ItemName
    {
        get => ReadStringAt(0x0);
        set => WriteStringAt(0x0, value);
    }

    public string ItemPath
    {
        get => ReadStringAt(0x10);
        set => WriteStringAt(0x10, value);
    }

    public string ItemId
    {
        get => ReadStringAt(0x20);
        set => WriteStringAt(0x20, value);
    }

    internal AkWwiseObjectDetails(nint address, UnrealContext context) : base(address, context, "AkWwiseObjectDetails")
    {
    }

    private protected AkWwiseObjectDetails(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AkWwiseObjectDetails? Allocate()
    {
        return SdkEnv.AllocateStruct<AkWwiseObjectDetails>("AkWwiseObjectDetails");
    }
}
