// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AkAudio;

public class MovieSceneAkAudioRTPCSection : Palforge.Sdk.Script.MovieScene.MovieSceneSection
{
    public Palforge.Sdk.Script.AkAudio.AkRtpc? Rtpc
    {
        get => WrapAt(0xF0) as Palforge.Sdk.Script.AkAudio.AkRtpc;
        set => WriteObjectAt(0xF0, value);
    }

    public string Name2
    {
        get => ReadStringAt(0xF8);
        set => WriteStringAt(0xF8, value);
    }

    public Palforge.Sdk.Script.Engine.RichCurve FloatCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0x108, Context);

    public Palforge.Sdk.Script.AkAudio.MovieSceneFloatChannelSerializationHelper FloatChannelSerializationHelper =>
        new Palforge.Sdk.Script.AkAudio.MovieSceneFloatChannelSerializationHelper(Address + 0x188, Context);

    public Palforge.Sdk.Script.MovieScene.MovieSceneFloatChannel RTPCChannel =>
        new Palforge.Sdk.Script.MovieScene.MovieSceneFloatChannel(Address + 0x1B8, Context);

    internal MovieSceneAkAudioRTPCSection(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneAkAudioRTPCSection");
    }

    public static new MovieSceneAkAudioRTPCSection? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneAkAudioRTPCSection", outer) as MovieSceneAkAudioRTPCSection;
    }

    public static new MovieSceneAkAudioRTPCSection? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneAkAudioRTPCSection;
    }
}
