// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AkAudio;

public class SAkWaapiFieldNamesConv : Palforge.Sdk.Script.Engine.BlueprintFunctionLibrary
{
    internal SAkWaapiFieldNamesConv(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SAkWaapiFieldNamesConv");
    }

    public static new SAkWaapiFieldNamesConv? New(UObject? outer = null)
    {
        return SdkEnv.New("SAkWaapiFieldNamesConv", outer) as SAkWaapiFieldNamesConv;
    }

    public static new SAkWaapiFieldNamesConv? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SAkWaapiFieldNamesConv;
    }

    public static string ConvFAkWaapiFieldNamesToString(Palforge.Sdk.Script.AkAudio.AkWaapiFieldNames iNAkWaapiFieldNames)
    {
        return SdkEnv.Text(SdkEnv.CallStatic("SAkWaapiFieldNamesConv", "Conv_FAkWaapiFieldNamesToString", SdkEnv.StructBytes(iNAkWaapiFieldNames, 16)));
    }
}
