// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.OnlineSubsystemSteam;

public class SteamNetConnection : Palforge.Sdk.Script.OnlineSubsystemUtils.IpConnection
{
    public bool BIsPassthrough
    {
        get => ReadBoolAt(0x33A0, 0xFF);
        set => WriteBoolAt(0x33A0, 0xFF, value);
    }

    internal SteamNetConnection(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SteamNetConnection");
    }

    public static new SteamNetConnection? New(UObject? outer = null)
    {
        return SdkEnv.New("SteamNetConnection", outer) as SteamNetConnection;
    }

    public static new SteamNetConnection? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SteamNetConnection;
    }
}
