// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.ModelingComponents;

public enum ECreateObjectTypeHint
{
    Undefined = 0,
    StaticMesh = 1,
    Volume = 2,
    DynamicMeshActor = 3,
    ECreateObjectTypeHintMax = 4
}
