// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.ModelingComponents;

public enum ESpaceCurveControlPointOriginMode
{
    Shared = 0,
    First = 1,
    Last = 2,
    ESpaceCurveControlPointOriginModeMax = 3
}
