// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ModelingComponents;

public class MeshElementsVisualizer : Palforge.Sdk.Script.ModelingComponents.PreviewGeometry
{
    public Palforge.Sdk.Script.ModelingComponents.MeshElementsVisualizerProperties? Settings
    {
        get => WrapAt(0xD0) as Palforge.Sdk.Script.ModelingComponents.MeshElementsVisualizerProperties;
        set => WriteObjectAt(0xD0, value);
    }

    public Palforge.Sdk.Script.ModelingComponents.MeshWireframeComponent? WireframeComponent
    {
        get => WrapAt(0xD8) as Palforge.Sdk.Script.ModelingComponents.MeshWireframeComponent;
        set => WriteObjectAt(0xD8, value);
    }

    internal MeshElementsVisualizer(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MeshElementsVisualizer");
    }

    public static new MeshElementsVisualizer? New(UObject? outer = null)
    {
        return SdkEnv.New("MeshElementsVisualizer", outer) as MeshElementsVisualizer;
    }

    public static new MeshElementsVisualizer? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MeshElementsVisualizer;
    }
}
