// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.FSR2MovieRenderPipeline;

public class FSR2MoviePipelineSettings : Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelineViewFamilySetting
{
    public Palforge.Sdk.Script.FSR2MovieRenderPipeline.EFSR2MoviePipelineQuality FSR2Quality
    {
        get => (Palforge.Sdk.Script.FSR2MovieRenderPipeline.EFSR2MoviePipelineQuality)ReadAt<byte>(0x48);
        set => WriteAt(0x48, (byte)value);
    }

    internal FSR2MoviePipelineSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("FSR2MoviePipelineSettings");
    }

    public static new FSR2MoviePipelineSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("FSR2MoviePipelineSettings", outer) as FSR2MoviePipelineSettings;
    }

    public static new FSR2MoviePipelineSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as FSR2MoviePipelineSettings;
    }
}
