// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ChaosCaching;

public class PerParticleCacheData : UStructValue
{
    public Palforge.Sdk.Script.ChaosCaching.ParticleTransformTrack TransformData =>
        new Palforge.Sdk.Script.ChaosCaching.ParticleTransformTrack(Address + 0x0, Context);

    public UnrealMap<string, Palforge.Sdk.Script.Engine.RichCurve> CurveData =>
        new UnrealMap<string, Palforge.Sdk.Script.Engine.RichCurve>(this, 0x48, 0x90, 0x8, "CurveData", static (context, element) => context.NameAt(element), static (context, element) => new Palforge.Sdk.Script.Engine.RichCurve(element, context), static (context, value) => context.NameBytes(value), static (context, value) => context.BytesAt(value.Address, 0x80), null, null);

    internal PerParticleCacheData(nint address, UnrealContext context) : base(address, context, "PerParticleCacheData")
    {
    }

    private protected PerParticleCacheData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PerParticleCacheData? Allocate()
    {
        return SdkEnv.AllocateStruct<PerParticleCacheData>("PerParticleCacheData");
    }
}
