// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CommonUI;

public class CommonUISettings : UObject
{
    public bool BAutoLoadData
    {
        get => ReadBoolAt(0x28, 0xFF);
        set => WriteBoolAt(0x28, 0xFF, value);
    }

    public string DefaultImageResourceObject
    {
        get => ReadSoftPathAt(0x30);
        set => WriteSoftPathAt(0x30, value);
    }

    public string DefaultThrobberMaterial
    {
        get => ReadSoftPathAt(0x60);
        set => WriteSoftPathAt(0x60, value);
    }

    public string DefaultRichTextDataClass
    {
        get => ReadSoftPathAt(0x90);
        set => WriteSoftPathAt(0x90, value);
    }

    public UnrealArray<Palforge.Sdk.Script.GameplayTags.GameplayTag> PlatformTraits =>
        new UnrealArray<Palforge.Sdk.Script.GameplayTags.GameplayTag>(this, 0xC0, 0x8, "PlatformTraits", static (context, element) => new Palforge.Sdk.Script.GameplayTags.GameplayTag(element, context), static (context, value) => context.BytesAt(value.Address, 0x8), null);

    public UObject? DefaultImageResourceObjectInstance
    {
        get => WrapAt(0xF8);
        set => WriteObjectAt(0xF8, value);
    }

    public Palforge.Sdk.Script.Engine.MaterialInterface? DefaultThrobberMaterialInstance
    {
        get => WrapAt(0x100) as Palforge.Sdk.Script.Engine.MaterialInterface;
        set => WriteObjectAt(0x100, value);
    }

    public Palforge.Sdk.Script.SlateCore.SlateBrush DefaultThrobberBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x110, Context);

    public Palforge.Sdk.Script.CommonUI.CommonUIRichTextData? RichTextDataInstance
    {
        get => WrapAt(0x1E0) as Palforge.Sdk.Script.CommonUI.CommonUIRichTextData;
        set => WriteObjectAt(0x1E0, value);
    }

    internal CommonUISettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CommonUISettings");
    }

    public static CommonUISettings? New(UObject? outer = null)
    {
        return SdkEnv.New("CommonUISettings", outer) as CommonUISettings;
    }

    public static CommonUISettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CommonUISettings;
    }
}
