// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.SlateCore;

public class WindowStyle : UStructValue
{
    public Palforge.Sdk.Script.SlateCore.ButtonStyle MinimizeButtonStyle =>
        new Palforge.Sdk.Script.SlateCore.ButtonStyle(Address + 0x10, Context);

    public Palforge.Sdk.Script.SlateCore.ButtonStyle MaximizeButtonStyle =>
        new Palforge.Sdk.Script.SlateCore.ButtonStyle(Address + 0x400, Context);

    public Palforge.Sdk.Script.SlateCore.ButtonStyle RestoreButtonStyle =>
        new Palforge.Sdk.Script.SlateCore.ButtonStyle(Address + 0x7F0, Context);

    public Palforge.Sdk.Script.SlateCore.ButtonStyle CloseButtonStyle =>
        new Palforge.Sdk.Script.SlateCore.ButtonStyle(Address + 0xBE0, Context);

    public Palforge.Sdk.Script.SlateCore.TextBlockStyle TitleTextStyle =>
        new Palforge.Sdk.Script.SlateCore.TextBlockStyle(Address + 0xFD0, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush ActiveTitleBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x1320, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush InactiveTitleBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x13F0, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush FlashTitleBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x14C0, Context);

    public Palforge.Sdk.Script.SlateCore.SlateColor BackgroundColor =>
        new Palforge.Sdk.Script.SlateCore.SlateColor(Address + 0x1590, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush OutlineBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x15B0, Context);

    public Palforge.Sdk.Script.SlateCore.SlateColor OutlineColor =>
        new Palforge.Sdk.Script.SlateCore.SlateColor(Address + 0x1680, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush BorderBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x16A0, Context);

    public Palforge.Sdk.Script.SlateCore.SlateColor BorderColor =>
        new Palforge.Sdk.Script.SlateCore.SlateColor(Address + 0x1770, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush BackgroundBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x1790, Context);

    public Palforge.Sdk.Script.SlateCore.SlateBrush ChildBackgroundBrush =>
        new Palforge.Sdk.Script.SlateCore.SlateBrush(Address + 0x1860, Context);

    public int WindowCornerRadius
    {
        get => ReadAt<int>(0x1930);
        set => WriteAt(0x1930, value);
    }

    public Palforge.Sdk.Script.SlateCore.Margin BorderPadding =>
        new Palforge.Sdk.Script.SlateCore.Margin(Address + 0x1934, Context);

    internal WindowStyle(nint address, UnrealContext context) : base(address, context, "WindowStyle")
    {
    }

    private protected WindowStyle(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static WindowStyle? Allocate()
    {
        return SdkEnv.AllocateStruct<WindowStyle>("WindowStyle");
    }
}
