// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.OnlineSubsystemUtils;

public class AchievementQueryCallbackProxy : Palforge.Sdk.Script.Engine.OnlineBlueprintCallProxyBase
{
    internal AchievementQueryCallbackProxy(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AchievementQueryCallbackProxy");
    }

    public static new AchievementQueryCallbackProxy? New(UObject? outer = null)
    {
        return SdkEnv.New("AchievementQueryCallbackProxy", outer) as AchievementQueryCallbackProxy;
    }

    public static new AchievementQueryCallbackProxy? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AchievementQueryCallbackProxy;
    }

    public static Palforge.Sdk.Script.OnlineSubsystemUtils.AchievementQueryCallbackProxy? CacheAchievements(UObject? worldContextObject, Palforge.Sdk.Script.Engine.PlayerController? playerController)
    {
        return SdkEnv.Wrap(SdkEnv.CallStatic("AchievementQueryCallbackProxy", "CacheAchievements", Bytes<nint>(worldContextObject?.Address ?? 0), Bytes<nint>(playerController?.Address ?? 0))) as Palforge.Sdk.Script.OnlineSubsystemUtils.AchievementQueryCallbackProxy;
    }

    public static Palforge.Sdk.Script.OnlineSubsystemUtils.AchievementQueryCallbackProxy? CacheAchievementDescriptions(UObject? worldContextObject, Palforge.Sdk.Script.Engine.PlayerController? playerController)
    {
        return SdkEnv.Wrap(SdkEnv.CallStatic("AchievementQueryCallbackProxy", "CacheAchievementDescriptions", Bytes<nint>(worldContextObject?.Address ?? 0), Bytes<nint>(playerController?.Address ?? 0))) as Palforge.Sdk.Script.OnlineSubsystemUtils.AchievementQueryCallbackProxy;
    }
}
