// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Composure;

public class CompositingTextureLookupTable : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal CompositingTextureLookupTable(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CompositingTextureLookupTable");
    }

    public static new CompositingTextureLookupTable? New(UObject? outer = null)
    {
        return SdkEnv.New("CompositingTextureLookupTable", outer) as CompositingTextureLookupTable;
    }

    public static new CompositingTextureLookupTable? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CompositingTextureLookupTable;
    }

    public bool FindNamedPassResult(string lookupName, out Palforge.Sdk.Script.Engine.Texture? outTexture)
    {
        var arguments = new byte[][] { SdkEnv.NameBytes(lookupName), Bytes<nint>(0) };
        var result = Call("FindNamedPassResult", arguments, out var outputs);
        outTexture = SdkEnv.Wrap(outputs[1]) as Palforge.Sdk.Script.Engine.Texture;
        return As<byte>(result) is not 0;
    }
}
