// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Composure;

public class MovieSceneComposureExportPass : UStructValue
{
    public string TransformPassName
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public bool BRenamePass
    {
        get => ReadBoolAt(0x8, 0xFF);
        set => WriteBoolAt(0x8, 0xFF, value);
    }

    public string ExportedAs
    {
        get => ReadNameAt(0xC);
        set => WriteNameAt(0xC, value);
    }

    internal MovieSceneComposureExportPass(nint address, UnrealContext context) : base(address, context, "MovieSceneComposureExportPass")
    {
    }

    private protected MovieSceneComposureExportPass(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneComposureExportPass? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneComposureExportPass>("MovieSceneComposureExportPass");
    }
}
