// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Flow;

public class FlowNodeCustomInput : Palforge.Sdk.Script.Flow.FlowNodeCustomEventBase
{
    internal FlowNodeCustomInput(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("FlowNode_CustomInput");
    }

    public static new FlowNodeCustomInput? New(UObject? outer = null)
    {
        return SdkEnv.New("FlowNode_CustomInput", outer) as FlowNodeCustomInput;
    }

    public static new FlowNodeCustomInput? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as FlowNodeCustomInput;
    }
}
