// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Flow;

public class FlowAssetSaveData : UStructValue
{
    public string WorldName
    {
        get => ReadStringAt(0x0);
        set => WriteStringAt(0x0, value);
    }

    public string InstanceName
    {
        get => ReadStringAt(0x10);
        set => WriteStringAt(0x10, value);
    }

    public UnrealArray<byte> AssetData =>
        new UnrealArray<byte>(this, 0x20, 0x1, "AssetData", static (context, element) => context.ValueAt<byte>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<Palforge.Sdk.Script.Flow.FlowNodeSaveData> NodeRecords =>
        new UnrealArray<Palforge.Sdk.Script.Flow.FlowNodeSaveData>(this, 0x30, 0x20, "NodeRecords", static (context, element) => new Palforge.Sdk.Script.Flow.FlowNodeSaveData(element, context), static (context, value) => context.BytesAt(value.Address, 0x20), null);

    internal FlowAssetSaveData(nint address, UnrealContext context) : base(address, context, "FlowAssetSaveData")
    {
    }

    private protected FlowAssetSaveData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static FlowAssetSaveData? Allocate()
    {
        return SdkEnv.AllocateStruct<FlowAssetSaveData>("FlowAssetSaveData");
    }
}
