// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Flow;

public class FlowNodeCounter : Palforge.Sdk.Script.Flow.FlowNode
{
    public int Goal
    {
        get => ReadAt<int>(0xD8);
        set => WriteAt(0xD8, value);
    }

    public int CurrentSum
    {
        get => ReadAt<int>(0xDC);
        set => WriteAt(0xDC, value);
    }

    internal FlowNodeCounter(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("FlowNode_Counter");
    }

    public static new FlowNodeCounter? New(UObject? outer = null)
    {
        return SdkEnv.New("FlowNode_Counter", outer) as FlowNodeCounter;
    }

    public static new FlowNodeCounter? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as FlowNodeCounter;
    }
}
