// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AlphaBlendArgs : UStructValue
{
    public Palforge.Sdk.Script.Engine.CurveFloat? CustomCurve
    {
        get => WrapAt(0x0) as Palforge.Sdk.Script.Engine.CurveFloat;
        set => WriteObjectAt(0x0, value);
    }

    public float BlendTime
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public Palforge.Sdk.Script.Engine.EAlphaBlendOption BlendOption
    {
        get => (Palforge.Sdk.Script.Engine.EAlphaBlendOption)ReadAt<byte>(0xC);
        set => WriteAt(0xC, (byte)value);
    }

    internal AlphaBlendArgs(nint address, UnrealContext context) : base(address, context, "AlphaBlendArgs")
    {
    }

    private protected AlphaBlendArgs(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AlphaBlendArgs? Allocate()
    {
        return SdkEnv.AllocateStruct<AlphaBlendArgs>("AlphaBlendArgs");
    }
}
