// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AnimDataModelNotifPayload : UStructValue
{
    internal AnimDataModelNotifPayload(nint address, UnrealContext context) : base(address, context, "AnimDataModelNotifPayload")
    {
    }

    private protected AnimDataModelNotifPayload(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AnimDataModelNotifPayload? Allocate()
    {
        return SdkEnv.AllocateStruct<AnimDataModelNotifPayload>("AnimDataModelNotifPayload");
    }
}
