// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AnimSubsystemTag : UStructValue
{
    public UnrealMap<string, int> NodeIndices =>
        new UnrealMap<string, int>(this, 0x8, 0x14, 0x8, "NodeIndices", static (context, element) => context.NameAt(element), static (context, element) => context.ValueAt<int>(element), static (context, value) => context.NameBytes(value), static (context, value) => Bytes(value), null, null);

    internal AnimSubsystemTag(nint address, UnrealContext context) : base(address, context, "AnimSubsystem_Tag")
    {
    }

    private protected AnimSubsystemTag(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AnimSubsystemTag? Allocate()
    {
        return SdkEnv.AllocateStruct<AnimSubsystemTag>("AnimSubsystem_Tag");
    }
}
