// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AnimNodeLinkedInputPose : UStructValue
{
    public string Name
    {
        get => ReadNameAt(0x10);
        set => WriteNameAt(0x10, value);
    }

    public string Graph
    {
        get => ReadNameAt(0x18);
        set => WriteNameAt(0x18, value);
    }

    public Palforge.Sdk.Script.Engine.PoseLink InputPose =>
        new Palforge.Sdk.Script.Engine.PoseLink(Address + 0x20, Context);

    internal AnimNodeLinkedInputPose(nint address, UnrealContext context) : base(address, context, "AnimNode_LinkedInputPose")
    {
    }

    private protected AnimNodeLinkedInputPose(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AnimNodeLinkedInputPose? Allocate()
    {
        return SdkEnv.AllocateStruct<AnimNodeLinkedInputPose>("AnimNode_LinkedInputPose");
    }
}
