// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AnimationAsset : UObject
{
    public Palforge.Sdk.Script.Engine.Skeleton? Skeleton
    {
        get => WrapAt(0x38) as Palforge.Sdk.Script.Engine.Skeleton;
        set => WriteObjectAt(0x38, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Engine.AnimMetaData?> Metadata =>
        new UnrealArray<Palforge.Sdk.Script.Engine.AnimMetaData?>(this, 0x60, 0x8, "Metadata", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.AnimMetaData, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UnrealArray<Palforge.Sdk.Script.Engine.AssetUserData?> AssetUserData =>
        new UnrealArray<Palforge.Sdk.Script.Engine.AssetUserData?>(this, 0x70, 0x8, "AssetUserData", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.AssetUserData, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal AnimationAsset(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AnimationAsset");
    }

    public static AnimationAsset? New(UObject? outer = null)
    {
        return SdkEnv.New("AnimationAsset", outer) as AnimationAsset;
    }

    public static AnimationAsset? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AnimationAsset;
    }

    public float GetPlayLength()
    {
        return As<float>(Call("GetPlayLength"));
    }
}
