// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class AtmosphericFog : Palforge.Sdk.Script.Engine.Info
{
    public Palforge.Sdk.Script.Engine.AtmosphericFogComponent? AtmosphericFogComponent
    {
        get => WrapAt(0x290) as Palforge.Sdk.Script.Engine.AtmosphericFogComponent;
        set => WriteObjectAt(0x290, value);
    }

    internal AtmosphericFog(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AtmosphericFog");
    }

    public static new AtmosphericFog? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("AtmosphericFog", owner, at) as AtmosphericFog;
    }

    public static new AtmosphericFog? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AtmosphericFog;
    }
}
