// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class BlueprintEditorPromotionSettings : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.FilePath FirstMeshPath =>
        new Palforge.Sdk.Script.CoreUObject.FilePath(Address + 0x0, Context);

    public Palforge.Sdk.Script.CoreUObject.FilePath SecondMeshPath =>
        new Palforge.Sdk.Script.CoreUObject.FilePath(Address + 0x10, Context);

    public Palforge.Sdk.Script.CoreUObject.FilePath DefaultParticleAsset =>
        new Palforge.Sdk.Script.CoreUObject.FilePath(Address + 0x20, Context);

    internal BlueprintEditorPromotionSettings(nint address, UnrealContext context) : base(address, context, "BlueprintEditorPromotionSettings")
    {
    }

    private protected BlueprintEditorPromotionSettings(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static BlueprintEditorPromotionSettings? Allocate()
    {
        return SdkEnv.AllocateStruct<BlueprintEditorPromotionSettings>("BlueprintEditorPromotionSettings");
    }
}
