// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class CloudStorageBase : Palforge.Sdk.Script.Engine.PlatformInterfaceBase
{
    public UnrealArray<string> LocalCloudFiles =>
        new UnrealArray<string>(this, 0x38, 0x10, "LocalCloudFiles", static (context, element) => context.StringAt(element), static (context, value) => context.StringValueBytes(value), static (context, bytes) => context.ReleaseStringValue(bytes));

    public bool BSuppressDelegateCalls
    {
        get => ReadBoolAt(0x48, 0x1);
        set => WriteBoolAt(0x48, 0x1, value);
    }

    internal CloudStorageBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CloudStorageBase");
    }

    public static new CloudStorageBase? New(UObject? outer = null)
    {
        return SdkEnv.New("CloudStorageBase", outer) as CloudStorageBase;
    }

    public static new CloudStorageBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CloudStorageBase;
    }
}
