// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class CollisionImpactData : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.Engine.RigidBodyContactInfo> ContactInfos =>
        new UnrealArray<Palforge.Sdk.Script.Engine.RigidBodyContactInfo>(this, 0x0, 0x48, "ContactInfos", static (context, element) => new Palforge.Sdk.Script.Engine.RigidBodyContactInfo(element, context), static (context, value) => context.BytesAt(value.Address, 0x48), null);

    public Palforge.Sdk.Script.CoreUObject.Vector TotalNormalImpulse =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x10, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector TotalFrictionImpulse =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x28, Context);

    public bool BIsVelocityDeltaUnderThreshold
    {
        get => ReadBoolAt(0x40, 0xFF);
        set => WriteBoolAt(0x40, 0xFF, value);
    }

    internal CollisionImpactData(nint address, UnrealContext context) : base(address, context, "CollisionImpactData")
    {
    }

    private protected CollisionImpactData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CollisionImpactData? Allocate()
    {
        return SdkEnv.AllocateStruct<CollisionImpactData>("CollisionImpactData");
    }
}
