// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class CompressedTrack : UStructValue
{
    public UnrealArray<byte> ByteStream =>
        new UnrealArray<byte>(this, 0x0, 0x1, "ByteStream", static (context, element) => context.ValueAt<byte>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<float> Times =>
        new UnrealArray<float>(this, 0x10, 0x4, "Times", static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes(value), null);

    public float Mins
    {
        get => ReadAt<float>(0x20);
        set => WriteAt(0x20, value);
    }

    public float Ranges
    {
        get => ReadAt<float>(0x2C);
        set => WriteAt(0x2C, value);
    }

    internal CompressedTrack(nint address, UnrealContext context) : base(address, context, "CompressedTrack")
    {
    }

    private protected CompressedTrack(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CompressedTrack? Allocate()
    {
        return SdkEnv.AllocateStruct<CompressedTrack>("CompressedTrack");
    }
}
