// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ConstraintInstanceBase : UStructValue
{
    internal ConstraintInstanceBase(nint address, UnrealContext context) : base(address, context, "ConstraintInstanceBase")
    {
    }

    private protected ConstraintInstanceBase(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ConstraintInstanceBase? Allocate()
    {
        return SdkEnv.AllocateStruct<ConstraintInstanceBase>("ConstraintInstanceBase");
    }
}
