// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class CurveEdTab : UStructValue
{
    public string TabName
    {
        get => ReadStringAt(0x0);
        set => WriteStringAt(0x0, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Engine.CurveEdEntry> Curves =>
        new UnrealArray<Palforge.Sdk.Script.Engine.CurveEdEntry>(this, 0x10, 0x38, "Curves", static (context, element) => new Palforge.Sdk.Script.Engine.CurveEdEntry(element, context), static (context, value) => context.BytesAt(value.Address, 0x38), null);

    public float ViewStartInput
    {
        get => ReadAt<float>(0x20);
        set => WriteAt(0x20, value);
    }

    public float ViewEndInput
    {
        get => ReadAt<float>(0x24);
        set => WriteAt(0x24, value);
    }

    public float ViewStartOutput
    {
        get => ReadAt<float>(0x28);
        set => WriteAt(0x28, value);
    }

    public float ViewEndOutput
    {
        get => ReadAt<float>(0x2C);
        set => WriteAt(0x2C, value);
    }

    internal CurveEdTab(nint address, UnrealContext context) : base(address, context, "CurveEdTab")
    {
    }

    private protected CurveEdTab(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CurveEdTab? Allocate()
    {
        return SdkEnv.AllocateStruct<CurveEdTab>("CurveEdTab");
    }
}
