// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class CustomDefine : UStructValue
{
    public string DefineName
    {
        get => ReadStringAt(0x0);
        set => WriteStringAt(0x0, value);
    }

    public string DefineValue
    {
        get => ReadStringAt(0x10);
        set => WriteStringAt(0x10, value);
    }

    internal CustomDefine(nint address, UnrealContext context) : base(address, context, "CustomDefine")
    {
    }

    private protected CustomDefine(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CustomDefine? Allocate()
    {
        return SdkEnv.AllocateStruct<CustomDefine>("CustomDefine");
    }
}
