// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class DataCacheDuplicatedObjectData : UStructValue
{
    internal DataCacheDuplicatedObjectData(nint address, UnrealContext context) : base(address, context, "DataCacheDuplicatedObjectData")
    {
    }

    private protected DataCacheDuplicatedObjectData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static DataCacheDuplicatedObjectData? Allocate()
    {
        return SdkEnv.AllocateStruct<DataCacheDuplicatedObjectData>("DataCacheDuplicatedObjectData");
    }
}
