// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class DebuggingInfoForSingleFunction : UStructValue
{
    internal DebuggingInfoForSingleFunction(nint address, UnrealContext context) : base(address, context, "DebuggingInfoForSingleFunction")
    {
    }

    private protected DebuggingInfoForSingleFunction(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static DebuggingInfoForSingleFunction? Allocate()
    {
        return SdkEnv.AllocateStruct<DebuggingInfoForSingleFunction>("DebuggingInfoForSingleFunction");
    }
}
