// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum EAttenuationDistanceModel
{
    Linear = 0,
    Logarithmic = 1,
    Inverse = 2,
    LogReverse = 3,
    NaturalSound = 4,
    Custom = 5,
    EAttenuationDistanceModelMax = 6
}
