// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum EFFTSize
{
    DefaultSize = 0,
    Min = 1,
    Small = 2,
    Medium = 3,
    Large = 4,
    VeryLarge = 5,
    Max = 6
}
