// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum EMeshCameraFacingUpAxis
{
    CameraFacingNoneUP = 0,
    CameraFacingZUp = 1,
    CameraFacingNegativeZUp = 2,
    CameraFacingYUp = 3,
    CameraFacingNegativeYUp = 4,
    CameraFacingMax = 5
}
