// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class EngineHandlerComponentFactory : Palforge.Sdk.Script.PacketHandler.HandlerComponentFactory
{
    internal EngineHandlerComponentFactory(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("EngineHandlerComponentFactory");
    }

    public static new EngineHandlerComponentFactory? New(UObject? outer = null)
    {
        return SdkEnv.New("EngineHandlerComponentFactory", outer) as EngineHandlerComponentFactory;
    }

    public static new EngineHandlerComponentFactory? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as EngineHandlerComponentFactory;
    }
}
