// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum EOccludedGeometryFilteringPolicy
{
    NoOcclusionFiltering = 0,
    VisibilityBasedFiltering = 1,
    EOccludedGeometryFilteringPolicyMax = 2
}
