// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum EPingType
{
    None = 0,
    RoundTrip = 1,
    RoundTripExclFrame = 2,
    Icmp = 4,
    UDPQoS = 8,
    Max = 8,
    Count = 4
}
