// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum ETextureSizingType
{
    TextureSizingTypeUseSingleTextureSize = 0,
    TextureSizingTypeUseAutomaticBiasedSizes = 1,
    TextureSizingTypeUseManualOverrideTextureSize = 2,
    TextureSizingTypeUseSimplygonAutomaticSizing = 3,
    TextureSizingTypeAutomaticFromTexelDensity = 4,
    TextureSizingTypeAutomaticFromMeshScreenSize = 5,
    TextureSizingTypeAutomaticFromMeshDrawDistance = 6,
    TextureSizingTypeMax = 7
}
