// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ExposureSettings : UStructValue
{
    public float FixedEV100
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public bool BFixed
    {
        get => ReadBoolAt(0x4, 0xFF);
        set => WriteBoolAt(0x4, 0xFF, value);
    }

    internal ExposureSettings(nint address, UnrealContext context) : base(address, context, "ExposureSettings")
    {
    }

    private protected ExposureSettings(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ExposureSettings? Allocate()
    {
        return SdkEnv.AllocateStruct<ExposureSettings>("ExposureSettings");
    }
}
