// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class GameUserSettings : UObject
{
    public bool BUseVSync
    {
        get => ReadBoolAt(0x28, 0xFF);
        set => WriteBoolAt(0x28, 0xFF, value);
    }

    public bool BUseDynamicResolution
    {
        get => ReadBoolAt(0x29, 0xFF);
        set => WriteBoolAt(0x29, 0xFF, value);
    }

    public uint ResolutionSizeX
    {
        get => ReadAt<uint>(0x88);
        set => WriteAt(0x88, value);
    }

    public uint ResolutionSizeY
    {
        get => ReadAt<uint>(0x8C);
        set => WriteAt(0x8C, value);
    }

    public uint LastUserConfirmedResolutionSizeX
    {
        get => ReadAt<uint>(0x90);
        set => WriteAt(0x90, value);
    }

    public uint LastUserConfirmedResolutionSizeY
    {
        get => ReadAt<uint>(0x94);
        set => WriteAt(0x94, value);
    }

    public int WindowPosX
    {
        get => ReadAt<int>(0x98);
        set => WriteAt(0x98, value);
    }

    public int WindowPosY
    {
        get => ReadAt<int>(0x9C);
        set => WriteAt(0x9C, value);
    }

    public int FullscreenMode
    {
        get => ReadAt<int>(0xA0);
        set => WriteAt(0xA0, value);
    }

    public int LastConfirmedFullscreenMode
    {
        get => ReadAt<int>(0xA4);
        set => WriteAt(0xA4, value);
    }

    public int PreferredFullscreenMode
    {
        get => ReadAt<int>(0xA8);
        set => WriteAt(0xA8, value);
    }

    public uint Version
    {
        get => ReadAt<uint>(0xAC);
        set => WriteAt(0xAC, value);
    }

    public int AudioQualityLevel
    {
        get => ReadAt<int>(0xB0);
        set => WriteAt(0xB0, value);
    }

    public int LastConfirmedAudioQualityLevel
    {
        get => ReadAt<int>(0xB4);
        set => WriteAt(0xB4, value);
    }

    public float FrameRateLimit
    {
        get => ReadAt<float>(0xB8);
        set => WriteAt(0xB8, value);
    }

    public int DesiredScreenWidth
    {
        get => ReadAt<int>(0xC0);
        set => WriteAt(0xC0, value);
    }

    public bool BUseDesiredScreenHeight
    {
        get => ReadBoolAt(0xC4, 0xFF);
        set => WriteBoolAt(0xC4, 0xFF, value);
    }

    public int DesiredScreenHeight
    {
        get => ReadAt<int>(0xC8);
        set => WriteAt(0xC8, value);
    }

    public int LastUserConfirmedDesiredScreenWidth
    {
        get => ReadAt<int>(0xCC);
        set => WriteAt(0xCC, value);
    }

    public int LastUserConfirmedDesiredScreenHeight
    {
        get => ReadAt<int>(0xD0);
        set => WriteAt(0xD0, value);
    }

    public float LastRecommendedScreenWidth
    {
        get => ReadAt<float>(0xD4);
        set => WriteAt(0xD4, value);
    }

    public float LastRecommendedScreenHeight
    {
        get => ReadAt<float>(0xD8);
        set => WriteAt(0xD8, value);
    }

    public float LastCPUBenchmarkResult
    {
        get => ReadAt<float>(0xDC);
        set => WriteAt(0xDC, value);
    }

    public float LastGPUBenchmarkResult
    {
        get => ReadAt<float>(0xE0);
        set => WriteAt(0xE0, value);
    }

    public UnrealArray<float> LastCPUBenchmarkSteps =>
        new UnrealArray<float>(this, 0xE8, 0x4, "LastCPUBenchmarkSteps", static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<float> LastGPUBenchmarkSteps =>
        new UnrealArray<float>(this, 0xF8, 0x4, "LastGPUBenchmarkSteps", static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes(value), null);

    public float LastGPUBenchmarkMultiplier
    {
        get => ReadAt<float>(0x108);
        set => WriteAt(0x108, value);
    }

    public bool BUseHDRDisplayOutput
    {
        get => ReadBoolAt(0x10C, 0xFF);
        set => WriteBoolAt(0x10C, 0xFF, value);
    }

    public int HDRDisplayOutputNits
    {
        get => ReadAt<int>(0x110);
        set => WriteAt(0x110, value);
    }

    internal GameUserSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GameUserSettings");
    }

    public static GameUserSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("GameUserSettings", outer) as GameUserSettings;
    }

    public static GameUserSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GameUserSettings;
    }

    public void ValidateSettings()
    {
        Call("ValidateSettings");
    }

    public bool SupportsHDRDisplayOutput()
    {
        return As<byte>(Call("SupportsHDRDisplayOutput")) is not 0;
    }

    public void SetVSyncEnabled(bool bEnable)
    {
        Call("SetVSyncEnabled", Bytes<byte>(bEnable ? (byte)1 : (byte)0));
    }

    public void SetVisualEffectQuality(int value)
    {
        Call("SetVisualEffectQuality", Bytes(value));
    }

    public void SetViewDistanceQuality(int value)
    {
        Call("SetViewDistanceQuality", Bytes(value));
    }

    public void SetToDefaults()
    {
        Call("SetToDefaults");
    }

    public void SetTextureQuality(int value)
    {
        Call("SetTextureQuality", Bytes(value));
    }

    public void SetShadowQuality(int value)
    {
        Call("SetShadowQuality", Bytes(value));
    }

    public void SetShadingQuality(int value)
    {
        Call("SetShadingQuality", Bytes(value));
    }

    public void SetScreenResolution(Palforge.Sdk.Script.CoreUObject.IntPoint resolution)
    {
        Call("SetScreenResolution", SdkEnv.StructBytes(resolution, 8));
    }

    public void SetResolutionScaleValueEx(float newScaleValue)
    {
        Call("SetResolutionScaleValueEx", Bytes(newScaleValue));
    }

    public void SetResolutionScaleValue(int newScaleValue)
    {
        Call("SetResolutionScaleValue", Bytes(newScaleValue));
    }

    public void SetResolutionScaleNormalized(float newScaleNormalized)
    {
        Call("SetResolutionScaleNormalized", Bytes(newScaleNormalized));
    }

    public void SetReflectionQuality(int value)
    {
        Call("SetReflectionQuality", Bytes(value));
    }

    public void SetPostProcessingQuality(int value)
    {
        Call("SetPostProcessingQuality", Bytes(value));
    }

    public void SetOverallScalabilityLevel(int value)
    {
        Call("SetOverallScalabilityLevel", Bytes(value));
    }

    public void SetGlobalIlluminationQuality(int value)
    {
        Call("SetGlobalIlluminationQuality", Bytes(value));
    }

    public void SetFullscreenMode(byte inFullscreenMode)
    {
        Call("SetFullscreenMode", Bytes(inFullscreenMode));
    }

    public void SetFrameRateLimit(float newLimit)
    {
        Call("SetFrameRateLimit", Bytes(newLimit));
    }

    public void SetFoliageQuality(int value)
    {
        Call("SetFoliageQuality", Bytes(value));
    }

    public void SetDynamicResolutionEnabled(bool bEnable)
    {
        Call("SetDynamicResolutionEnabled", Bytes<byte>(bEnable ? (byte)1 : (byte)0));
    }

    public void SetBenchmarkFallbackValues()
    {
        Call("SetBenchmarkFallbackValues");
    }

    public void SetAudioQualityLevel(int qualityLevel)
    {
        Call("SetAudioQualityLevel", Bytes(qualityLevel));
    }

    public void SetAntiAliasingQuality(int value)
    {
        Call("SetAntiAliasingQuality", Bytes(value));
    }

    public void SaveSettings()
    {
        Call("SaveSettings");
    }

    public void RunHardwareBenchmark(int workScale, float cPUMultiplier, float gPUMultiplier)
    {
        Call("RunHardwareBenchmark", Bytes(workScale), Bytes(cPUMultiplier), Bytes(gPUMultiplier));
    }

    public void RevertVideoMode()
    {
        Call("RevertVideoMode");
    }

    public void ResetToCurrentSettings()
    {
        Call("ResetToCurrentSettings");
    }

    public void LoadSettings(bool bForceReload)
    {
        Call("LoadSettings", Bytes<byte>(bForceReload ? (byte)1 : (byte)0));
    }

    public bool IsVSyncEnabled()
    {
        return As<byte>(Call("IsVSyncEnabled")) is not 0;
    }

    public bool IsVSyncDirty()
    {
        return As<byte>(Call("IsVSyncDirty")) is not 0;
    }

    public bool IsScreenResolutionDirty()
    {
        return As<byte>(Call("IsScreenResolutionDirty")) is not 0;
    }

    public bool IsHDREnabled()
    {
        return As<byte>(Call("IsHDREnabled")) is not 0;
    }

    public bool IsFullscreenModeDirty()
    {
        return As<byte>(Call("IsFullscreenModeDirty")) is not 0;
    }

    public bool IsDynamicResolutionEnabled()
    {
        return As<byte>(Call("IsDynamicResolutionEnabled")) is not 0;
    }

    public bool IsDynamicResolutionDirty()
    {
        return As<byte>(Call("IsDynamicResolutionDirty")) is not 0;
    }

    public bool IsDirty()
    {
        return As<byte>(Call("IsDirty")) is not 0;
    }

    public int GetVisualEffectQuality()
    {
        return As<int>(Call("GetVisualEffectQuality"));
    }

    public int GetViewDistanceQuality()
    {
        return As<int>(Call("GetViewDistanceQuality"));
    }

    public int GetTextureQuality()
    {
        return As<int>(Call("GetTextureQuality"));
    }

    public static int GetSyncInterval()
    {
        return As<int>(SdkEnv.CallStatic("GameUserSettings", "GetSyncInterval"));
    }

    public int GetShadowQuality()
    {
        return As<int>(Call("GetShadowQuality"));
    }

    public int GetShadingQuality()
    {
        return As<int>(Call("GetShadingQuality"));
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint? GetScreenResolution()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.IntPoint>(this, "GetScreenResolution", "IntPoint");
    }

    public float GetResolutionScaleNormalized()
    {
        return As<float>(Call("GetResolutionScaleNormalized"));
    }

    public void GetResolutionScaleInformationEx(out float currentScaleNormalized, out float currentScaleValue, out float minScaleValue, out float maxScaleValue)
    {
        var arguments = new byte[][] { Bytes<float>(default), Bytes<float>(default), Bytes<float>(default), Bytes<float>(default) };
        Call("GetResolutionScaleInformationEx", arguments, out var outputs);
        currentScaleNormalized = As<float>(outputs[0]);
        currentScaleValue = As<float>(outputs[1]);
        minScaleValue = As<float>(outputs[2]);
        maxScaleValue = As<float>(outputs[3]);
    }

    public void GetResolutionScaleInformation(out float currentScaleNormalized, out int currentScaleValue, out int minScaleValue, out int maxScaleValue)
    {
        var arguments = new byte[][] { Bytes<float>(default), Bytes<int>(default), Bytes<int>(default), Bytes<int>(default) };
        Call("GetResolutionScaleInformation", arguments, out var outputs);
        currentScaleNormalized = As<float>(outputs[0]);
        currentScaleValue = As<int>(outputs[1]);
        minScaleValue = As<int>(outputs[2]);
        maxScaleValue = As<int>(outputs[3]);
    }

    public int GetReflectionQuality()
    {
        return As<int>(Call("GetReflectionQuality"));
    }

    public float GetRecommendedResolutionScale()
    {
        return As<float>(Call("GetRecommendedResolutionScale"));
    }

    public byte GetPreferredFullscreenMode()
    {
        return As<byte>(Call("GetPreferredFullscreenMode"));
    }

    public int GetPostProcessingQuality()
    {
        return As<int>(Call("GetPostProcessingQuality"));
    }

    public int GetOverallScalabilityLevel()
    {
        return As<int>(Call("GetOverallScalabilityLevel"));
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint? GetLastConfirmedScreenResolution()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.IntPoint>(this, "GetLastConfirmedScreenResolution", "IntPoint");
    }

    public byte GetLastConfirmedFullscreenMode()
    {
        return As<byte>(Call("GetLastConfirmedFullscreenMode"));
    }

    public int GetGlobalIlluminationQuality()
    {
        return As<int>(Call("GetGlobalIlluminationQuality"));
    }

    public static Palforge.Sdk.Script.Engine.GameUserSettings? GetGameUserSettings()
    {
        return SdkEnv.Wrap(SdkEnv.CallStatic("GameUserSettings", "GetGameUserSettings")) as Palforge.Sdk.Script.Engine.GameUserSettings;
    }

    public byte GetFullscreenMode()
    {
        return As<byte>(Call("GetFullscreenMode"));
    }

    public float GetFrameRateLimit()
    {
        return As<float>(Call("GetFrameRateLimit"));
    }

    public static int GetFramePace()
    {
        return As<int>(SdkEnv.CallStatic("GameUserSettings", "GetFramePace"));
    }

    public int GetFoliageQuality()
    {
        return As<int>(Call("GetFoliageQuality"));
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint? GetDesktopResolution()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.IntPoint>(this, "GetDesktopResolution", "IntPoint");
    }

    public static Palforge.Sdk.Script.CoreUObject.IntPoint? GetDefaultWindowPosition()
    {
        return SdkEnv.CallStaticForStruct<Palforge.Sdk.Script.CoreUObject.IntPoint>("GameUserSettings", "GetDefaultWindowPosition", "IntPoint");
    }

    public static byte GetDefaultWindowMode()
    {
        return As<byte>(SdkEnv.CallStatic("GameUserSettings", "GetDefaultWindowMode"));
    }

    public float GetDefaultResolutionScale()
    {
        return As<float>(Call("GetDefaultResolutionScale"));
    }

    public static Palforge.Sdk.Script.CoreUObject.IntPoint? GetDefaultResolution()
    {
        return SdkEnv.CallStaticForStruct<Palforge.Sdk.Script.CoreUObject.IntPoint>("GameUserSettings", "GetDefaultResolution", "IntPoint");
    }

    public int GetCurrentHDRDisplayNits()
    {
        return As<int>(Call("GetCurrentHDRDisplayNits"));
    }

    public int GetAudioQualityLevel()
    {
        return As<int>(Call("GetAudioQualityLevel"));
    }

    public int GetAntiAliasingQuality()
    {
        return As<int>(Call("GetAntiAliasingQuality"));
    }

    public void EnableHDRDisplayOutput(bool bEnable, int displayNits)
    {
        Call("EnableHDRDisplayOutput", Bytes<byte>(bEnable ? (byte)1 : (byte)0), Bytes(displayNits));
    }

    public void ConfirmVideoMode()
    {
        Call("ConfirmVideoMode");
    }

    public void ApplySettings(bool bCheckForCommandLineOverrides)
    {
        Call("ApplySettings", Bytes<byte>(bCheckForCommandLineOverrides ? (byte)1 : (byte)0));
    }

    public void ApplyResolutionSettings(bool bCheckForCommandLineOverrides)
    {
        Call("ApplyResolutionSettings", Bytes<byte>(bCheckForCommandLineOverrides ? (byte)1 : (byte)0));
    }

    public void ApplyNonResolutionSettings()
    {
        Call("ApplyNonResolutionSettings");
    }

    public void ApplyHardwareBenchmarkResults()
    {
        Call("ApplyHardwareBenchmarkResults");
    }
}
