// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class InputBlendPose : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.Engine.BranchFilter> BranchFilters =>
        new UnrealArray<Palforge.Sdk.Script.Engine.BranchFilter>(this, 0x0, 0xC, "BranchFilters", static (context, element) => new Palforge.Sdk.Script.Engine.BranchFilter(element, context), static (context, value) => context.BytesAt(value.Address, 0xC), null);

    internal InputBlendPose(nint address, UnrealContext context) : base(address, context, "InputBlendPose")
    {
    }

    private protected InputBlendPose(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static InputBlendPose? Allocate()
    {
        return SdkEnv.AllocateStruct<InputBlendPose>("InputBlendPose");
    }
}
