// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class InputTouchDelegateBinding : Palforge.Sdk.Script.Engine.InputDelegateBinding
{
    public UnrealArray<Palforge.Sdk.Script.Engine.BlueprintInputTouchDelegateBinding> InputTouchDelegateBindings =>
        new UnrealArray<Palforge.Sdk.Script.Engine.BlueprintInputTouchDelegateBinding>(this, 0x28, 0x10, "InputTouchDelegateBindings", static (context, element) => new Palforge.Sdk.Script.Engine.BlueprintInputTouchDelegateBinding(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    internal InputTouchDelegateBinding(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("InputTouchDelegateBinding");
    }

    public static new InputTouchDelegateBinding? New(UObject? outer = null)
    {
        return SdkEnv.New("InputTouchDelegateBinding", outer) as InputTouchDelegateBinding;
    }

    public static new InputTouchDelegateBinding? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as InputTouchDelegateBinding;
    }
}
