// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionChannelMaskParameter : Palforge.Sdk.Script.Engine.MaterialExpressionVectorParameter
{
    public byte MaskChannel
    {
        get => ReadAt<byte>(0x150);
        set => WriteAt(0x150, value);
    }

    public Palforge.Sdk.Script.Engine.ExpressionInput Input =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0x158, Context);

    internal MaterialExpressionChannelMaskParameter(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionChannelMaskParameter");
    }

    public static new MaterialExpressionChannelMaskParameter? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionChannelMaskParameter", outer) as MaterialExpressionChannelMaskParameter;
    }

    public static new MaterialExpressionChannelMaskParameter? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionChannelMaskParameter;
    }
}
