// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionActorPositionWS : Palforge.Sdk.Script.Engine.MaterialExpression
{
    internal MaterialExpressionActorPositionWS(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionActorPositionWS");
    }

    public static new MaterialExpressionActorPositionWS? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionActorPositionWS", outer) as MaterialExpressionActorPositionWS;
    }

    public static new MaterialExpressionActorPositionWS? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionActorPositionWS;
    }
}
