// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionBreakMaterialAttributes : Palforge.Sdk.Script.Engine.MaterialExpression
{
    public Palforge.Sdk.Script.Engine.MaterialAttributesInput MaterialAttributes =>
        new Palforge.Sdk.Script.Engine.MaterialAttributesInput(Address + 0xB0, Context);

    internal MaterialExpressionBreakMaterialAttributes(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionBreakMaterialAttributes");
    }

    public static new MaterialExpressionBreakMaterialAttributes? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionBreakMaterialAttributes", outer) as MaterialExpressionBreakMaterialAttributes;
    }

    public static new MaterialExpressionBreakMaterialAttributes? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionBreakMaterialAttributes;
    }
}
