// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionSingleLayerWaterMaterialOutput : Palforge.Sdk.Script.Engine.MaterialExpressionCustomOutput
{
    public Palforge.Sdk.Script.Engine.ExpressionInput ScatteringCoefficients =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput AbsorptionCoefficients =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xD8, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput PhaseG =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0x100, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput ColorScaleBehindWater =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0x128, Context);

    internal MaterialExpressionSingleLayerWaterMaterialOutput(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionSingleLayerWaterMaterialOutput");
    }

    public static new MaterialExpressionSingleLayerWaterMaterialOutput? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionSingleLayerWaterMaterialOutput", outer) as MaterialExpressionSingleLayerWaterMaterialOutput;
    }

    public static new MaterialExpressionSingleLayerWaterMaterialOutput? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionSingleLayerWaterMaterialOutput;
    }
}
