// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionParticleSubUV : Palforge.Sdk.Script.Engine.MaterialExpressionTextureSample
{
    public bool BBlend
    {
        get => ReadBoolAt(0x1B8, 0x1);
        set => WriteBoolAt(0x1B8, 0x1, value);
    }

    internal MaterialExpressionParticleSubUV(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionParticleSubUV");
    }

    public static new MaterialExpressionParticleSubUV? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionParticleSubUV", outer) as MaterialExpressionParticleSubUV;
    }

    public static new MaterialExpressionParticleSubUV? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionParticleSubUV;
    }
}
