// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionClearCoatNormalCustomOutput : Palforge.Sdk.Script.Engine.MaterialExpressionCustomOutput
{
    public Palforge.Sdk.Script.Engine.ExpressionInput Input =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    internal MaterialExpressionClearCoatNormalCustomOutput(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionClearCoatNormalCustomOutput");
    }

    public static new MaterialExpressionClearCoatNormalCustomOutput? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionClearCoatNormalCustomOutput", outer) as MaterialExpressionClearCoatNormalCustomOutput;
    }

    public static new MaterialExpressionClearCoatNormalCustomOutput? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionClearCoatNormalCustomOutput;
    }
}
