// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionStrataVolumetricFogCloudBSDF : Palforge.Sdk.Script.Engine.MaterialExpressionStrataBSDF
{
    public Palforge.Sdk.Script.Engine.ExpressionInput Albedo =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput Extinction =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xD8, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput EmissiveColor =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0x100, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput AmbientOcclusion =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0x128, Context);

    internal MaterialExpressionStrataVolumetricFogCloudBSDF(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionStrataVolumetricFogCloudBSDF");
    }

    public static new MaterialExpressionStrataVolumetricFogCloudBSDF? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionStrataVolumetricFogCloudBSDF", outer) as MaterialExpressionStrataVolumetricFogCloudBSDF;
    }

    public static new MaterialExpressionStrataVolumetricFogCloudBSDF? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionStrataVolumetricFogCloudBSDF;
    }
}
