// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionLogarithm2 : Palforge.Sdk.Script.Engine.MaterialExpression
{
    public Palforge.Sdk.Script.Engine.ExpressionInput X =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    internal MaterialExpressionLogarithm2(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionLogarithm2");
    }

    public static new MaterialExpressionLogarithm2? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionLogarithm2", outer) as MaterialExpressionLogarithm2;
    }

    public static new MaterialExpressionLogarithm2? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionLogarithm2;
    }
}
