// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionSceneTexture : Palforge.Sdk.Script.Engine.MaterialExpression
{
    public Palforge.Sdk.Script.Engine.ExpressionInput Coordinates =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    public byte SceneTextureId
    {
        get => ReadAt<byte>(0xD8);
        set => WriteAt(0xD8, value);
    }

    public bool BFiltered
    {
        get => ReadBoolAt(0xD9, 0xFF);
        set => WriteBoolAt(0xD9, 0xFF, value);
    }

    internal MaterialExpressionSceneTexture(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionSceneTexture");
    }

    public static new MaterialExpressionSceneTexture? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionSceneTexture", outer) as MaterialExpressionSceneTexture;
    }

    public static new MaterialExpressionSceneTexture? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionSceneTexture;
    }
}
