// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionDistanceFieldsRenderingSwitch : Palforge.Sdk.Script.Engine.MaterialExpression
{
    public Palforge.Sdk.Script.Engine.ExpressionInput No =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB0, Context);

    public Palforge.Sdk.Script.Engine.ExpressionInput Yes =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xD8, Context);

    internal MaterialExpressionDistanceFieldsRenderingSwitch(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionDistanceFieldsRenderingSwitch");
    }

    public static new MaterialExpressionDistanceFieldsRenderingSwitch? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionDistanceFieldsRenderingSwitch", outer) as MaterialExpressionDistanceFieldsRenderingSwitch;
    }

    public static new MaterialExpressionDistanceFieldsRenderingSwitch? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionDistanceFieldsRenderingSwitch;
    }
}
