// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionPixelNormalWS : Palforge.Sdk.Script.Engine.MaterialExpression
{
    internal MaterialExpressionPixelNormalWS(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionPixelNormalWS");
    }

    public static new MaterialExpressionPixelNormalWS? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionPixelNormalWS", outer) as MaterialExpressionPixelNormalWS;
    }

    public static new MaterialExpressionPixelNormalWS? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionPixelNormalWS;
    }
}
