// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class MaterialExpressionSkyAtmosphereLightIlluminance : Palforge.Sdk.Script.Engine.MaterialExpression
{
    public int LightIndex
    {
        get => ReadAt<int>(0xB0);
        set => WriteAt(0xB0, value);
    }

    public Palforge.Sdk.Script.Engine.ExpressionInput WorldPosition =>
        new Palforge.Sdk.Script.Engine.ExpressionInput(Address + 0xB8, Context);

    internal MaterialExpressionSkyAtmosphereLightIlluminance(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MaterialExpressionSkyAtmosphereLightIlluminance");
    }

    public static new MaterialExpressionSkyAtmosphereLightIlluminance? New(UObject? outer = null)
    {
        return SdkEnv.New("MaterialExpressionSkyAtmosphereLightIlluminance", outer) as MaterialExpressionSkyAtmosphereLightIlluminance;
    }

    public static new MaterialExpressionSkyAtmosphereLightIlluminance? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MaterialExpressionSkyAtmosphereLightIlluminance;
    }
}
