// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class NameCurveKey : UStructValue
{
    public float Time
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public string Value
    {
        get => ReadNameAt(0x4);
        set => WriteNameAt(0x4, value);
    }

    internal NameCurveKey(nint address, UnrealContext context) : base(address, context, "NameCurveKey")
    {
    }

    private protected NameCurveKey(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NameCurveKey? Allocate()
    {
        return SdkEnv.AllocateStruct<NameCurveKey>("NameCurveKey");
    }
}
