// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class NavigationSystemConfig : UObject
{
    public Palforge.Sdk.Script.CoreUObject.SoftClassPath NavigationSystemClass =>
        new Palforge.Sdk.Script.CoreUObject.SoftClassPath(Address + 0x28, Context);

    public Palforge.Sdk.Script.Engine.NavAgentSelector SupportedAgentsMask =>
        new Palforge.Sdk.Script.Engine.NavAgentSelector(Address + 0x48, Context);

    public string DefaultAgentName
    {
        get => ReadNameAt(0x4C);
        set => WriteNameAt(0x4C, value);
    }

    public bool BIsOverriden
    {
        get => ReadBoolAt(0x54, 0x1);
        set => WriteBoolAt(0x54, 0x1, value);
    }

    internal NavigationSystemConfig(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NavigationSystemConfig");
    }

    public static NavigationSystemConfig? New(UObject? outer = null)
    {
        return SdkEnv.New("NavigationSystemConfig", outer) as NavigationSystemConfig;
    }

    public static NavigationSystemConfig? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NavigationSystemConfig;
    }
}
