// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class NavPathObserverInterface : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal NavPathObserverInterface(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NavPathObserverInterface");
    }

    public static new NavPathObserverInterface? New(UObject? outer = null)
    {
        return SdkEnv.New("NavPathObserverInterface", outer) as NavPathObserverInterface;
    }

    public static new NavPathObserverInterface? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NavPathObserverInterface;
    }
}
