// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ParticleModuleLightSeeded : Palforge.Sdk.Script.Engine.ParticleModuleLight
{
    public Palforge.Sdk.Script.Engine.ParticleRandomSeedInfo RandomSeedInfo =>
        new Palforge.Sdk.Script.Engine.ParticleRandomSeedInfo(Address + 0x140, Context);

    internal ParticleModuleLightSeeded(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ParticleModuleLight_Seeded");
    }

    public static new ParticleModuleLightSeeded? New(UObject? outer = null)
    {
        return SdkEnv.New("ParticleModuleLight_Seeded", outer) as ParticleModuleLightSeeded;
    }

    public static new ParticleModuleLightSeeded? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ParticleModuleLightSeeded;
    }
}
