// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ParticleModuleVectorFieldBase : Palforge.Sdk.Script.Engine.ParticleModule
{
    internal ParticleModuleVectorFieldBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ParticleModuleVectorFieldBase");
    }

    public static new ParticleModuleVectorFieldBase? New(UObject? outer = null)
    {
        return SdkEnv.New("ParticleModuleVectorFieldBase", outer) as ParticleModuleVectorFieldBase;
    }

    public static new ParticleModuleVectorFieldBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ParticleModuleVectorFieldBase;
    }
}
