// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ParticleSystemReplay : UObject
{
    public int ClipIDNumber
    {
        get => ReadAt<int>(0x28);
        set => WriteAt(0x28, value);
    }

    internal ParticleSystemReplay(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ParticleSystemReplay");
    }

    public static ParticleSystemReplay? New(UObject? outer = null)
    {
        return SdkEnv.New("ParticleSystemReplay", outer) as ParticleSystemReplay;
    }

    public static ParticleSystemReplay? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ParticleSystemReplay;
    }
}
