// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ParticleModuleEventSendToGame : UObject
{
    internal ParticleModuleEventSendToGame(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ParticleModuleEventSendToGame");
    }

    public static ParticleModuleEventSendToGame? New(UObject? outer = null)
    {
        return SdkEnv.New("ParticleModuleEventSendToGame", outer) as ParticleModuleEventSendToGame;
    }

    public static ParticleModuleEventSendToGame? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ParticleModuleEventSendToGame;
    }
}
