// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class ResponseChannel : UStructValue
{
    public string Channel
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public byte Response
    {
        get => ReadAt<byte>(0x8);
        set => WriteAt(0x8, value);
    }

    internal ResponseChannel(nint address, UnrealContext context) : base(address, context, "ResponseChannel")
    {
    }

    private protected ResponseChannel(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ResponseChannel? Allocate()
    {
        return SdkEnv.AllocateStruct<ResponseChannel>("ResponseChannel");
    }
}
