// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class RuntimeVirtualTextureComponent : Palforge.Sdk.Script.Engine.SceneComponent
{
    public string BoundsAlignActor
    {
        get => ReadSoftPathAt(0x2A0);
        set => WriteSoftPathAt(0x2A0, value);
    }

    public bool BSetBoundsButton
    {
        get => ReadBoolAt(0x2D0, 0xFF);
        set => WriteBoolAt(0x2D0, 0xFF, value);
    }

    public bool BSnapBoundsToLandscape
    {
        get => ReadBoolAt(0x2D1, 0xFF);
        set => WriteBoolAt(0x2D1, 0xFF, value);
    }

    public Palforge.Sdk.Script.Engine.RuntimeVirtualTexture? VirtualTexture
    {
        get => WrapAt(0x2D8) as Palforge.Sdk.Script.Engine.RuntimeVirtualTexture;
        set => WriteObjectAt(0x2D8, value);
    }

    public bool BEnableScalability
    {
        get => ReadBoolAt(0x2E0, 0xFF);
        set => WriteBoolAt(0x2E0, 0xFF, value);
    }

    public uint ScalabilityGroup
    {
        get => ReadAt<uint>(0x2E4);
        set => WriteAt(0x2E4, value);
    }

    public bool BHidePrimitives
    {
        get => ReadBoolAt(0x2E8, 0xFF);
        set => WriteBoolAt(0x2E8, 0xFF, value);
    }

    public Palforge.Sdk.Script.Engine.VirtualTextureBuilder? StreamingTexture
    {
        get => WrapAt(0x2F0) as Palforge.Sdk.Script.Engine.VirtualTextureBuilder;
        set => WriteObjectAt(0x2F0, value);
    }

    public int StreamLowMips
    {
        get => ReadAt<int>(0x2F8);
        set => WriteAt(0x2F8, value);
    }

    public bool BBuildStreamingMipsButton
    {
        get => ReadBoolAt(0x2FC, 0xFF);
        set => WriteBoolAt(0x2FC, 0xFF, value);
    }

    public byte LossyCompressionAmount
    {
        get => ReadAt<byte>(0x2FD);
        set => WriteAt(0x2FD, value);
    }

    public bool BUseStreamingLowMipsInEditor
    {
        get => ReadBoolAt(0x2FE, 0xFF);
        set => WriteBoolAt(0x2FE, 0xFF, value);
    }

    public bool BBuildDebugStreamingMips
    {
        get => ReadBoolAt(0x2FF, 0xFF);
        set => WriteBoolAt(0x2FF, 0xFF, value);
    }

    internal RuntimeVirtualTextureComponent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("RuntimeVirtualTextureComponent");
    }

    public static new RuntimeVirtualTextureComponent? New(UObject? outer = null)
    {
        return SdkEnv.New("RuntimeVirtualTextureComponent", outer) as RuntimeVirtualTextureComponent;
    }

    public static new RuntimeVirtualTextureComponent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as RuntimeVirtualTextureComponent;
    }

    public void Invalidate(Palforge.Sdk.Script.CoreUObject.BoxSphereBounds worldBounds)
    {
        Call("Invalidate", SdkEnv.StructBytes(worldBounds, 56));
    }
}
