// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class SkeletalMeshSimplificationSettings : Palforge.Sdk.Script.DeveloperSettings.DeveloperSettings
{
    public string SkeletalMeshReductionModuleName
    {
        get => ReadNameAt(0x38);
        set => WriteNameAt(0x38, value);
    }

    internal SkeletalMeshSimplificationSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SkeletalMeshSimplificationSettings");
    }

    public static new SkeletalMeshSimplificationSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("SkeletalMeshSimplificationSettings", outer) as SkeletalMeshSimplificationSettings;
    }

    public static new SkeletalMeshSimplificationSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SkeletalMeshSimplificationSettings;
    }
}
