// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Engine;

public enum SkeletalMeshOptimizationImportance
{
    SmoiOff = 0,
    SmoiLowest = 1,
    SmoiLow = 2,
    SmoiNormal = 3,
    SmoiHigh = 4,
    SmoiHighest = 5,
    SmoiMax = 6
}
