// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class SmartNameMapping : UStructValue
{
    internal SmartNameMapping(nint address, UnrealContext context) : base(address, context, "SmartNameMapping")
    {
    }

    private protected SmartNameMapping(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static SmartNameMapping? Allocate()
    {
        return SdkEnv.AllocateStruct<SmartNameMapping>("SmartNameMapping");
    }
}
