// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class SmokeTestCommandlet : Palforge.Sdk.Script.Engine.Commandlet
{
    internal SmokeTestCommandlet(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SmokeTestCommandlet");
    }

    public static new SmokeTestCommandlet? New(UObject? outer = null)
    {
        return SdkEnv.New("SmokeTestCommandlet", outer) as SmokeTestCommandlet;
    }

    public static new SmokeTestCommandlet? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SmokeTestCommandlet;
    }
}
