// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class SoundModulationDefaultSettings : UStructValue
{
    public Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings VolumeModulationDestination =>
        new Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings(Address + 0x0, Context);

    public Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings PitchModulationDestination =>
        new Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings(Address + 0x60, Context);

    public Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings HighpassModulationDestination =>
        new Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings(Address + 0xC0, Context);

    public Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings LowpassModulationDestination =>
        new Palforge.Sdk.Script.Engine.SoundModulationDestinationSettings(Address + 0x120, Context);

    internal SoundModulationDefaultSettings(nint address, UnrealContext context) : base(address, context, "SoundModulationDefaultSettings")
    {
    }

    private protected SoundModulationDefaultSettings(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static SoundModulationDefaultSettings? Allocate()
    {
        return SdkEnv.AllocateStruct<SoundModulationDefaultSettings>("SoundModulationDefaultSettings");
    }
}
