// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class TextureRenderTarget2D : Palforge.Sdk.Script.Engine.TextureRenderTarget
{
    public int SizeX
    {
        get => ReadAt<int>(0x1F8);
        set => WriteAt(0x1F8, value);
    }

    public int SizeY
    {
        get => ReadAt<int>(0x1FC);
        set => WriteAt(0x1FC, value);
    }

    public Palforge.Sdk.Script.CoreUObject.LinearColor ClearColor =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x200, Context);

    public byte AddressX
    {
        get => ReadAt<byte>(0x210);
        set => WriteAt(0x210, value);
    }

    public byte AddressY
    {
        get => ReadAt<byte>(0x211);
        set => WriteAt(0x211, value);
    }

    public bool BForceLinearGamma
    {
        get => ReadBoolAt(0x212, 0x1);
        set => WriteBoolAt(0x212, 0x1, value);
    }

    public bool BHDR
    {
        get => ReadBoolAt(0x212, 0x2);
        set => WriteBoolAt(0x212, 0x2, value);
    }

    public bool BGPUSharedFlag
    {
        get => ReadBoolAt(0x212, 0x4);
        set => WriteBoolAt(0x212, 0x4, value);
    }

    public byte RenderTargetFormat
    {
        get => ReadAt<byte>(0x213);
        set => WriteAt(0x213, value);
    }

    public bool BAutoGenerateMips
    {
        get => ReadBoolAt(0x214, 0x1);
        set => WriteBoolAt(0x214, 0x1, value);
    }

    public byte MipsSamplerFilter
    {
        get => ReadAt<byte>(0x215);
        set => WriteAt(0x215, value);
    }

    public byte MipsAddressU
    {
        get => ReadAt<byte>(0x216);
        set => WriteAt(0x216, value);
    }

    public byte MipsAddressV
    {
        get => ReadAt<byte>(0x217);
        set => WriteAt(0x217, value);
    }

    public byte OverrideFormat
    {
        get => ReadAt<byte>(0x218);
        set => WriteAt(0x218, value);
    }

    internal TextureRenderTarget2D(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("TextureRenderTarget2D");
    }

    public static new TextureRenderTarget2D? New(UObject? outer = null)
    {
        return SdkEnv.New("TextureRenderTarget2D", outer) as TextureRenderTarget2D;
    }

    public static new TextureRenderTarget2D? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as TextureRenderTarget2D;
    }
}
