// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class TouchInterface : UObject
{
    public UnrealArray<Palforge.Sdk.Script.Engine.TouchInputControl> Controls =>
        new UnrealArray<Palforge.Sdk.Script.Engine.TouchInputControl>(this, 0x28, 0x90, "Controls", static (context, element) => new Palforge.Sdk.Script.Engine.TouchInputControl(element, context), static (context, value) => context.BytesAt(value.Address, 0x90), null);

    public float ActiveOpacity
    {
        get => ReadAt<float>(0x38);
        set => WriteAt(0x38, value);
    }

    public float InactiveOpacity
    {
        get => ReadAt<float>(0x3C);
        set => WriteAt(0x3C, value);
    }

    public float TimeUntilDeactive
    {
        get => ReadAt<float>(0x40);
        set => WriteAt(0x40, value);
    }

    public float TimeUntilReset
    {
        get => ReadAt<float>(0x44);
        set => WriteAt(0x44, value);
    }

    public float ActivationDelay
    {
        get => ReadAt<float>(0x48);
        set => WriteAt(0x48, value);
    }

    public bool BPreventRecenter
    {
        get => ReadBoolAt(0x4C, 0xFF);
        set => WriteBoolAt(0x4C, 0xFF, value);
    }

    public float StartupDelay
    {
        get => ReadAt<float>(0x50);
        set => WriteAt(0x50, value);
    }

    internal TouchInterface(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("TouchInterface");
    }

    public static TouchInterface? New(UObject? outer = null)
    {
        return SdkEnv.New("TouchInterface", outer) as TouchInterface;
    }

    public static TouchInterface? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as TouchInterface;
    }
}
