// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class TypedElementCommonActions : UObject
{
    internal TypedElementCommonActions(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("TypedElementCommonActions");
    }

    public static TypedElementCommonActions? New(UObject? outer = null)
    {
        return SdkEnv.New("TypedElementCommonActions", outer) as TypedElementCommonActions;
    }

    public static TypedElementCommonActions? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as TypedElementCommonActions;
    }

    public bool DeleteSelectedElements(Palforge.Sdk.Script.TypedElementRuntime.TypedElementSelectionSet? selectionSet, Palforge.Sdk.Script.Engine.World? world, Palforge.Sdk.Script.Engine.TypedElementDeletionOptions deletionOptions)
    {
        return As<byte>(Call("DeleteSelectedElements", Bytes<nint>(selectionSet?.Address ?? 0), Bytes<nint>(world?.Address ?? 0), SdkEnv.StructBytes(deletionOptions, 3))) is not 0;
    }

    public bool DeleteNormalizedElements(Palforge.Sdk.Script.TypedElementFramework.ScriptTypedElementListProxy elementList, Palforge.Sdk.Script.Engine.World? world, Palforge.Sdk.Script.TypedElementRuntime.TypedElementSelectionSet? inSelectionSet, Palforge.Sdk.Script.Engine.TypedElementDeletionOptions deletionOptions)
    {
        return As<byte>(Call("DeleteNormalizedElements", SdkEnv.StructBytes(elementList, 16), Bytes<nint>(world?.Address ?? 0), Bytes<nint>(inSelectionSet?.Address ?? 0), SdkEnv.StructBytes(deletionOptions, 3))) is not 0;
    }
}
