// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Engine;

public class WorldPartitionRuntimeCellDebugInfo : UStructValue
{
    public string Name
    {
        get => ReadStringAt(0x0);
        set => WriteStringAt(0x0, value);
    }

    public string GridName
    {
        get => ReadNameAt(0x10);
        set => WriteNameAt(0x10, value);
    }

    public long CoordX
    {
        get => ReadAt<long>(0x18);
        set => WriteAt(0x18, value);
    }

    public long CoordY
    {
        get => ReadAt<long>(0x20);
        set => WriteAt(0x20, value);
    }

    public long CoordZ
    {
        get => ReadAt<long>(0x28);
        set => WriteAt(0x28, value);
    }

    internal WorldPartitionRuntimeCellDebugInfo(nint address, UnrealContext context) : base(address, context, "WorldPartitionRuntimeCellDebugInfo")
    {
    }

    private protected WorldPartitionRuntimeCellDebugInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static WorldPartitionRuntimeCellDebugInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<WorldPartitionRuntimeCellDebugInfo>("WorldPartitionRuntimeCellDebugInfo");
    }
}
