// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.NavigationSystem;

public class NavGraphNode : UStructValue
{
    public UObject? Owner
    {
        get => WrapAt(0x0);
        set => WriteObjectAt(0x0, value);
    }

    internal NavGraphNode(nint address, UnrealContext context) : base(address, context, "NavGraphNode")
    {
    }

    private protected NavGraphNode(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NavGraphNode? Allocate()
    {
        return SdkEnv.AllocateStruct<NavGraphNode>("NavGraphNode");
    }
}
