// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.NavigationSystem;

public class NavigationData : Palforge.Sdk.Script.Engine.Actor
{
    public Palforge.Sdk.Script.Engine.PrimitiveComponent? RenderingComp
    {
        get => WrapAt(0x298) as Palforge.Sdk.Script.Engine.PrimitiveComponent;
        set => WriteObjectAt(0x298, value);
    }

    public Palforge.Sdk.Script.Engine.NavDataConfig NavDataConfig =>
        new Palforge.Sdk.Script.Engine.NavDataConfig(Address + 0x2A0, Context);

    public bool BEnableDrawing
    {
        get => ReadBoolAt(0x338, 0x1);
        set => WriteBoolAt(0x338, 0x1, value);
    }

    public bool BForceRebuildOnLoad
    {
        get => ReadBoolAt(0x338, 0x2);
        set => WriteBoolAt(0x338, 0x2, value);
    }

    public bool BAutoDestroyWhenNoNavigation
    {
        get => ReadBoolAt(0x338, 0x4);
        set => WriteBoolAt(0x338, 0x4, value);
    }

    public bool BCanBeMainNavData
    {
        get => ReadBoolAt(0x338, 0x8);
        set => WriteBoolAt(0x338, 0x8, value);
    }

    public bool BCanSpawnOnRebuild
    {
        get => ReadBoolAt(0x338, 0x10);
        set => WriteBoolAt(0x338, 0x10, value);
    }

    public bool BRebuildAtRuntime
    {
        get => ReadBoolAt(0x338, 0x20);
        set => WriteBoolAt(0x338, 0x20, value);
    }

    public Palforge.Sdk.Script.NavigationSystem.ERuntimeGenerationType RuntimeGeneration
    {
        get => (Palforge.Sdk.Script.NavigationSystem.ERuntimeGenerationType)ReadAt<byte>(0x33C);
        set => WriteAt(0x33C, (byte)value);
    }

    public float ObservedPathsTickInterval
    {
        get => ReadAt<float>(0x340);
        set => WriteAt(0x340, value);
    }

    public uint DataVersion
    {
        get => ReadAt<uint>(0x344);
        set => WriteAt(0x344, value);
    }

    public UnrealArray<Palforge.Sdk.Script.NavigationSystem.SupportedAreaData> SupportedAreas =>
        new UnrealArray<Palforge.Sdk.Script.NavigationSystem.SupportedAreaData>(this, 0x450, 0x20, "SupportedAreas", static (context, element) => new Palforge.Sdk.Script.NavigationSystem.SupportedAreaData(element, context), static (context, value) => context.BytesAt(value.Address, 0x20), null);

    internal NavigationData(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NavigationData");
    }

    public static new NavigationData? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("NavigationData", owner, at) as NavigationData;
    }

    public static new NavigationData? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NavigationData;
    }
}
