// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Slate;

public enum EScrollWhenFocusChanges
{
    NoScroll = 0,
    InstantScroll = 1,
    AnimatedScroll = 2,
    EScrollWhenFocusChangesMax = 3
}
