// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Slate;

public class SpinBoxWidgetStyle : Palforge.Sdk.Script.SlateCore.SlateWidgetStyleContainerBase
{
    public Palforge.Sdk.Script.SlateCore.SpinBoxStyle SpinBoxStyle =>
        new Palforge.Sdk.Script.SlateCore.SpinBoxStyle(Address + 0x30, Context);

    internal SpinBoxWidgetStyle(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SpinBoxWidgetStyle");
    }

    public static new SpinBoxWidgetStyle? New(UObject? outer = null)
    {
        return SdkEnv.New("SpinBoxWidgetStyle", outer) as SpinBoxWidgetStyle;
    }

    public static new SpinBoxWidgetStyle? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SpinBoxWidgetStyle;
    }
}
