// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Slate;

public class VirtualKeyboardOptions : UStructValue
{
    public bool BEnableAutocorrect
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    internal VirtualKeyboardOptions(nint address, UnrealContext context) : base(address, context, "VirtualKeyboardOptions")
    {
    }

    private protected VirtualKeyboardOptions(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static VirtualKeyboardOptions? Allocate()
    {
        return SdkEnv.AllocateStruct<VirtualKeyboardOptions>("VirtualKeyboardOptions");
    }
}
