// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalPassiveTriggerType
{
    None = 0,
    ActiveOtomo = 1,
    Worker = 2,
    Ride = 4,
    Reserve = 8,
    InOtomo = 16,
    InBaseCamp = 32,
    Always = 64,
    EPalPassiveTriggerTypeMax = 65
}
