// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalDimensionStorageReplicationTriggerType
{
    Common = 0,
    Sort = 1,
    EPalDimensionStorageReplicationTriggerTypeMax = 2
}
