// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalStageRequestResult
{
    None = 0,
    Success = 1,
    FailedNotValidStage = 2,
    FailedNotValidPlayerUId = 3,
    FailedNotValidPlayerState = 4,
    FailedNotValidPlayerController = 5,
    FailedNotValidPlayerCharacter = 6,
    FailedNotValidLoginPlayer = 7,
    FailedNotValidNetworkPlayerComponent = 8,
    FailedPlayerIsDead = 9,
    FailedNotValidStageWorldSubsystem = 10,
    FailedGetStartPointTransform = 11,
    FailedGetReturnToFieldPointTransform = 12,
    FailedNotValidExitParameter = 13,
    FailedNotAllowed = 14,
    FailedConcurrentStageLimitation = 15,
    FailedCannotExitStageOnRespawn = 16,
    FailedPlayerNotInStage = 17,
    EPalStageRequestResultMax = 18
}
