// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalPassiveSkillEffectTargetType
{
    None = 0,
    ToSelf = 1,
    ToTrainer = 2,
    ToSelfAndTrainer = 3,
    ToBaseCampPal = 4,
    ToBuildObject = 5,
    ToOtomo = 6,
    ToTrainerAndOtomo = 7,
    ToActiveOtomo = 8,
    EPalPassiveSkillEffectTargetTypeMax = 9
}
