// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalBattleBGMType
{
    None = 0,
    Cute = 1,
    Cool = 2,
    Strong = 3,
    HumanCommon = 4,
    HumanVillain = 5,
    FieldBossTier = 6,
    FieldBossTier2 = 7,
    FieldBossTier3 = 8,
    FieldBossTier4 = 9,
    FieldBossTier5 = 10,
    Predator = 11,
    EyeofCthulhu = 12,
    WildlifeSanctuaryDrone = 13,
    Machine = 14,
    Legend = 15,
    KingWhale = 16,
    RaidBoss = 17,
    TowerBoss = 18,
    RaidBossKingBahamut = 19,
    RaidBossDarkMechaDragon = 20,
    RaidBossMoonLord = 21,
    RaidBossLegendDeer = 22,
    RaidBossLegendDeer2 = 23,
    WorldTreeDragon = 24,
    EPalBattleBGMTypeMax = 25
}
