// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalBossBattleState
{
    Open = 0,
    PreBattle = 1,
    InBattle = 2,
    AfterBattle = 3,
    EPalBossBattleStateMax = 4
}
