// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalUIPalCharacterRankUpRequestResult
{
    Success = 0,
    FailedNotValidMapObject = 1,
    FailedNotSetTarget = 2,
    FailedCannotRankUp = 3,
    FailedNotEnoughResources = 4,
    EPalUIPalCharacterRankUpRequestResultMax = 5
}
