// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Pal;

public enum EPalBossBattleHardUnlockCondition
{
    DefeatHardUnlockTiggerBoss = 0,
    DefeatSameBossNormal = 1,
    EPalBossBattleHardUnlockConditionMax = 2
}
