// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class FastPalBaseCampRepInfoArray : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.Pal.PalBaseCampRepInfo> Items =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalBaseCampRepInfo>(this, 0x108, 0x28, "Items", static (context, element) => new Palforge.Sdk.Script.Pal.PalBaseCampRepInfo(element, context), static (context, value) => context.BytesAt(value.Address, 0x28), null);

    public int ArrayReplicationKey
    {
        get => ReadAt<int>(0x54);
        set => WriteAt(0x54, value);
    }

    public Palforge.Sdk.Script.NetCore.EFastArraySerializerDeltaFlags DeltaFlags
    {
        get => (Palforge.Sdk.Script.NetCore.EFastArraySerializerDeltaFlags)ReadAt<byte>(0x100);
        set => WriteAt(0x100, (byte)value);
    }

    internal FastPalBaseCampRepInfoArray(nint address, UnrealContext context) : base(address, context, "FastPalBaseCampRepInfoArray")
    {
    }

    private protected FastPalBaseCampRepInfoArray(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static FastPalBaseCampRepInfoArray? Allocate()
    {
        return SdkEnv.AllocateStruct<FastPalBaseCampRepInfoArray>("FastPalBaseCampRepInfoArray");
    }
}
