// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAILeashActorBase : Palforge.Sdk.Script.Engine.Actor
{
    public float LeashInnerRadius
    {
        get => ReadAt<float>(0x290);
        set => WriteAt(0x290, value);
    }

    public float LeashOuterRadius
    {
        get => ReadAt<float>(0x294);
        set => WriteAt(0x294, value);
    }

    public float InvokerExtentRadius
    {
        get => ReadAt<float>(0x298);
        set => WriteAt(0x298, value);
    }

    public bool BAutoActivateLeash
    {
        get => ReadBoolAt(0x29C, 0xFF);
        set => WriteBoolAt(0x29C, 0xFF, value);
    }

    public Palforge.Sdk.Script.Pal.EPalLeashState LeashState
    {
        get => (Palforge.Sdk.Script.Pal.EPalLeashState)ReadAt<byte>(0x29D);
        set => WriteAt(0x29D, (byte)value);
    }

    public Palforge.Sdk.Script.Pal.PalNavigationInvokerComponent? NavigationInvoker
    {
        get => WrapAt(0x2C0) as Palforge.Sdk.Script.Pal.PalNavigationInvokerComponent;
        set => WriteObjectAt(0x2C0, value);
    }

    internal PalAILeashActorBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAILeashActorBase");
    }

    public static new PalAILeashActorBase? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("PalAILeashActorBase", owner, at) as PalAILeashActorBase;
    }

    public static new PalAILeashActorBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAILeashActorBase;
    }

    public void SetLeashLocation(Palforge.Sdk.Script.CoreUObject.Vector newLeashLocation)
    {
        Call("SetLeashLocation", SdkEnv.StructBytes(newLeashLocation, 24));
    }

    public void OnLeashedPawnStateChangedDelegateSignature(Palforge.Sdk.Script.Pal.PalCharacter? leashedCharacter, Palforge.Sdk.Script.Pal.EPalLeashState previousLeashState, Palforge.Sdk.Script.Pal.EPalLeashState leashState)
    {
        Call("OnLeashedPawnStateChanged__DelegateSignature", Bytes<nint>(leashedCharacter?.Address ?? 0), Bytes((byte)previousLeashState), Bytes((byte)leashState));
    }

    public void OnCharacterOutOfLeashRangeDelegateSignature(Palforge.Sdk.Script.Pal.PalCharacter? leashedCharacter, Palforge.Sdk.Script.CoreUObject.Vector targetLocation, float targetDistance)
    {
        Call("OnCharacterOutOfLeashRange__DelegateSignature", Bytes<nint>(leashedCharacter?.Address ?? 0), SdkEnv.StructBytes(targetLocation, 24), Bytes(targetDistance));
    }

    public bool IsActiveLeash()
    {
        return As<byte>(Call("IsActiveLeash")) is not 0;
    }

    public void DeactivateLeash()
    {
        Call("DeactivateLeash");
    }

    public void ActivateLeash()
    {
        Call("ActivateLeash");
    }
}
