// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAICombatModuleNPCOilrig : Palforge.Sdk.Script.Pal.PalAICombatModuleWild
{
    internal PalAICombatModuleNPCOilrig(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAICombatModule_NPCOilrig");
    }

    public static new PalAICombatModuleNPCOilrig? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAICombatModule_NPCOilrig", outer) as PalAICombatModuleNPCOilrig;
    }

    public static new PalAICombatModuleNPCOilrig? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAICombatModuleNPCOilrig;
    }

    public Palforge.Sdk.Script.Engine.Actor? FindTargetByStack()
    {
        return SdkEnv.Wrap(Call("FindTargetByStack")) as Palforge.Sdk.Script.Engine.Actor;
    }
}
