// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAIActionWorkerWaitForWorkable : Palforge.Sdk.Script.Pal.PalAIActionWorkerChildBase
{
    internal PalAIActionWorkerWaitForWorkable(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAIActionWorkerWaitForWorkable");
    }

    public static new PalAIActionWorkerWaitForWorkable? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAIActionWorkerWaitForWorkable", outer) as PalAIActionWorkerWaitForWorkable;
    }

    public static new PalAIActionWorkerWaitForWorkable? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAIActionWorkerWaitForWorkable;
    }
}
