// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAIActionCoopAssaultrifleMode : Palforge.Sdk.Script.Pal.PalAIActionBase
{
    public float SearchEnemyRadius
    {
        get => ReadAt<float>(0x138);
        set => WriteAt(0x138, value);
    }

    public float SearchLocationRadiusMax
    {
        get => ReadAt<float>(0x13C);
        set => WriteAt(0x13C, value);
    }

    public float SearchLocationRadiusStep
    {
        get => ReadAt<float>(0x140);
        set => WriteAt(0x140, value);
    }

    public float SearchLocationDegStep
    {
        get => ReadAt<float>(0x144);
        set => WriteAt(0x144, value);
    }

    public float SearchingLocationRadius
    {
        get => ReadAt<float>(0x148);
        set => WriteAt(0x148, value);
    }

    public Palforge.Sdk.Script.Pal.PalCharacter? TargetCharacter
    {
        get => WrapAt(0x150) as Palforge.Sdk.Script.Pal.PalCharacter;
        set => WriteObjectAt(0x150, value);
    }

    public Palforge.Sdk.Script.Pal.PalCharacter? ReticleTarget
    {
        get => WrapAt(0x158) as Palforge.Sdk.Script.Pal.PalCharacter;
        set => WriteObjectAt(0x158, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector AimStartPoint =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x160, Context);

    internal PalAIActionCoopAssaultrifleMode(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAIActionCoopAssaultrifleMode");
    }

    public static new PalAIActionCoopAssaultrifleMode? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAIActionCoopAssaultrifleMode", outer) as PalAIActionCoopAssaultrifleMode;
    }

    public static new PalAIActionCoopAssaultrifleMode? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAIActionCoopAssaultrifleMode;
    }

    public void Update(float deltaTime)
    {
        Call("Update", Bytes(deltaTime));
    }

    public void SetAimStartPoint(Palforge.Sdk.Script.CoreUObject.Vector offsetLocation)
    {
        Call("SetAimStartPoint", SdkEnv.StructBytes(offsetLocation, 24));
    }

    public void SearchForTargetAndShootingLocation()
    {
        Call("SearchForTargetAndShootingLocation");
    }

    public void ProgressSeraching(float deltaTime)
    {
        Call("ProgressSeraching", Bytes(deltaTime));
    }

    public void ProgressVerifyShootableEnemy()
    {
        Call("Progress_VerifyShootableEnemy");
    }

    public void ProgressCollectShootableLocation()
    {
        Call("Progress_CollectShootableLocation");
    }

    public void OnUpdateShootingLocation(Palforge.Sdk.Script.Pal.PalCharacter? target, Palforge.Sdk.Script.CoreUObject.Vector shootLocation)
    {
        Call("OnUpdateShootingLocation", Bytes<nint>(target?.Address ?? 0), SdkEnv.StructBytes(shootLocation, 24));
    }

    public void OnRoadBlocked()
    {
        Call("OnRoadBlocked");
    }

    public bool IsSearching()
    {
        return As<byte>(Call("IsSearching")) is not 0;
    }

    public bool HasReached(Palforge.Sdk.Script.CoreUObject.Vector goal)
    {
        return As<byte>(Call("HasReached", SdkEnv.StructBytes(goal, 24))) is not 0;
    }

    public Palforge.Sdk.Script.Pal.PalCharacter? GetTrainer()
    {
        return SdkEnv.Wrap(Call("GetTrainer")) as Palforge.Sdk.Script.Pal.PalCharacter;
    }

    public void GetTargetEnemies(out Palforge.Sdk.Script.Pal.PalCharacter[] enemies)
    {
        var arguments = new byte[][] { new byte[16] };
        Call("GetTargetEnemies", arguments, out var outputs);
        enemies = SdkEnv.Objects<Palforge.Sdk.Script.Pal.PalCharacter>(outputs[0]);
    }

    public Palforge.Sdk.Script.Pal.PalCharacter? GetTargetCharacter()
    {
        return SdkEnv.Wrap(Call("GetTargetCharacter")) as Palforge.Sdk.Script.Pal.PalCharacter;
    }

    public Palforge.Sdk.Script.Pal.PalCharacter? GetReticleTarget()
    {
        return SdkEnv.Wrap(Call("GetReticleTarget")) as Palforge.Sdk.Script.Pal.PalCharacter;
    }

    public bool FindLocationToShootEnemy(Palforge.Sdk.Script.Pal.PalCharacter? target, Palforge.Sdk.Script.Pal.PalCoopSkillAssaultrifleModeCandidateLocation outLocation)
    {
        var arguments = new byte[][] { Bytes<nint>(target?.Address ?? 0), SdkEnv.StructBytes(outLocation, 32) };
        var destinations = new nint[] { 0, outLocation.Address };
        var result = Call("FindLocationToShootEnemy", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public void ClearTargetCharacter()
    {
        Call("ClearTargetCharacter");
    }
}
