// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalArenaWorldSubsystem : Palforge.Sdk.Script.Pal.PalWorldSubsystem
{
    public UnrealArray<Palforge.Sdk.Script.Engine.DataLayerAsset?> DataLayers =>
        new UnrealArray<Palforge.Sdk.Script.Engine.DataLayerAsset?>(this, 0xA8, 0x8, "DataLayers", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.DataLayerAsset, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UObject? ArenaSequencerClass
    {
        get => WrapAt(0xB8);
        set => WriteObjectAt(0xB8, value);
    }

    public UObject? ArenaSpectateSequencerClass
    {
        get => WrapAt(0xC0);
        set => WriteObjectAt(0xC0, value);
    }

    public int InBattleTime
    {
        get => ReadAt<int>(0xC8);
        set => WriteAt(0xC8, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType> DisablePassiveTypes =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType>(this, 0xD0, 0x1, "DisablePassiveTypes", static (context, element) => (Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType)context.ValueAt<byte>(element), static (context, value) => Bytes((byte)value), null);

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType> DisablePassiveTypesToSubPals =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType>(this, 0xE0, 0x1, "DisablePassiveTypesToSubPals", static (context, element) => (Palforge.Sdk.Script.Pal.EPalPassiveSkillEffectType)context.ValueAt<byte>(element), static (context, value) => Bytes((byte)value), null);

    public Palforge.Sdk.Script.Engine.DataTable? SoloNPCPresetTable
    {
        get => WrapAt(0xF0) as Palforge.Sdk.Script.Engine.DataTable;
        set => WriteObjectAt(0xF0, value);
    }

    public Palforge.Sdk.Script.Engine.DataTable? SoloRewadTable
    {
        get => WrapAt(0xF8) as Palforge.Sdk.Script.Engine.DataTable;
        set => WriteObjectAt(0xF8, value);
    }

    public UObject? SoloNPCSpawnerClass
    {
        get => WrapAt(0x100);
        set => WriteObjectAt(0x100, value);
    }

    public UObject? ArenaWorldRankingInfoClass
    {
        get => WrapAt(0x108);
        set => WriteObjectAt(0x108, value);
    }

    public float InitialHateHigh
    {
        get => ReadAt<float>(0x110);
        set => WriteAt(0x110, value);
    }

    public float InitialHateLow
    {
        get => ReadAt<float>(0x114);
        set => WriteAt(0x114, value);
    }

    public Palforge.Sdk.Script.Pal.PalArenaWorldRankingInfo? ArenaWorldRankingInfo
    {
        get => WrapAt(0x118) as Palforge.Sdk.Script.Pal.PalArenaWorldRankingInfo;
        set => WriteObjectAt(0x118, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.PalArenaInstanceModel?> InstanceModels =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalArenaInstanceModel?>(this, 0x120, 0x8, "InstanceModels", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Pal.PalArenaInstanceModel, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public Palforge.Sdk.Script.Pal.PalArenaEntrance? ArenaEntrance
    {
        get => WrapAt(0x130) as Palforge.Sdk.Script.Pal.PalArenaEntrance;
        set => WriteObjectAt(0x130, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Guid GroupGuid =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x138, Context);

    public bool ArenaTopMenuLive
    {
        get => ReadBoolAt(0x148, 0xFF);
        set => WriteBoolAt(0x148, 0xFF, value);
    }

    public Palforge.Sdk.Script.Pal.PalArenaStartReadinessWaiter? ArenaStartReadinessWaiter
    {
        get => WrapAt(0x150) as Palforge.Sdk.Script.Pal.PalArenaStartReadinessWaiter;
        set => WriteObjectAt(0x150, value);
    }

    internal PalArenaWorldSubsystem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalArenaWorldSubsystem");
    }

    public static new PalArenaWorldSubsystem? New(UObject? outer = null)
    {
        return SdkEnv.New("PalArenaWorldSubsystem", outer) as PalArenaWorldSubsystem;
    }

    public static new PalArenaWorldSubsystem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalArenaWorldSubsystem;
    }

    public void ShowOverLimitWarning()
    {
        Call("ShowOverLimitWarning");
    }

    public void SetArenaTopMenuLive(bool isLive)
    {
        Call("SetArenaTopMenuLive", Bytes<byte>(isLive ? (byte)1 : (byte)0));
    }

    public void RequestExitSpectate()
    {
        Call("RequestExitSpectate");
    }

    public void RequestEnterArenaSolo(Palforge.Sdk.Script.Pal.EPalArenaRank rank)
    {
        Call("RequestEnterArenaSolo", Bytes((byte)rank));
    }

    public void RequestEnterArena(Palforge.Sdk.Script.CoreUObject.Guid arenaRoomId)
    {
        Call("RequestEnterArena", SdkEnv.StructBytes(arenaRoomId, 16));
    }

    public void RequestCreateArenaRoom(Palforge.Sdk.Script.Pal.PalArenaRule arenaRule)
    {
        Call("RequestCreateArenaRoom", SdkEnv.StructBytes(arenaRule, 56));
    }

    public void RequestCancelEntryArena(Palforge.Sdk.Script.Pal.PalPlayerCharacter? cancelPlayer)
    {
        Call("RequestCancelEntryArena", Bytes<nint>(cancelPlayer?.Address ?? 0));
    }

    public void PalOnLocalPlayerRankingInfoNotifiedDelegateSignature(Palforge.Sdk.Script.Pal.PalArenaWorldRankingRecord rankingInfo)
    {
        Call("PalOnLocalPlayerRankingInfoNotified__DelegateSignature", SdkEnv.StructBytes(rankingInfo, 136));
    }

    public void OnUIRequestRepliedDelegateDelegateSignature(Palforge.Sdk.Script.Pal.EPalArenaMenuActionType actionType)
    {
        Call("OnUIRequestRepliedDelegate__DelegateSignature", Bytes((byte)actionType));
    }

    public void OnSoloNPCSpawned(Palforge.Sdk.Script.Pal.PalArenaSoloNPCSpawner? spawner)
    {
        Call("OnSoloNPCSpawned", Bytes<nint>(spawner?.Address ?? 0));
    }

    public void OnChangeBattleEndTimeServerInternal(Palforge.Sdk.Script.CoreUObject.DateTime battleEndTime)
    {
        Call("OnChangeBattleEndTime_ServerInternal", SdkEnv.StructBytes(battleEndTime, 8));
    }

    public void OnArenaTopMenuCloseDelegateDelegateSignature()
    {
        Call("OnArenaTopMenuCloseDelegate__DelegateSignature");
    }

    public void OnArenaStartReady(Palforge.Sdk.Script.Pal.PalArenaSequencerInitializeParameter initParam)
    {
        Call("OnArenaStartReady", SdkEnv.StructBytes(initParam, 40));
    }

    public Palforge.Sdk.Script.Pal.PalArenaSequencer? GetLocalPlayerSequencer()
    {
        return SdkEnv.Wrap(Call("GetLocalPlayerSequencer")) as Palforge.Sdk.Script.Pal.PalArenaSequencer;
    }

    public Palforge.Sdk.Script.Pal.PalArenaWorldRankingInfo? GetArenaWorldRankingInfo()
    {
        return SdkEnv.Wrap(Call("GetArenaWorldRankingInfo")) as Palforge.Sdk.Script.Pal.PalArenaWorldRankingInfo;
    }

    public int GetArenaBattleTime()
    {
        return As<int>(Call("GetArenaBattleTime"));
    }

    public void ForceStageExitAll()
    {
        Call("ForceStageExitAll");
    }

    public void ExitArena(Palforge.Sdk.Script.Pal.PalPlayerCharacter? player)
    {
        Call("ExitArena", Bytes<nint>(player?.Address ?? 0));
    }

    public void ExitAllByInstanceId(Palforge.Sdk.Script.CoreUObject.Guid arenaInstanceId)
    {
        Call("ExitAllByInstanceId", SdkEnv.StructBytes(arenaInstanceId, 16));
    }

    public void AddGroupCharacter(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? addIndividualHandle)
    {
        Call("AddGroupCharacter", Bytes<nint>(addIndividualHandle?.Address ?? 0));
    }
}
