// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalArenaRankPointChangeResult : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Guid PlayerUId =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x0, Context);

    public int AfterPoint
    {
        get => ReadAt<int>(0x10);
        set => WriteAt(0x10, value);
    }

    public int ChangePoint
    {
        get => ReadAt<int>(0x14);
        set => WriteAt(0x14, value);
    }

    public Palforge.Sdk.Script.Pal.EPalArenaRankChange RankChange
    {
        get => (Palforge.Sdk.Script.Pal.EPalArenaRankChange)ReadAt<byte>(0x18);
        set => WriteAt(0x18, (byte)value);
    }

    internal PalArenaRankPointChangeResult(nint address, UnrealContext context) : base(address, context, "PalArenaRankPointChangeResult")
    {
    }

    private protected PalArenaRankPointChangeResult(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalArenaRankPointChangeResult? Allocate()
    {
        return SdkEnv.AllocateStruct<PalArenaRankPointChangeResult>("PalArenaRankPointChangeResult");
    }
}
