// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalActionSpawnItem : Palforge.Sdk.Script.Pal.PalActionBase
{
    public string SpawnSocketName
    {
        get => ReadNameAt(0x160);
        set => WriteNameAt(0x160, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector SpawnLocationOffset =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x168, Context);

    public Palforge.Sdk.Script.CoreUObject.Rotator SpawnItemRotator =>
        new Palforge.Sdk.Script.CoreUObject.Rotator(Address + 0x180, Context);

    internal PalActionSpawnItem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalActionSpawnItem");
    }

    public static new PalActionSpawnItem? New(UObject? outer = null)
    {
        return SdkEnv.New("PalActionSpawnItem", outer) as PalActionSpawnItem;
    }

    public static new PalActionSpawnItem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalActionSpawnItem;
    }

    public static void WriteBlackboard(Palforge.Sdk.Script.Pal.PalNetArchive blackboardRef, Palforge.Sdk.Script.Pal.PalStaticItemIdAndNum itemInfo)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(blackboardRef, 16), SdkEnv.StructBytes(itemInfo, 12) };
        var destinations = new nint[] { blackboardRef.Address, 0 };
        SdkEnv.CallStatic("PalActionSpawnItem", "WriteBlackboard", arguments, destinations, out var outputs);
    }

    public void SpawnItemInServer()
    {
        Call("SpawnItemInServer");
    }

    public void ReadBlackboard(Palforge.Sdk.Script.Pal.PalStaticItemIdAndNum itemInfo)
    {
        var arguments = new byte[][] { SdkEnv.StructBytes(itemInfo, 12) };
        var destinations = new nint[] { itemInfo.Address };
        Call("ReadBlackboard", arguments, destinations, out var outputs);
    }
}
