// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAIControllerWorkerModuleNormal : Palforge.Sdk.Script.Pal.PalAIControllerWorkerModule
{
    internal PalAIControllerWorkerModuleNormal(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAIControllerWorkerModuleNormal");
    }

    public static new PalAIControllerWorkerModuleNormal? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAIControllerWorkerModuleNormal", outer) as PalAIControllerWorkerModuleNormal;
    }

    public static new PalAIControllerWorkerModuleNormal? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAIControllerWorkerModuleNormal;
    }
}
