// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalActionDummyTargetActor : Palforge.Sdk.Script.Engine.Actor
{
    internal PalActionDummyTargetActor(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalActionDummyTargetActor");
    }

    public static new PalActionDummyTargetActor? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("PalActionDummyTargetActor", owner, at) as PalActionDummyTargetActor;
    }

    public static new PalActionDummyTargetActor? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalActionDummyTargetActor;
    }
}
