// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAIActionFunnelSkillBase : Palforge.Sdk.Script.Pal.PalAIActionBase
{
    public Palforge.Sdk.Script.Pal.PalFunnelSkillModule? Module
    {
        get => WrapAt(0x138) as Palforge.Sdk.Script.Pal.PalFunnelSkillModule;
        set => WriteObjectAt(0x138, value);
    }

    internal PalAIActionFunnelSkillBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAIActionFunnelSkillBase");
    }

    public static new PalAIActionFunnelSkillBase? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAIActionFunnelSkillBase", outer) as PalAIActionFunnelSkillBase;
    }

    public static new PalAIActionFunnelSkillBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAIActionFunnelSkillBase;
    }

    public void SetModule(Palforge.Sdk.Script.Pal.PalFunnelSkillModule? inModule)
    {
        Call("SetModule", Bytes<nint>(inModule?.Address ?? 0));
    }
}
