// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalAIActionWorkerWorking : Palforge.Sdk.Script.Pal.PalAIActionWorkerChildBase
{
    public Palforge.Sdk.Script.Pal.EPalWorkType CurrentWorkType
    {
        get => (Palforge.Sdk.Script.Pal.EPalWorkType)ReadAt<byte>(0x148);
        set => WriteAt(0x148, (byte)value);
    }

    public float TurnSpeedToTarget
    {
        get => ReadAt<float>(0x14C);
        set => WriteAt(0x14C, value);
    }

    internal PalAIActionWorkerWorking(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalAIActionWorkerWorking");
    }

    public static new PalAIActionWorkerWorking? New(UObject? outer = null)
    {
        return SdkEnv.New("PalAIActionWorkerWorking", outer) as PalAIActionWorkerWorking;
    }

    public static new PalAIActionWorkerWorking? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalAIActionWorkerWorking;
    }
}
