// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalBaseCampPassiveEffectSanityDecreaseSuppressor : Palforge.Sdk.Script.Pal.PalBaseCampPassiveEffectBase
{
    public float SanityDecreaseSuppressionRate
    {
        get => ReadAt<float>(0x78);
        set => WriteAt(0x78, value);
    }

    internal PalBaseCampPassiveEffectSanityDecreaseSuppressor(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalBaseCampPassiveEffect_SanityDecreaseSuppressor");
    }

    public static new PalBaseCampPassiveEffectSanityDecreaseSuppressor? New(UObject? outer = null)
    {
        return SdkEnv.New("PalBaseCampPassiveEffect_SanityDecreaseSuppressor", outer) as PalBaseCampPassiveEffectSanityDecreaseSuppressor;
    }

    public static new PalBaseCampPassiveEffectSanityDecreaseSuppressor? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalBaseCampPassiveEffectSanityDecreaseSuppressor;
    }
}
