// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalBuildObjectDefenseBase : Palforge.Sdk.Script.Pal.PalBuildObject
{
    public UObject? DefenseAIActionClass
    {
        get => WrapAt(0x750);
        set => WriteObjectAt(0x750, value);
    }

    internal PalBuildObjectDefenseBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalBuildObjectDefenseBase");
    }

    public static new PalBuildObjectDefenseBase? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("PalBuildObjectDefenseBase", owner, at) as PalBuildObjectDefenseBase;
    }

    public static new PalBuildObjectDefenseBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalBuildObjectDefenseBase;
    }

    public Palforge.Sdk.Script.CoreUObject.Rotator? GetCharacterRotation()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Rotator>(this, "GetCharacterRotation", "Rotator");
    }

    public void GetCharacterLocationAndRotationWithOffset(Palforge.Sdk.Script.Pal.PalCharacter? ownerCharacter, Palforge.Sdk.Script.CoreUObject.Vector preCharaLocation, Palforge.Sdk.Script.CoreUObject.Vector outLocation, Palforge.Sdk.Script.CoreUObject.Rotator outRotation)
    {
        var arguments = new byte[][] { Bytes<nint>(ownerCharacter?.Address ?? 0), SdkEnv.StructBytes(preCharaLocation, 24), SdkEnv.StructBytes(outLocation, 24), SdkEnv.StructBytes(outRotation, 24) };
        var destinations = new nint[] { 0, 0, outLocation.Address, outRotation.Address };
        Call("GetCharacterLocationAndRotationWithOffset", arguments, destinations, out var outputs);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector? GetCharacterLocation()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Vector>(this, "GetCharacterLocation", "Vector");
    }
}
