// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalCharacterContainerSortInfo : UStructValue
{
    public Palforge.Sdk.Script.Pal.EPalCharacterContainerSortType SortType
    {
        get => (Palforge.Sdk.Script.Pal.EPalCharacterContainerSortType)ReadAt<byte>(0x0);
        set => WriteAt(0x0, (byte)value);
    }

    public UnrealArray<byte> PrioritizeFavoriteIndexArray =>
        new UnrealArray<byte>(this, 0x8, 0x1, "PrioritizeFavoriteIndexArray", static (context, element) => context.ValueAt<byte>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalElementType> FilteringElementType =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalElementType>(this, 0x18, 0x1, "FilteringElementType", static (context, element) => (Palforge.Sdk.Script.Pal.EPalElementType)context.ValueAt<byte>(element), static (context, value) => Bytes((byte)value), null);

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalWorkSuitability> FilteringSuitability =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalWorkSuitability>(this, 0x28, 0x1, "FilteringSuitability", static (context, element) => (Palforge.Sdk.Script.Pal.EPalWorkSuitability)context.ValueAt<byte>(element), static (context, value) => Bytes((byte)value), null);

    public bool BPrioritizeMale
    {
        get => ReadBoolAt(0x38, 0xFF);
        set => WriteBoolAt(0x38, 0xFF, value);
    }

    public bool BPrioritizeFemael
    {
        get => ReadBoolAt(0x39, 0xFF);
        set => WriteBoolAt(0x39, 0xFF, value);
    }

    public bool BPrioritizeNoneGender
    {
        get => ReadBoolAt(0x3A, 0xFF);
        set => WriteBoolAt(0x3A, 0xFF, value);
    }

    public bool BPrioritizeImportedPal
    {
        get => ReadBoolAt(0x3B, 0xFF);
        set => WriteBoolAt(0x3B, 0xFF, value);
    }

    public string FilteringPassiveId
    {
        get => ReadNameAt(0x3C);
        set => WriteNameAt(0x3C, value);
    }

    internal PalCharacterContainerSortInfo(nint address, UnrealContext context) : base(address, context, "PalCharacterContainerSortInfo")
    {
    }

    private protected PalCharacterContainerSortInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalCharacterContainerSortInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<PalCharacterContainerSortInfo>("PalCharacterContainerSortInfo");
    }
}
