// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalCharacterOnCompleteInitializeParameterWrapper : UObject
{
    internal PalCharacterOnCompleteInitializeParameterWrapper(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalCharacterOnCompleteInitializeParameterWrapper");
    }

    public static PalCharacterOnCompleteInitializeParameterWrapper? New(UObject? outer = null)
    {
        return SdkEnv.New("PalCharacterOnCompleteInitializeParameterWrapper", outer) as PalCharacterOnCompleteInitializeParameterWrapper;
    }

    public static PalCharacterOnCompleteInitializeParameterWrapper? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalCharacterOnCompleteInitializeParameterWrapper;
    }

    public void Broadcast(Palforge.Sdk.Script.Pal.PalCharacter? character)
    {
        Call("Broadcast", Bytes<nint>(character?.Address ?? 0));
    }
}
