// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalCoopClimbPlayer : UObject
{
    public Palforge.Sdk.Script.Pal.PalCharacter? Player
    {
        get => WrapAt(0x28) as Palforge.Sdk.Script.Pal.PalCharacter;
        set => WriteObjectAt(0x28, value);
    }

    public Palforge.Sdk.Script.Pal.PalAnimInstance? PlayerAnime
    {
        get => WrapAt(0x30) as Palforge.Sdk.Script.Pal.PalAnimInstance;
        set => WriteObjectAt(0x30, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.EHumanBone> BoneChain =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EHumanBone>(this, 0x38, 0x1, "BoneChain", static (context, element) => (Palforge.Sdk.Script.Pal.EHumanBone)context.ValueAt<byte>(element), static (context, value) => Bytes((byte)value), null);

    public int CurrentIndex
    {
        get => ReadAt<int>(0x48);
        set => WriteAt(0x48, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Transform TargetWorldTf =>
        new Palforge.Sdk.Script.CoreUObject.Transform(Address + 0x50, Context);

    public float Progress
    {
        get => ReadAt<float>(0xB0);
        set => WriteAt(0xB0, value);
    }

    public bool Complete
    {
        get => ReadBoolAt(0xB4, 0xFF);
        set => WriteBoolAt(0xB4, 0xFF, value);
    }

    internal PalCoopClimbPlayer(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalCoopClimbPlayer");
    }

    public static PalCoopClimbPlayer? New(UObject? outer = null)
    {
        return SdkEnv.New("PalCoopClimbPlayer", outer) as PalCoopClimbPlayer;
    }

    public static PalCoopClimbPlayer? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalCoopClimbPlayer;
    }

    public Palforge.Sdk.Script.CoreUObject.Transform? UpdateTransform(Palforge.Sdk.Script.CoreUObject.Transform climber, float progressSpeed, float leapPosSpeed, float leapRotateSpeed, float deltaTime)
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Transform>(this, "UpdateTransform", "Transform", SdkEnv.StructBytes(climber, 96), Bytes(progressSpeed), Bytes(leapPosSpeed), Bytes(leapRotateSpeed), Bytes(deltaTime));
    }

    public void StartStandAnimeDelegateDelegateSignature()
    {
        Call("StartStandAnimeDelegate__DelegateSignature");
    }

    public void InitializeNode(Palforge.Sdk.Script.Pal.EHumanBone entryBone, Palforge.Sdk.Script.Pal.PalCharacter? playerCharacter, Palforge.Sdk.Script.CoreUObject.Transform climber)
    {
        Call("InitializeNode", Bytes((byte)entryBone), Bytes<nint>(playerCharacter?.Address ?? 0), SdkEnv.StructBytes(climber, 96));
    }
}
