// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalCutsceneIdleAnimComponent : Palforge.Sdk.Script.Engine.ActorComponent
{
    public Palforge.Sdk.Script.Engine.AnimMontage? CurrentMontage
    {
        get => WrapAt(0xA0) as Palforge.Sdk.Script.Engine.AnimMontage;
        set => WriteObjectAt(0xA0, value);
    }

    internal PalCutsceneIdleAnimComponent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalCutsceneIdleAnimComponent");
    }

    public static new PalCutsceneIdleAnimComponent? New(UObject? outer = null)
    {
        return SdkEnv.New("PalCutsceneIdleAnimComponent", outer) as PalCutsceneIdleAnimComponent;
    }

    public static new PalCutsceneIdleAnimComponent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalCutsceneIdleAnimComponent;
    }
}
