// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalCullSubsystem : Palforge.Sdk.Script.Pal.PalWorldSubsystem
{
    public UnrealArray<Palforge.Sdk.Script.Pal.PalCullVolumeBase?> CullVolumes =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalCullVolumeBase?>(this, 0x208, 0x8, "CullVolumes", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Pal.PalCullVolumeBase, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal PalCullSubsystem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalCullSubsystem");
    }

    public static new PalCullSubsystem? New(UObject? outer = null)
    {
        return SdkEnv.New("PalCullSubsystem", outer) as PalCullSubsystem;
    }

    public static new PalCullSubsystem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalCullSubsystem;
    }
}
