// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalDimensionalDistortionPawn : Palforge.Sdk.Script.Engine.Pawn
{
    public Palforge.Sdk.Script.Engine.CapsuleComponent? CollisionComponent
    {
        get => WrapAt(0x318) as Palforge.Sdk.Script.Engine.CapsuleComponent;
        set => WriteObjectAt(0x318, value);
    }

    public Palforge.Sdk.Script.Pal.PalDimensionalDistortionMovementComponent? MovementComponent
    {
        get => WrapAt(0x320) as Palforge.Sdk.Script.Pal.PalDimensionalDistortionMovementComponent;
        set => WriteObjectAt(0x320, value);
    }

    public float MoveSpeed
    {
        get => ReadAt<float>(0x328);
        set => WriteAt(0x328, value);
    }

    public float AccelerationRate
    {
        get => ReadAt<float>(0x32C);
        set => WriteAt(0x32C, value);
    }

    public float InterpSpeed
    {
        get => ReadAt<float>(0x330);
        set => WriteAt(0x330, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Guid AssignedWarpPointLocationId =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x334, Context);

    public float TeleportCooldown
    {
        get => ReadAt<float>(0x344);
        set => WriteAt(0x344, value);
    }

    public UObject? OwnerSpawner
    {
        get => ReadWeakAt(0x348);
        set => WriteWeakAt(0x348, value);
    }

    public Palforge.Sdk.Script.Pal.EPalDimensionalDistortionState ReplicatedState
    {
        get => (Palforge.Sdk.Script.Pal.EPalDimensionalDistortionState)ReadAt<byte>(0x350);
        set => WriteAt(0x350, (byte)value);
    }

    public UObject? TeleportSessionTarget
    {
        get => ReadWeakAt(0x370);
        set => WriteWeakAt(0x370, value);
    }

    public bool BWasClientContact
    {
        get => ReadBoolAt(0x378, 0xFF);
        set => WriteBoolAt(0x378, 0xFF, value);
    }

    internal PalDimensionalDistortionPawn(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalDimensionalDistortionPawn");
    }

    public static new PalDimensionalDistortionPawn? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("PalDimensionalDistortionPawn", owner, at) as PalDimensionalDistortionPawn;
    }

    public static new PalDimensionalDistortionPawn? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalDimensionalDistortionPawn;
    }

    public void OnTeleportSessionBeginMulticast(Palforge.Sdk.Script.Pal.PalPlayerCharacter? targetPlayer)
    {
        Call("OnTeleportSessionBegin_Multicast", Bytes<nint>(targetPlayer?.Address ?? 0));
    }

    public void OnTeleportSessionBegin(Palforge.Sdk.Script.Pal.PalPlayerCharacter? targetPlayer)
    {
        Call("OnTeleportSessionBegin", Bytes<nint>(targetPlayer?.Address ?? 0));
    }

    public void OnRepReplicatedState()
    {
        Call("OnRep_ReplicatedState");
    }

    public void MulticastOnTeleportExecuted(Palforge.Sdk.Script.Pal.PalPlayerCharacter? teleportedPlayer, Palforge.Sdk.Script.CoreUObject.Vector destination)
    {
        Call("Multicast_OnTeleportExecuted", Bytes<nint>(teleportedPlayer?.Address ?? 0), SdkEnv.StructBytes(destination, 24));
    }

    public void MulticastCleanupPlayerRideStateForTeleport(Palforge.Sdk.Script.Pal.PalPlayerCharacter? player)
    {
        Call("Multicast_CleanupPlayerRideStateForTeleport", Bytes<nint>(player?.Address ?? 0));
    }

    public float GetWarpRotationZ()
    {
        return As<float>(Call("GetWarpRotationZ"));
    }

    public Palforge.Sdk.Script.CoreUObject.Vector? GetWarpDestination()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Vector>(this, "GetWarpDestination", "Vector");
    }

    public Palforge.Sdk.Script.Pal.PalPlayerCharacter? GetTeleportSessionTarget()
    {
        return SdkEnv.Wrap(Call("GetTeleportSessionTarget")) as Palforge.Sdk.Script.Pal.PalPlayerCharacter;
    }

    public Palforge.Sdk.Script.Pal.PalPlayerCharacter? GetTargetPlayer()
    {
        return SdkEnv.Wrap(Call("GetTargetPlayer")) as Palforge.Sdk.Script.Pal.PalPlayerCharacter;
    }

    public Palforge.Sdk.Script.CoreUObject.Vector? GetReturnLocation()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Vector>(this, "GetReturnLocation", "Vector");
    }

    public Palforge.Sdk.Script.Pal.EPalDimensionalDistortionState GetReplicatedState()
    {
        return (Palforge.Sdk.Script.Pal.EPalDimensionalDistortionState)As<byte>(Call("GetReplicatedState"));
    }

    public Palforge.Sdk.Script.Pal.PalDimensionalDistortionSpawner? GetOwnerSpawner()
    {
        return SdkEnv.Wrap(Call("GetOwnerSpawner")) as Palforge.Sdk.Script.Pal.PalDimensionalDistortionSpawner;
    }

    public Palforge.Sdk.Script.Pal.PalDimensionalDistortionMovementComponent? GetDistortionMovementComponent()
    {
        return SdkEnv.Wrap(Call("GetDistortionMovementComponent")) as Palforge.Sdk.Script.Pal.PalDimensionalDistortionMovementComponent;
    }

    public float GetCollisionRadius()
    {
        return As<float>(Call("GetCollisionRadius"));
    }

    public Palforge.Sdk.Script.Engine.CapsuleComponent? GetCollisionComponent()
    {
        return SdkEnv.Wrap(Call("GetCollisionComponent")) as Palforge.Sdk.Script.Engine.CapsuleComponent;
    }

    public Palforge.Sdk.Script.CoreUObject.Guid? GetAssignedWarpPointLocationId()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.Guid>(this, "GetAssignedWarpPointLocationId", "Guid");
    }
}
