// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalDropItemDatabaseRow : UStructValue
{
    public string CharacterID
    {
        get => ReadNameAt(0x8);
        set => WriteNameAt(0x8, value);
    }

    public int Level
    {
        get => ReadAt<int>(0x10);
        set => WriteAt(0x10, value);
    }

    public string ItemId1
    {
        get => ReadNameAt(0x14);
        set => WriteNameAt(0x14, value);
    }

    public float Rate1
    {
        get => ReadAt<float>(0x1C);
        set => WriteAt(0x1C, value);
    }

    public int Min1
    {
        get => ReadAt<int>(0x20);
        set => WriteAt(0x20, value);
    }

    public int Max1
    {
        get => ReadAt<int>(0x24);
        set => WriteAt(0x24, value);
    }

    public string ItemId2
    {
        get => ReadNameAt(0x28);
        set => WriteNameAt(0x28, value);
    }

    public float Rate2
    {
        get => ReadAt<float>(0x30);
        set => WriteAt(0x30, value);
    }

    public int Min2
    {
        get => ReadAt<int>(0x34);
        set => WriteAt(0x34, value);
    }

    public int Max2
    {
        get => ReadAt<int>(0x38);
        set => WriteAt(0x38, value);
    }

    public string ItemId3
    {
        get => ReadNameAt(0x3C);
        set => WriteNameAt(0x3C, value);
    }

    public float Rate3
    {
        get => ReadAt<float>(0x44);
        set => WriteAt(0x44, value);
    }

    public int Min3
    {
        get => ReadAt<int>(0x48);
        set => WriteAt(0x48, value);
    }

    public int Max3
    {
        get => ReadAt<int>(0x4C);
        set => WriteAt(0x4C, value);
    }

    public string ItemId4
    {
        get => ReadNameAt(0x50);
        set => WriteNameAt(0x50, value);
    }

    public float Rate4
    {
        get => ReadAt<float>(0x58);
        set => WriteAt(0x58, value);
    }

    public int Min4
    {
        get => ReadAt<int>(0x5C);
        set => WriteAt(0x5C, value);
    }

    public int Max4
    {
        get => ReadAt<int>(0x60);
        set => WriteAt(0x60, value);
    }

    public string ItemId5
    {
        get => ReadNameAt(0x64);
        set => WriteNameAt(0x64, value);
    }

    public float Rate5
    {
        get => ReadAt<float>(0x6C);
        set => WriteAt(0x6C, value);
    }

    public int Min5
    {
        get => ReadAt<int>(0x70);
        set => WriteAt(0x70, value);
    }

    public int Max5
    {
        get => ReadAt<int>(0x74);
        set => WriteAt(0x74, value);
    }

    public string ItemId6
    {
        get => ReadNameAt(0x78);
        set => WriteNameAt(0x78, value);
    }

    public float Rate6
    {
        get => ReadAt<float>(0x80);
        set => WriteAt(0x80, value);
    }

    public int Min6
    {
        get => ReadAt<int>(0x84);
        set => WriteAt(0x84, value);
    }

    public int Max6
    {
        get => ReadAt<int>(0x88);
        set => WriteAt(0x88, value);
    }

    public string ItemId7
    {
        get => ReadNameAt(0x8C);
        set => WriteNameAt(0x8C, value);
    }

    public float Rate7
    {
        get => ReadAt<float>(0x94);
        set => WriteAt(0x94, value);
    }

    public int Min7
    {
        get => ReadAt<int>(0x98);
        set => WriteAt(0x98, value);
    }

    public int Max7
    {
        get => ReadAt<int>(0x9C);
        set => WriteAt(0x9C, value);
    }

    public string ItemId8
    {
        get => ReadNameAt(0xA0);
        set => WriteNameAt(0xA0, value);
    }

    public float Rate8
    {
        get => ReadAt<float>(0xA8);
        set => WriteAt(0xA8, value);
    }

    public int Min8
    {
        get => ReadAt<int>(0xAC);
        set => WriteAt(0xAC, value);
    }

    public int Max8
    {
        get => ReadAt<int>(0xB0);
        set => WriteAt(0xB0, value);
    }

    public string ItemId9
    {
        get => ReadNameAt(0xB4);
        set => WriteNameAt(0xB4, value);
    }

    public float Rate9
    {
        get => ReadAt<float>(0xBC);
        set => WriteAt(0xBC, value);
    }

    public int Min9
    {
        get => ReadAt<int>(0xC0);
        set => WriteAt(0xC0, value);
    }

    public int Max9
    {
        get => ReadAt<int>(0xC4);
        set => WriteAt(0xC4, value);
    }

    public string ItemId10
    {
        get => ReadNameAt(0xC8);
        set => WriteNameAt(0xC8, value);
    }

    public float Rate10
    {
        get => ReadAt<float>(0xD0);
        set => WriteAt(0xD0, value);
    }

    public int Min10
    {
        get => ReadAt<int>(0xD4);
        set => WriteAt(0xD4, value);
    }

    public int Max10
    {
        get => ReadAt<int>(0xD8);
        set => WriteAt(0xD8, value);
    }

    internal PalDropItemDatabaseRow(nint address, UnrealContext context) : base(address, context, "PalDropItemDatabaseRow")
    {
    }

    private protected PalDropItemDatabaseRow(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalDropItemDatabaseRow? Allocate()
    {
        return SdkEnv.AllocateStruct<PalDropItemDatabaseRow>("PalDropItemDatabaseRow");
    }
}
