// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalEnemyCampTreasureBoxItemInfo : UStructValue
{
    public string MapObjectId
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public Palforge.Sdk.Script.Pal.EPalMapObjectTreasureGradeType GradeType
    {
        get => (Palforge.Sdk.Script.Pal.EPalMapObjectTreasureGradeType)ReadAt<byte>(0x8);
        set => WriteAt(0x8, (byte)value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.PalItemAndNum> Items =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalItemAndNum>(this, 0x10, 0x2C, "Items", static (context, element) => new Palforge.Sdk.Script.Pal.PalItemAndNum(element, context), static (context, value) => context.BytesAt(value.Address, 0x2C), null);

    public bool BOpened
    {
        get => ReadBoolAt(0x20, 0xFF);
        set => WriteBoolAt(0x20, 0xFF, value);
    }

    internal PalEnemyCampTreasureBoxItemInfo(nint address, UnrealContext context) : base(address, context, "PalEnemyCampTreasureBoxItemInfo")
    {
    }

    private protected PalEnemyCampTreasureBoxItemInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalEnemyCampTreasureBoxItemInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<PalEnemyCampTreasureBoxItemInfo>("PalEnemyCampTreasureBoxItemInfo");
    }
}
