// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalFindEnemyOption : UStructValue
{
    public bool BCheckAimTargetSocket
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    public bool BTargetFriend
    {
        get => ReadBoolAt(0x1, 0xFF);
        set => WriteBoolAt(0x1, 0xFF, value);
    }

    public bool BTargetNeutral
    {
        get => ReadBoolAt(0x2, 0xFF);
        set => WriteBoolAt(0x2, 0xFF, value);
    }

    public bool BTargetPlayer
    {
        get => ReadBoolAt(0x3, 0xFF);
        set => WriteBoolAt(0x3, 0xFF, value);
    }

    public bool BFilterByHateList
    {
        get => ReadBoolAt(0x4, 0xFF);
        set => WriteBoolAt(0x4, 0xFF, value);
    }

    public bool BLineTrace
    {
        get => ReadBoolAt(0x5, 0xFF);
        set => WriteBoolAt(0x5, 0xFF, value);
    }

    public bool BIgnoreRidePal
    {
        get => ReadBoolAt(0x6, 0xFF);
        set => WriteBoolAt(0x6, 0xFF, value);
    }

    public byte TraceType
    {
        get => ReadAt<byte>(0x7);
        set => WriteAt(0x7, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Engine.Actor?> IgnoreActors =>
        new UnrealArray<Palforge.Sdk.Script.Engine.Actor?>(this, 0x8, 0x8, "IgnoreActors", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.Actor, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public float MaxRangeCap
    {
        get => ReadAt<float>(0x18);
        set => WriteAt(0x18, value);
    }

    internal PalFindEnemyOption(nint address, UnrealContext context) : base(address, context, "PalFindEnemyOption")
    {
    }

    private protected PalFindEnemyOption(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalFindEnemyOption? Allocate()
    {
        return SdkEnv.AllocateStruct<PalFindEnemyOption>("PalFindEnemyOption");
    }
}
