// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalFastWorkAssignRepInfoArray : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.Pal.PalWorkAssignRepInfo> Items =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalWorkAssignRepInfo>(this, 0x108, 0x18, "Items", static (context, element) => new Palforge.Sdk.Script.Pal.PalWorkAssignRepInfo(element, context), static (context, value) => context.BytesAt(value.Address, 0x18), null);

    public int ArrayReplicationKey
    {
        get => ReadAt<int>(0x54);
        set => WriteAt(0x54, value);
    }

    public Palforge.Sdk.Script.NetCore.EFastArraySerializerDeltaFlags DeltaFlags
    {
        get => (Palforge.Sdk.Script.NetCore.EFastArraySerializerDeltaFlags)ReadAt<byte>(0x100);
        set => WriteAt(0x100, (byte)value);
    }

    internal PalFastWorkAssignRepInfoArray(nint address, UnrealContext context) : base(address, context, "PalFastWorkAssignRepInfoArray")
    {
    }

    private protected PalFastWorkAssignRepInfoArray(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalFastWorkAssignRepInfoArray? Allocate()
    {
        return SdkEnv.AllocateStruct<PalFastWorkAssignRepInfoArray>("PalFastWorkAssignRepInfoArray");
    }
}
