// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalHUDDispatchParameterMultiHatchingEgg : Palforge.Sdk.Script.Pal.PalHUDDispatchParameterBase
{
    public Palforge.Sdk.Script.Pal.PalMapObjectMultiHatchingEggModel? HatchingEggModel
    {
        get => WrapAt(0x38) as Palforge.Sdk.Script.Pal.PalMapObjectMultiHatchingEggModel;
        set => WriteObjectAt(0x38, value);
    }

    internal PalHUDDispatchParameterMultiHatchingEgg(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalHUDDispatchParameter_MultiHatchingEgg");
    }

    public static new PalHUDDispatchParameterMultiHatchingEgg? New(UObject? outer = null)
    {
        return SdkEnv.New("PalHUDDispatchParameter_MultiHatchingEgg", outer) as PalHUDDispatchParameterMultiHatchingEgg;
    }

    public static new PalHUDDispatchParameterMultiHatchingEgg? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalHUDDispatchParameterMultiHatchingEgg;
    }
}
