// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalKillLogFilteringWaiter : UObject
{
    public bool IsKillLog
    {
        get => ReadBoolAt(0x38, 0xFF);
        set => WriteBoolAt(0x38, 0xFF, value);
    }

    public Palforge.Sdk.Script.Pal.PalKillLogDisplayData LogData =>
        new Palforge.Sdk.Script.Pal.PalKillLogDisplayData(Address + 0x40, Context);

    internal PalKillLogFilteringWaiter(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalKillLogFilteringWaiter");
    }

    public static PalKillLogFilteringWaiter? New(UObject? outer = null)
    {
        return SdkEnv.New("PalKillLogFilteringWaiter", outer) as PalKillLogFilteringWaiter;
    }

    public static PalKillLogFilteringWaiter? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalKillLogFilteringWaiter;
    }

    public void OnReceivedWordFilteringResult(string responseBody, bool bResponseOK, int responseCode)
    {
        Call("OnReceivedWordFilteringResult", StringArgument(responseBody), Bytes<byte>(bResponseOK ? (byte)1 : (byte)0), Bytes(responseCode));
    }

    public void OnFilteredKillLogDelegateDelegateSignature(Palforge.Sdk.Script.Pal.PalKillLogFilteringWaiter? waiter, Palforge.Sdk.Script.Pal.PalKillLogDisplayData message)
    {
        Call("OnFilteredKillLogDelegate__DelegateSignature", Bytes<nint>(waiter?.Address ?? 0), SdkEnv.StructBytes(message, 104));
    }
}
