// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalLocationPointStaticCreateParameter : Palforge.Sdk.Script.Pal.PalLocationCreateParameter
{
    internal PalLocationPointStaticCreateParameter(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalLocationPointStaticCreateParameter");
    }

    public static new PalLocationPointStaticCreateParameter? New(UObject? outer = null)
    {
        return SdkEnv.New("PalLocationPointStaticCreateParameter", outer) as PalLocationPointStaticCreateParameter;
    }

    public static new PalLocationPointStaticCreateParameter? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalLocationPointStaticCreateParameter;
    }
}
