// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalLoadingScreenWidgetBase : Palforge.Sdk.Script.Pal.PalUserWidget
{
    internal PalLoadingScreenWidgetBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalLoadingScreenWidgetBase");
    }

    public static new PalLoadingScreenWidgetBase? New(UObject? outer = null)
    {
        return SdkEnv.New("PalLoadingScreenWidgetBase", outer) as PalLoadingScreenWidgetBase;
    }

    public static new PalLoadingScreenWidgetBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalLoadingScreenWidgetBase;
    }
}
