// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMultiLineEditableTextBox : Palforge.Sdk.Script.Umg.TextLayoutWidget
{
    public string Text =>
        ReadTextAt(0x170);

    public string HintText =>
        ReadTextAt(0x188);

    public UnrealDelegate HintTextDelegate =>
        new UnrealDelegate(this, 0x1A0);

    public Palforge.Sdk.Script.SlateCore.EditableTextBoxStyle WidgetStyle =>
        new Palforge.Sdk.Script.SlateCore.EditableTextBoxStyle(Address + 0x1B0, Context);

    public bool BIsReadOnly
    {
        get => ReadBoolAt(0x1040, 0xFF);
        set => WriteBoolAt(0x1040, 0xFF, value);
    }

    public bool AllowContextMenu
    {
        get => ReadBoolAt(0x1041, 0xFF);
        set => WriteBoolAt(0x1041, 0xFF, value);
    }

    public Palforge.Sdk.Script.Slate.VirtualKeyboardOptions VirtualKeyboardOptions =>
        new Palforge.Sdk.Script.Slate.VirtualKeyboardOptions(Address + 0x1042, Context);

    public Palforge.Sdk.Script.Slate.EVirtualKeyboardDismissAction VirtualKeyboardDismissAction
    {
        get => (Palforge.Sdk.Script.Slate.EVirtualKeyboardDismissAction)ReadAt<byte>(0x1043);
        set => WriteAt(0x1043, (byte)value);
    }

    internal PalMultiLineEditableTextBox(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMultiLineEditableTextBox");
    }

    public static new PalMultiLineEditableTextBox? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMultiLineEditableTextBox", outer) as PalMultiLineEditableTextBox;
    }

    public static new PalMultiLineEditableTextBox? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMultiLineEditableTextBox;
    }

    public void SetTextStyle(Palforge.Sdk.Script.SlateCore.TextBlockStyle inTextStyle)
    {
        Call("SetTextStyle", SdkEnv.StructBytes(inTextStyle, 848));
    }

    public void SetIsReadOnly(bool bReadOnly)
    {
        Call("SetIsReadOnly", Bytes<byte>(bReadOnly ? (byte)1 : (byte)0));
    }

    public void SetForegroundColor(Palforge.Sdk.Script.CoreUObject.LinearColor color)
    {
        Call("SetForegroundColor", SdkEnv.StructBytes(color, 16));
    }
}
