// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectItemContainerAccessInterface : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal PalMapObjectItemContainerAccessInterface(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMapObjectItemContainerAccessInterface");
    }

    public static new PalMapObjectItemContainerAccessInterface? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMapObjectItemContainerAccessInterface", outer) as PalMapObjectItemContainerAccessInterface;
    }

    public static new PalMapObjectItemContainerAccessInterface? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMapObjectItemContainerAccessInterface;
    }

    public void RequestStopItemContainerReplication()
    {
        Call("RequestStopItemContainerReplication");
    }

    public void RequestStartItemContainerReplication()
    {
        Call("RequestStartItemContainerReplication");
    }

    public void RequestSortContainerItemContainerAccessInterface()
    {
        Call("RequestSortContainer_ItemContainerAccessInterface");
    }

    public Palforge.Sdk.Script.Pal.PalItemContainer? GetItemContainerItemContainerAccessInterface()
    {
        return SdkEnv.Wrap(Call("GetItemContainer_ItemContainerAccessInterface")) as Palforge.Sdk.Script.Pal.PalItemContainer;
    }

    public int GetDisplayContainerSlotNumDefault()
    {
        return As<int>(Call("GetDisplayContainerSlotNumDefault"));
    }
}
