// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectDefenseAutoTurretModel : Palforge.Sdk.Script.Pal.PalMapObjectDefenseNoWorkerModel
{
    public UObject? CachedEnemyObserver
    {
        get => ReadWeakAt(0x228);
        set => WriteWeakAt(0x228, value);
    }

    internal PalMapObjectDefenseAutoTurretModel(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMapObjectDefenseAutoTurretModel");
    }

    public static new PalMapObjectDefenseAutoTurretModel? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMapObjectDefenseAutoTurretModel", outer) as PalMapObjectDefenseAutoTurretModel;
    }

    public static new PalMapObjectDefenseAutoTurretModel? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMapObjectDefenseAutoTurretModel;
    }
}
