// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectDetectableParameterComponent : Palforge.Sdk.Script.Engine.ActorComponent
{
    internal PalMapObjectDetectableParameterComponent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMapObjectDetectableParameterComponent");
    }

    public static new PalMapObjectDetectableParameterComponent? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMapObjectDetectableParameterComponent", outer) as PalMapObjectDetectableParameterComponent;
    }

    public static new PalMapObjectDetectableParameterComponent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMapObjectDetectableParameterComponent;
    }
}
