// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectInfoTickInBackground : UStructValue
{
    internal PalMapObjectInfoTickInBackground(nint address, UnrealContext context) : base(address, context, "PalMapObjectInfoTickInBackground")
    {
    }

    private protected PalMapObjectInfoTickInBackground(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalMapObjectInfoTickInBackground? Allocate()
    {
        return SdkEnv.AllocateStruct<PalMapObjectInfoTickInBackground>("PalMapObjectInfoTickInBackground");
    }
}
