// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectModelConnectorFoundation : Palforge.Sdk.Script.Pal.PalMapObjectModelConnectorBase
{
    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo FrontConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0x48, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo BackConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0x60, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo LeftConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0x78, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo RightConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0x90, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo CornerFrontLeftConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0xA8, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo CornerFrontRightConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0xC0, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo CornerBackLeftConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0xD8, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo CornerBackRightConnectInfo =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelConnectInfo(Address + 0xF0, Context);

    internal PalMapObjectModelConnectorFoundation(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMapObjectModelConnectorFoundation");
    }

    public static new PalMapObjectModelConnectorFoundation? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMapObjectModelConnectorFoundation", outer) as PalMapObjectModelConnectorFoundation;
    }

    public static new PalMapObjectModelConnectorFoundation? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMapObjectModelConnectorFoundation;
    }
}
