// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectPickableCharacterModelBase : Palforge.Sdk.Script.Pal.PalMapObjectConcreteModelBase
{
    public Palforge.Sdk.Script.Pal.PalCharacterStoredParameterId StoredParameterId =>
        new Palforge.Sdk.Script.Pal.PalCharacterStoredParameterId(Address + 0x220, Context);

    public Palforge.Sdk.Script.Pal.PalCharacterStoredParameterInfo ForReadStoredParameter =>
        new Palforge.Sdk.Script.Pal.PalCharacterStoredParameterInfo(Address + 0x230, Context);

    public Palforge.Sdk.Script.CoreUObject.Guid LocationId =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x5E8, Context);

    public Palforge.Sdk.Script.CoreUObject.DateTime CreatedAtRealTime =>
        new Palforge.Sdk.Script.CoreUObject.DateTime(Address + 0x600, Context);

    public Palforge.Sdk.Script.CoreUObject.Guid PickupablePlayerUid =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x608, Context);

    internal PalMapObjectPickableCharacterModelBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalMapObjectPickableCharacterModelBase");
    }

    public static new PalMapObjectPickableCharacterModelBase? New(UObject? outer = null)
    {
        return SdkEnv.New("PalMapObjectPickableCharacterModelBase", outer) as PalMapObjectPickableCharacterModelBase;
    }

    public static new PalMapObjectPickableCharacterModelBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalMapObjectPickableCharacterModelBase;
    }

    public void RequestPickupServerInternal(int requestPlayerId)
    {
        Call("RequestPickup_ServerInternal", Bytes(requestPlayerId));
    }

    public void RequestPickup()
    {
        Call("RequestPickup");
    }

    public void OnRemovedStoredCharacterServerInternal(Palforge.Sdk.Script.Pal.PalCharacterStoredParameterId removedID)
    {
        Call("OnRemovedStoredCharacter_ServerInternal", SdkEnv.StructBytes(removedID, 16));
    }

    public Palforge.Sdk.Script.CoreUObject.DateTime? GetCreatedAtRealTime()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.DateTime>(this, "GetCreatedAtRealTime", "DateTime");
    }

    public Palforge.Sdk.Script.Pal.PalIndividualCharacterSaveParameter? GetCharacterSaveParameter()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.Pal.PalIndividualCharacterSaveParameter>(this, "GetCharacterSaveParameter", "PalIndividualCharacterSaveParameter");
    }

    public void CorrectInvalidCreatedAtRealTimeForOldSaveServerInternal()
    {
        Call("CorrectInvalidCreatedAtRealTimeForOldSave_ServerInternal");
    }
}
