// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalMapObjectSaveData : UStructValue
{
    public string MapObjectId
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public Palforge.Sdk.Script.Pal.PalMapObjectModelSaveData Model =>
        new Palforge.Sdk.Script.Pal.PalMapObjectModelSaveData(Address + 0x8, Context);

    public Palforge.Sdk.Script.Pal.PalMapObjectConcreteModelSaveData ConcreteModel =>
        new Palforge.Sdk.Script.Pal.PalMapObjectConcreteModelSaveData(Address + 0xD8, Context);

    internal PalMapObjectSaveData(nint address, UnrealContext context) : base(address, context, "PalMapObjectSaveData")
    {
    }

    private protected PalMapObjectSaveData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalMapObjectSaveData? Allocate()
    {
        return SdkEnv.AllocateStruct<PalMapObjectSaveData>("PalMapObjectSaveData");
    }
}
