// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalNavigationInvokerComponent : Palforge.Sdk.Script.NavigationSystem.NavigationInvokerComponent
{
    public bool BIsAutoActivateInvoker
    {
        get => ReadBoolAt(0xB0, 0xFF);
        set => WriteBoolAt(0xB0, 0xFF, value);
    }

    public bool BIsWaitWorldPartition
    {
        get => ReadBoolAt(0xB1, 0xFF);
        set => WriteBoolAt(0xB1, 0xFF, value);
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint AreaBelongTo =>
        new Palforge.Sdk.Script.CoreUObject.IntPoint(Address + 0xB4, Context);

    public Palforge.Sdk.Script.Pal.FlagContainer IsDisableInvorkerFlag =>
        new Palforge.Sdk.Script.Pal.FlagContainer(Address + 0xC0, Context);

    internal PalNavigationInvokerComponent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalNavigationInvokerComponent");
    }

    public static new PalNavigationInvokerComponent? New(UObject? outer = null)
    {
        return SdkEnv.New("PalNavigationInvokerComponent", outer) as PalNavigationInvokerComponent;
    }

    public static new PalNavigationInvokerComponent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalNavigationInvokerComponent;
    }

    public void SetDisableInvorkerFlag(string flagName, bool isDisable)
    {
        Call("SetDisableInvorkerFlag", SdkEnv.NameBytes(flagName), Bytes<byte>(isDisable ? (byte)1 : (byte)0));
    }

    public bool IsDisableInvorker()
    {
        return As<byte>(Call("IsDisableInvorker")) is not 0;
    }

    public bool GetDisableInvorkerFlag(string flagName)
    {
        return As<byte>(Call("GetDisableInvorkerFlag", SdkEnv.NameBytes(flagName))) is not 0;
    }

    public void DeactivateInvoker()
    {
        Call("DeactivateInvoker");
    }

    public void ActivateInvoker()
    {
        Call("ActivateInvoker");
    }
}
