// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalNetworkItemOperationParameter : UStructValue
{
    internal PalNetworkItemOperationParameter(nint address, UnrealContext context) : base(address, context, "PalNetworkItemOperationParameter")
    {
    }

    private protected PalNetworkItemOperationParameter(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalNetworkItemOperationParameter? Allocate()
    {
        return SdkEnv.AllocateStruct<PalNetworkItemOperationParameter>("PalNetworkItemOperationParameter");
    }
}
