// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalOptimizeParameter : UStructValue
{
    public int FoliageISMDistanceMeters
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    public float TargetFPS
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    public float MinFPS
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public float MaxFPS
    {
        get => ReadAt<float>(0xC);
        set => WriteAt(0xC, value);
    }

    public int CharacterImportanceCheckNumberPerFrame
    {
        get => ReadAt<int>(0x10);
        set => WriteAt(0x10, value);
    }

    public int CharacterImportanceNearestCount
    {
        get => ReadAt<int>(0x14);
        set => WriteAt(0x14, value);
    }

    public float CharacterImportanceNearDistance
    {
        get => ReadAt<float>(0x18);
        set => WriteAt(0x18, value);
    }

    public float CharacterImportanceFarDistance
    {
        get => ReadAt<float>(0x1C);
        set => WriteAt(0x1C, value);
    }

    public float CharacterImportanceFarthestDistance
    {
        get => ReadAt<float>(0x20);
        set => WriteAt(0x20, value);
    }

    public float DeadBodyDespawnSightRange
    {
        get => ReadAt<float>(0x24);
        set => WriteAt(0x24, value);
    }

    public float DeadBodyDespawnUpdateIntervalSeconds
    {
        get => ReadAt<float>(0x28);
        set => WriteAt(0x28, value);
    }

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalActor =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x30, 0x10, 0x4, "CharacterImportance_TickInterval_Actor", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalMovement =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x80, 0x10, 0x4, "CharacterImportance_TickInterval_Movement", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalMesh =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0xD0, 0x10, 0x4, "CharacterImportance_TickInterval_Mesh", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalMeshUpdate =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x120, 0x10, 0x4, "CharacterImportance_TickInterval_Mesh_Update", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalMeshEvaluation =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x170, 0x10, 0x4, "CharacterImportance_TickInterval_Mesh_Evaluation", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalAction =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x1C0, 0x10, 0x4, "CharacterImportance_TickInterval_Action", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalStatus =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x210, 0x10, 0x4, "CharacterImportance_TickInterval_Status", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalLookAt =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x260, 0x10, 0x4, "CharacterImportance_TickInterval_LookAt", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalVisualEffect =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x2B0, 0x10, 0x4, "CharacterImportance_TickInterval_VisualEffect", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalShooter =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x300, 0x10, 0x4, "CharacterImportance_TickInterval_Shooter", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalFlyMesh =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x350, 0x10, 0x4, "CharacterImportance_TickInterval_FlyMesh", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalController =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x3A0, 0x10, 0x4, "CharacterImportance_TickInterval_Controller", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalAIAction =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x3F0, 0x10, 0x4, "CharacterImportance_TickInterval_AIAction", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalAISensor =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x440, 0x10, 0x4, "CharacterImportance_TickInterval_AISensor", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float> CharacterImportanceTickIntervalPathFollowing =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalCharacterImportanceType, float>(this, 0x490, 0x10, 0x4, "CharacterImportance_TickInterval_PathFollowing", static (context, element) => (Palforge.Sdk.Script.Pal.EPalCharacterImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public float SpawnerImportanceNearDistance
    {
        get => ReadAt<float>(0x4E0);
        set => WriteAt(0x4E0, value);
    }

    public float SpawnerImportanceFarDistance
    {
        get => ReadAt<float>(0x4E4);
        set => WriteAt(0x4E4, value);
    }

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType, float> SpawnerImportanceTickIntervalNPCSpawner =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType, float>(this, 0x4E8, 0x10, 0x4, "SpawnerImportance_TickInterval_NPCSpawner", static (context, element) => (Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    public UnrealMap<Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType, float> LevelObjectImportanceTickIntervalLevelObjectActor =>
        new UnrealMap<Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType, float>(this, 0x538, 0x10, 0x4, "LevelObjectImportance_TickInterval_LevelObjectActor", static (context, element) => (Palforge.Sdk.Script.Pal.EPalSpwnerImportanceType)context.ValueAt<byte>(element), static (context, element) => context.ValueAt<float>(element), static (context, value) => Bytes((byte)value), static (context, value) => Bytes(value), null, null);

    internal PalOptimizeParameter(nint address, UnrealContext context) : base(address, context, "PalOptimizeParameter")
    {
    }

    private protected PalOptimizeParameter(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalOptimizeParameter? Allocate()
    {
        return SdkEnv.AllocateStruct<PalOptimizeParameter>("PalOptimizeParameter");
    }
}
