// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalOilrigSaveStatus : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid> DestroyedCannon =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid>(this, 0x0, 0x10, "DestroyedCannon", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Guid(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid> DestroyedGasTank =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid>(this, 0x10, 0x10, "DestroyedGasTank", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Guid(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid> WipedOutEnemySpawner =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid>(this, 0x20, 0x10, "WipedOutEnemySpawner", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Guid(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid> OpenedTreasureBoxSpawner =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Guid>(this, 0x30, 0x10, "OpenedTreasureBoxSpawner", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Guid(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public int GoalTreasureBoxSpawnerIndex
    {
        get => ReadAt<int>(0x40);
        set => WriteAt(0x40, value);
    }

    public bool Alarm
    {
        get => ReadBoolAt(0x44, 0xFF);
        set => WriteBoolAt(0x44, 0xFF, value);
    }

    public bool Clear
    {
        get => ReadBoolAt(0x45, 0xFF);
        set => WriteBoolAt(0x45, 0xFF, value);
    }

    public float ResetTimer
    {
        get => ReadAt<float>(0x48);
        set => WriteAt(0x48, value);
    }

    public bool IsMachineSpawned
    {
        get => ReadBoolAt(0x4C, 0xFF);
        set => WriteBoolAt(0x4C, 0xFF, value);
    }

    public bool IsMachineDestroyed
    {
        get => ReadBoolAt(0x4D, 0xFF);
        set => WriteBoolAt(0x4D, 0xFF, value);
    }

    internal PalOilrigSaveStatus(nint address, UnrealContext context) : base(address, context, "PalOilrigSaveStatus")
    {
    }

    private protected PalOilrigSaveStatus(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalOilrigSaveStatus? Allocate()
    {
        return SdkEnv.AllocateStruct<PalOilrigSaveStatus>("PalOilrigSaveStatus");
    }
}
