// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalPalBoothTradeInfo : UStructValue
{
    public Palforge.Sdk.Script.Pal.PalInstanceID PalId =>
        new Palforge.Sdk.Script.Pal.PalInstanceID(Address + 0x0, Context);

    public Palforge.Sdk.Script.Pal.PalItemAndNum Cost =>
        new Palforge.Sdk.Script.Pal.PalItemAndNum(Address + 0x30, Context);

    public Palforge.Sdk.Script.CoreUObject.Guid SellerPlayerUId =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x5C, Context);

    internal PalPalBoothTradeInfo(nint address, UnrealContext context) : base(address, context, "PalPalBoothTradeInfo")
    {
    }

    private protected PalPalBoothTradeInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalPalBoothTradeInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<PalPalBoothTradeInfo>("PalPalBoothTradeInfo");
    }
}
