// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRelicPossessNumEntry : UStructValue
{
    public Palforge.Sdk.Script.Pal.EPalRelicType Type
    {
        get => (Palforge.Sdk.Script.Pal.EPalRelicType)ReadAt<byte>(0x0);
        set => WriteAt(0x0, (byte)value);
    }

    public Palforge.Sdk.Script.Pal.ThreadSafeInt32 Num =>
        new Palforge.Sdk.Script.Pal.ThreadSafeInt32(Address + 0x4, Context);

    internal PalRelicPossessNumEntry(nint address, UnrealContext context) : base(address, context, "PalRelicPossessNumEntry")
    {
    }

    private protected PalRelicPossessNumEntry(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalRelicPossessNumEntry? Allocate()
    {
        return SdkEnv.AllocateStruct<PalRelicPossessNumEntry>("PalRelicPossessNumEntry");
    }
}
