// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRandomIncidentSpawnMonsterOutbreakData : UStructValue
{
    public Palforge.Sdk.Script.Pal.PalDataTableRowNamePalMonsterData CharacterID =>
        new Palforge.Sdk.Script.Pal.PalDataTableRowNamePalMonsterData(Address + 0x8, Context);

    public int Num
    {
        get => ReadAt<int>(0x10);
        set => WriteAt(0x10, value);
    }

    public int LevelMin
    {
        get => ReadAt<int>(0x14);
        set => WriteAt(0x14, value);
    }

    public int LevelMax
    {
        get => ReadAt<int>(0x18);
        set => WriteAt(0x18, value);
    }

    public int Group
    {
        get => ReadAt<int>(0x1C);
        set => WriteAt(0x1C, value);
    }

    public bool IsSquad
    {
        get => ReadBoolAt(0x20, 0xFF);
        set => WriteBoolAt(0x20, 0xFF, value);
    }

    public Palforge.Sdk.Script.Engine.DataTable? LocationTable
    {
        get => WrapAt(0x28) as Palforge.Sdk.Script.Engine.DataTable;
        set => WriteObjectAt(0x28, value);
    }

    public UObject? ControllerClass
    {
        get => WrapAt(0x30);
        set => WriteObjectAt(0x30, value);
    }

    public UObject? DefaultActionClass
    {
        get => WrapAt(0x38);
        set => WriteObjectAt(0x38, value);
    }

    internal PalRandomIncidentSpawnMonsterOutbreakData(nint address, UnrealContext context) : base(address, context, "PalRandomIncidentSpawnMonsterOutbreakData")
    {
    }

    private protected PalRandomIncidentSpawnMonsterOutbreakData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalRandomIncidentSpawnMonsterOutbreakData? Allocate()
    {
        return SdkEnv.AllocateStruct<PalRandomIncidentSpawnMonsterOutbreakData>("PalRandomIncidentSpawnMonsterOutbreakData");
    }
}
