// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRegionAreaTriggerBase : Palforge.Sdk.Script.Engine.Actor
{
    public Palforge.Sdk.Script.Pal.PalDataTableRowNameWorldMapAreaData AreaName =>
        new Palforge.Sdk.Script.Pal.PalDataTableRowNameWorldMapAreaData(Address + 0x290, Context);

    internal PalRegionAreaTriggerBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalRegionAreaTriggerBase");
    }

    public static new PalRegionAreaTriggerBase? Spawn(UObject? owner = null, UStructValue? at = null)
    {
        return SdkEnv.SpawnActor("PalRegionAreaTriggerBase", owner, at) as PalRegionAreaTriggerBase;
    }

    public static new PalRegionAreaTriggerBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalRegionAreaTriggerBase;
    }

    public void OnOverlap(Palforge.Sdk.Script.Engine.Actor? otherActor)
    {
        Call("OnOverlap", Bytes<nint>(otherActor?.Address ?? 0));
    }

    public void OnEndOverlap(Palforge.Sdk.Script.Engine.Actor? otherActor)
    {
        Call("OnEndOverlap", Bytes<nint>(otherActor?.Address ?? 0));
    }
}
