// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRaidBossSpawnInfo : UStructValue
{
    public Palforge.Sdk.Script.Pal.PalDataTableRowNamePalMonsterData PalId =>
        new Palforge.Sdk.Script.Pal.PalDataTableRowNamePalMonsterData(Address + 0x0, Context);

    public int Level
    {
        get => ReadAt<int>(0x8);
        set => WriteAt(0x8, value);
    }

    public Palforge.Sdk.Script.Pal.EPalWazaID WarpWazaID
    {
        get => (Palforge.Sdk.Script.Pal.EPalWazaID)ReadAt<ushort>(0xC);
        set => WriteAt(0xC, (ushort)value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID> BaseCampAttackWazaIDs =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID>(this, 0x10, 0x2, "BaseCampAttackWazaIDs", static (context, element) => (Palforge.Sdk.Script.Pal.EPalWazaID)context.ValueAt<ushort>(element), static (context, value) => Bytes((ushort)value), null);

    public Palforge.Sdk.Script.Pal.EPalElementType OverrideInitialElement1
    {
        get => (Palforge.Sdk.Script.Pal.EPalElementType)ReadAt<byte>(0x20);
        set => WriteAt(0x20, (byte)value);
    }

    public Palforge.Sdk.Script.Pal.EPalElementType OverrideInitialElement2
    {
        get => (Palforge.Sdk.Script.Pal.EPalElementType)ReadAt<byte>(0x21);
        set => WriteAt(0x21, (byte)value);
    }

    public bool CanModeChange
    {
        get => ReadBoolAt(0x22, 0xFF);
        set => WriteBoolAt(0x22, 0xFF, value);
    }

    public bool IgnoreLargeDown
    {
        get => ReadBoolAt(0x23, 0xFF);
        set => WriteBoolAt(0x23, 0xFF, value);
    }

    public Palforge.Sdk.Script.Pal.EPalStatusID ModeChangeAddStatusToAllWhenModeChgange
    {
        get => (Palforge.Sdk.Script.Pal.EPalStatusID)ReadAt<byte>(0x24);
        set => WriteAt(0x24, (byte)value);
    }

    public Palforge.Sdk.Script.Pal.EPalElementType ModeChangeElement1
    {
        get => (Palforge.Sdk.Script.Pal.EPalElementType)ReadAt<byte>(0x25);
        set => WriteAt(0x25, (byte)value);
    }

    public Palforge.Sdk.Script.Pal.EPalElementType ModeChangeElement2
    {
        get => (Palforge.Sdk.Script.Pal.EPalElementType)ReadAt<byte>(0x26);
        set => WriteAt(0x26, (byte)value);
    }

    public UnrealArray<string> ModeChangeAddPassiveSkill =>
        new UnrealArray<string>(this, 0x28, 0x8, "ModeChange_AddPassiveSkill", static (context, element) => context.NameAt(element), static (context, value) => context.NameBytes(value), null);

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID> ModeChangeAddWaza =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID>(this, 0x38, 0x2, "ModeChange_AddWaza", static (context, element) => (Palforge.Sdk.Script.Pal.EPalWazaID)context.ValueAt<ushort>(element), static (context, value) => Bytes((ushort)value), null);

    public UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID> ModeChangeRemoveWaza =>
        new UnrealArray<Palforge.Sdk.Script.Pal.EPalWazaID>(this, 0x48, 0x2, "ModeChange_RemoveWaza", static (context, element) => (Palforge.Sdk.Script.Pal.EPalWazaID)context.ValueAt<ushort>(element), static (context, value) => Bytes((ushort)value), null);

    public UObject? AIControllerClass
    {
        get => WrapAt(0x58);
        set => WriteObjectAt(0x58, value);
    }

    internal PalRaidBossSpawnInfo(nint address, UnrealContext context) : base(address, context, "PalRaidBossSpawnInfo")
    {
    }

    private protected PalRaidBossSpawnInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalRaidBossSpawnInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<PalRaidBossSpawnInfo>("PalRaidBossSpawnInfo");
    }
}
