// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalReticleTargetUtility : UObject
{
    internal PalReticleTargetUtility(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalReticleTargetUtility");
    }

    public static PalReticleTargetUtility? New(UObject? outer = null)
    {
        return SdkEnv.New("PalReticleTargetUtility", outer) as PalReticleTargetUtility;
    }

    public static PalReticleTargetUtility? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalReticleTargetUtility;
    }
}
