// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRESTAPISubsystem : Palforge.Sdk.Script.Engine.GameInstanceSubsystem
{
    internal PalRESTAPISubsystem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalRESTAPISubsystem");
    }

    public static new PalRESTAPISubsystem? New(UObject? outer = null)
    {
        return SdkEnv.New("PalRESTAPISubsystem", outer) as PalRESTAPISubsystem;
    }

    public static new PalRESTAPISubsystem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalRESTAPISubsystem;
    }
}
