// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalRecordCountRewardData : UStructValue
{
    public string RecordID
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public int RequireCount
    {
        get => ReadAt<int>(0x8);
        set => WriteAt(0x8, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Pal.PalStaticItemIdAndNum> RewardItems =>
        new UnrealArray<Palforge.Sdk.Script.Pal.PalStaticItemIdAndNum>(this, 0x10, 0xC, "RewardItems", static (context, element) => new Palforge.Sdk.Script.Pal.PalStaticItemIdAndNum(element, context), static (context, value) => context.BytesAt(value.Address, 0xC), null);

    public int ExpBonusLevel
    {
        get => ReadAt<int>(0x20);
        set => WriteAt(0x20, value);
    }

    internal PalRecordCountRewardData(nint address, UnrealContext context) : base(address, context, "PalRecordCountRewardData")
    {
    }

    private protected PalRecordCountRewardData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalRecordCountRewardData? Allocate()
    {
        return SdkEnv.AllocateStruct<PalRecordCountRewardData>("PalRecordCountRewardData");
    }
}
