// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalSoundSlot : UObject
{
    public UnrealMap<Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID, Palforge.Sdk.Script.AkAudio.AkAudioEvent?> SoundMap =>
        new UnrealMap<Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID, Palforge.Sdk.Script.AkAudio.AkAudioEvent?>(this, 0x28, 0x18, 0x8, "SoundMap", static (context, element) => new Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID(element, context), static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.AkAudio.AkAudioEvent, static (context, value) => context.BytesAt(value.Address, 0x8), static (context, value) => Bytes<nint>(value?.Address ?? 0), null, null);

    public UnrealMap<int, Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID> PlaySoundParameters =>
        new UnrealMap<int, Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID>(this, 0x78, 0x14, 0x4, "PlaySoundParameters", static (context, element) => context.ValueAt<int>(element), static (context, element) => new Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID(element, context), static (context, value) => Bytes(value), static (context, value) => context.BytesAt(value.Address, 0x8), null, null);

    public Palforge.Sdk.Script.Pal.PalSoundPlayer? SoundPlayer
    {
        get => WrapAt(0xC8) as Palforge.Sdk.Script.Pal.PalSoundPlayer;
        set => WriteObjectAt(0xC8, value);
    }

    internal PalSoundSlot(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalSoundSlot");
    }

    public static PalSoundSlot? New(UObject? outer = null)
    {
        return SdkEnv.New("PalSoundSlot", outer) as PalSoundSlot;
    }

    public static PalSoundSlot? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalSoundSlot;
    }

    public void Terminate()
    {
        Call("Terminate");
    }

    public void StopSoundBySoundId(Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID soundId)
    {
        Call("StopSoundBySoundId", SdkEnv.StructBytes(soundId, 8));
    }

    public void StopSound()
    {
        Call("StopSound");
    }

    public void StopByPlayingId(int playingID)
    {
        Call("StopByPlayingId", Bytes(playingID));
    }

    public void SetSwitch(string switchGroup, string switchState)
    {
        Call("SetSwitch", StringArgument(switchGroup), StringArgument(switchState));
    }

    public void SetRTPCValue(string name, float value, float interpolSec)
    {
        Call("SetRTPCValue", SdkEnv.NameBytes(name), Bytes(value), Bytes(interpolSec));
    }

    public void SetPhysicalMaterial(byte physicalSurface)
    {
        Call("SetPhysicalMaterial", Bytes(physicalSurface));
    }

    public int PlaySoundByAkEvent(Palforge.Sdk.Script.AkAudio.AkAudioEvent? akEvent, Palforge.Sdk.Script.Pal.PalSoundOptions options)
    {
        return As<int>(Call("PlaySoundByAkEvent", Bytes<nint>(akEvent?.Address ?? 0), SdkEnv.StructBytes(options, 4)));
    }

    public int PlaySound(Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID id, Palforge.Sdk.Script.Pal.PalSoundOptions options)
    {
        return As<int>(Call("PlaySound", SdkEnv.StructBytes(id, 8), SdkEnv.StructBytes(options, 4)));
    }

    public void OnAkPostEventCallback(Palforge.Sdk.Script.AkAudio.EAkCallbackType callbackType, Palforge.Sdk.Script.AkAudio.AkCallbackInfo? callbackInfo)
    {
        Call("OnAkPostEventCallback", Bytes((byte)callbackType), Bytes<nint>(callbackInfo?.Address ?? 0));
    }

    public bool IsPlayingBySoundId(Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID soundId)
    {
        return As<byte>(Call("IsPlayingBySoundId", SdkEnv.StructBytes(soundId, 8))) is not 0;
    }

    public void Initialize()
    {
        Call("Initialize");
    }

    public Palforge.Sdk.Script.Pal.PalSoundPlayer? GetSoundPlayer()
    {
        return SdkEnv.Wrap(Call("GetSoundPlayer")) as Palforge.Sdk.Script.Pal.PalSoundPlayer;
    }

    public Palforge.Sdk.Script.AkAudio.AkAudioEvent? GetAkEvent(Palforge.Sdk.Script.Pal.PalDataTableRowNameSoundID id)
    {
        return SdkEnv.Wrap(Call("GetAkEvent", SdkEnv.StructBytes(id, 8))) as Palforge.Sdk.Script.AkAudio.AkAudioEvent;
    }
}
