// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalSporeManager : Palforge.Sdk.Script.Pal.PalWorldSubsystem
{
    public float TickIntervalSeconds
    {
        get => ReadAt<float>(0x78);
        set => WriteAt(0x78, value);
    }

    public float SpawnRadius
    {
        get => ReadAt<float>(0x7C);
        set => WriteAt(0x7C, value);
    }

    public float DespawnRadius
    {
        get => ReadAt<float>(0x80);
        set => WriteAt(0x80, value);
    }

    internal PalSporeManager(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalSporeManager");
    }

    public static new PalSporeManager? New(UObject? outer = null)
    {
        return SdkEnv.New("PalSporeManager", outer) as PalSporeManager;
    }

    public static new PalSporeManager? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalSporeManager;
    }
}
