// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalStationaryLauncherLoopStartParameter : UStructValue
{
    public float LoopInterval
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public int LoopCount
    {
        get => ReadAt<int>(0x4);
        set => WriteAt(0x4, value);
    }

    internal PalStationaryLauncherLoopStartParameter(nint address, UnrealContext context) : base(address, context, "PalStationaryLauncherLoopStartParameter")
    {
    }

    private protected PalStationaryLauncherLoopStartParameter(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalStationaryLauncherLoopStartParameter? Allocate()
    {
        return SdkEnv.AllocateStruct<PalStationaryLauncherLoopStartParameter>("PalStationaryLauncherLoopStartParameter");
    }
}
