// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalSkinDataArmor : Palforge.Sdk.Script.Pal.PalSkinDataBase
{
    public UnrealMap<string, string> HairAttachSocketNameMap =>
        new UnrealMap<string, string>(this, 0x128, 0x18, 0x8, "HairAttachSocketNameMap", static (context, element) => context.NameAt(element), static (context, element) => context.NameAt(element), static (context, value) => context.NameBytes(value), static (context, value) => context.NameBytes(value), null, null);

    internal PalSkinDataArmor(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalSkinDataArmor");
    }

    public static new PalSkinDataArmor? New(UObject? outer = null)
    {
        return SdkEnv.New("PalSkinDataArmor", outer) as PalSkinDataArmor;
    }

    public static new PalSkinDataArmor? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalSkinDataArmor;
    }
}
