// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUICaptureCameraOffsetData : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector LocationOffset =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Rotator Rotator =>
        new Palforge.Sdk.Script.CoreUObject.Rotator(Address + 0x20, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector PointLightOffset =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x38, Context);

    public float PointLightIntensity
    {
        get => ReadAt<float>(0x50);
        set => WriteAt(0x50, value);
    }

    public float PointLightSize
    {
        get => ReadAt<float>(0x54);
        set => WriteAt(0x54, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector PointLightOffset2 =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x58, Context);

    public float PointLightIntensity2
    {
        get => ReadAt<float>(0x70);
        set => WriteAt(0x70, value);
    }

    public float PointLightSize2
    {
        get => ReadAt<float>(0x74);
        set => WriteAt(0x74, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector RectLightOffset =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x78, Context);

    public Palforge.Sdk.Script.CoreUObject.Rotator RectLightRotator =>
        new Palforge.Sdk.Script.CoreUObject.Rotator(Address + 0x90, Context);

    public float RectLightIntensity
    {
        get => ReadAt<float>(0xA8);
        set => WriteAt(0xA8, value);
    }

    public float RectLightSize
    {
        get => ReadAt<float>(0xAC);
        set => WriteAt(0xAC, value);
    }

    internal PalUICaptureCameraOffsetData(nint address, UnrealContext context) : base(address, context, "PalUICaptureCameraOffsetData")
    {
    }

    private protected PalUICaptureCameraOffsetData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalUICaptureCameraOffsetData? Allocate()
    {
        return SdkEnv.AllocateStruct<PalUICaptureCameraOffsetData>("PalUICaptureCameraOffsetData");
    }
}
