// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUnlockFastTravelTriggerEvent : UObject
{
    internal PalUnlockFastTravelTriggerEvent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUnlockFastTravelTriggerEvent");
    }

    public static PalUnlockFastTravelTriggerEvent? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUnlockFastTravelTriggerEvent", outer) as PalUnlockFastTravelTriggerEvent;
    }

    public static PalUnlockFastTravelTriggerEvent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUnlockFastTravelTriggerEvent;
    }

    public void TriggerEvent()
    {
        Call("TriggerEvent");
    }
}
