// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIPalBoxBase : Palforge.Sdk.Script.Pal.PalUserWidgetOverlayUI
{
    internal PalUIPalBoxBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIPalBoxBase");
    }

    public static new PalUIPalBoxBase? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIPalBoxBase", outer) as PalUIPalBoxBase;
    }

    public static new PalUIPalBoxBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIPalBoxBase;
    }

    public void TryMoveToOtomo(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? moveSlot)
    {
        Call("TryMoveToOtomo", Bytes<nint>(moveSlot?.Address ?? 0));
    }

    public void TryMoveToBoxForWorker(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? moveSlot)
    {
        Call("TryMoveToBoxForWorker", Bytes<nint>(moveSlot?.Address ?? 0));
    }

    public void TryMoveToBoxForOtomo(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? moveSlot)
    {
        Call("TryMoveToBoxForOtomo", Bytes<nint>(moveSlot?.Address ?? 0));
    }

    public void TryMoveToBaseCamp(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? moveSlot)
    {
        Call("TryMoveToBaseCamp", Bytes<nint>(moveSlot?.Address ?? 0));
    }

    public void TryLoosePal(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? targetSlot)
    {
        Call("TryLoosePal", Bytes<nint>(targetSlot?.Address ?? 0));
    }

    public void ToggleFavorite(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? targetSlot)
    {
        Call("ToggleFavorite", Bytes<nint>(targetSlot?.Address ?? 0));
    }

    public void SetPagePalBoxList(int newPage)
    {
        Call("SetPagePalBoxList", Bytes(newPage));
    }

    public void SetByMapObjectInstanceId(Palforge.Sdk.Script.CoreUObject.Guid byMapObjectInstanceId)
    {
        Call("SetByMapObjectInstanceId", SdkEnv.StructBytes(byMapObjectInstanceId, 16));
    }

    public void SetBaseCampId(Palforge.Sdk.Script.CoreUObject.Guid baseCampId)
    {
        Call("SetBaseCampId", SdkEnv.StructBytes(baseCampId, 16));
    }

    public void SelectCharacterSlot(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? targetSlot, Palforge.Sdk.Script.Pal.EPalItemSlotPressType pressType)
    {
        Call("SelectCharacterSlot", Bytes<nint>(targetSlot?.Address ?? 0), Bytes((byte)pressType));
    }

    public void RequestSortBox(Palforge.Sdk.Script.Pal.PalCharacterContainerSortInfo sortInfo)
    {
        Call("RequestSortBox", SdkEnv.StructBytes(sortInfo, 72));
    }

    public void OnUpdateWorkerCapacity(Palforge.Sdk.Script.Pal.PalIndividualCharacterContainer? container)
    {
        Call("OnUpdateWorkerCapacity", Bytes<nint>(container?.Address ?? 0));
    }

    public bool GetNowDisplayWorkerList(out Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot[] outSlots)
    {
        var arguments = new byte[][] { new byte[16] };
        var result = Call("GetNowDisplayWorkerList", arguments, out var outputs);
        outSlots = SdkEnv.Objects<Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot>(outputs[0]);
        return As<byte>(result) is not 0;
    }

    public int GetBoxMaxPageNum()
    {
        return As<int>(Call("GetBoxMaxPageNum"));
    }

    public void ChangePrevPagePalBoxList()
    {
        Call("ChangePrevPagePalBoxList");
    }

    public void ChangePageByDataIndex(int dataIndex)
    {
        Call("ChangePageByDataIndex", Bytes(dataIndex));
    }

    public void ChangeNextPagePalBoxList()
    {
        Call("ChangeNextPagePalBoxList");
    }

    public void CancelLift()
    {
        Call("CancelLift");
    }
}
