// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIProductSettingModel : UObject
{
    public string TargetMapObjectName =>
        ReadTextAt(0x58);

    public string SelectedRecipeId
    {
        get => ReadNameAt(0x70);
        set => WriteNameAt(0x70, value);
    }

    public string FocusedRecipeId
    {
        get => ReadNameAt(0x78);
        set => WriteNameAt(0x78, value);
    }

    public int ProductNum
    {
        get => ReadAt<int>(0x80);
        set => WriteAt(0x80, value);
    }

    public UObject? WeakOwnerConcreteModel
    {
        get => ReadWeakAt(0x84);
        set => WriteWeakAt(0x84, value);
    }

    internal PalUIProductSettingModel(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIProductSettingModel");
    }

    public static PalUIProductSettingModel? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIProductSettingModel", outer) as PalUIProductSettingModel;
    }

    public static PalUIProductSettingModel? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIProductSettingModel;
    }

    public void UpdateSettingDelegateDelegateSignature(Palforge.Sdk.Script.Pal.PalUIProductSettingModel? model)
    {
        Call("UpdateSettingDelegate__DelegateSignature", Bytes<nint>(model?.Address ?? 0));
    }

    public void SetProductNumByInput(int inputNum)
    {
        Call("SetProductNumByInput", Bytes(inputNum));
    }

    public void SetMaxProduction()
    {
        Call("SetMaxProduction");
    }

    public void SetInfiniteProduction()
    {
        Call("SetInfiniteProduction");
    }

    public void SetFocusedRecipe(string recipeID)
    {
        Call("SetFocusedRecipe", SdkEnv.NameBytes(recipeID));
    }

    public void SelectRecipe(string recipeID)
    {
        Call("SelectRecipe", SdkEnv.NameBytes(recipeID));
    }

    public void ResetProductNum()
    {
        Call("ResetProductNum");
    }

    public void OnUpdateInventory(Palforge.Sdk.Script.Pal.PalItemContainerMultiHelper? iInventoryContainers)
    {
        Call("OnUpdateInventory", Bytes<nint>(iInventoryContainers?.Address ?? 0));
    }

    public void NotifyUpdateForce()
    {
        Call("NotifyUpdateForce");
    }

    public bool IsProductNumInfinite()
    {
        return As<byte>(Call("IsProductNumInfinite")) is not 0;
    }

    public void IncreaseProductNum()
    {
        Call("IncreaseProductNum");
    }

    public string GetRecipeId()
    {
        return SdkEnv.Text(Call("GetRecipeId"));
    }

    public Palforge.Sdk.Script.Pal.PalItemRecipe? GetRecipe()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.Pal.PalItemRecipe>(this, "GetRecipe", "PalItemRecipe");
    }

    public int GetProductNum()
    {
        return As<int>(Call("GetProductNum"));
    }

    public void DecreaseProductNum()
    {
        Call("DecreaseProductNum");
    }

    public float CalcWorkAmount()
    {
        return As<float>(Call("CalcWorkAmount"));
    }

    public int CalcMaxProductableNum()
    {
        return As<int>(Call("CalcMaxProductableNum"));
    }

    public int CalcConsumeEnergy()
    {
        return As<int>(Call("CalcConsumeEnergy"));
    }
}
