// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIMapObjectStatusIndicatorParameterClinic : Palforge.Sdk.Script.Pal.PalUIMapObjectStatusIndicatorParameterBase
{
    public Palforge.Sdk.Script.Pal.PalUIMapObjectClinicStatusIndicatorModel? UIModel
    {
        get => WrapAt(0x40) as Palforge.Sdk.Script.Pal.PalUIMapObjectClinicStatusIndicatorModel;
        set => WriteObjectAt(0x40, value);
    }

    internal PalUIMapObjectStatusIndicatorParameterClinic(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIMapObjectStatusIndicatorParameter_Clinic");
    }

    public static new PalUIMapObjectStatusIndicatorParameterClinic? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIMapObjectStatusIndicatorParameter_Clinic", outer) as PalUIMapObjectStatusIndicatorParameterClinic;
    }

    public static new PalUIMapObjectStatusIndicatorParameterClinic? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIMapObjectStatusIndicatorParameterClinic;
    }
}
