// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIAimReticleBase : Palforge.Sdk.Script.Pal.PalUserWidget
{
    public bool BHideDefaultReticle
    {
        get => ReadBoolAt(0x450, 0xFF);
        set => WriteBoolAt(0x450, 0xFF, value);
    }

    internal PalUIAimReticleBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIAimReticleBase");
    }

    public static new PalUIAimReticleBase? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIAimReticleBase", outer) as PalUIAimReticleBase;
    }

    public static new PalUIAimReticleBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIAimReticleBase;
    }

    public bool ShouldHideDefaultReticle()
    {
        return As<byte>(Call("ShouldHideDefaultReticle")) is not 0;
    }

    public void OnTick(float deltaTime)
    {
        Call("OnTick", Bytes(deltaTime));
    }

    public void OnReticleDeactivated()
    {
        Call("OnReticleDeactivated");
    }

    public void OnReticleActivted(Palforge.Sdk.Script.Pal.PalItemId weaponItemId)
    {
        Call("OnReticleActivted", SdkEnv.StructBytes(weaponItemId, 40));
    }

    public Palforge.Sdk.Script.Pal.PalStaticItemDataBase? GetCurrentWeaponStaticItemData()
    {
        return SdkEnv.Wrap(Call("GetCurrentWeaponStaticItemData")) as Palforge.Sdk.Script.Pal.PalStaticItemDataBase;
    }

    public Palforge.Sdk.Script.Pal.PalDynamicWeaponItemDataBase? GetCurrentWeaponDynamicItemData()
    {
        return SdkEnv.Wrap(Call("GetCurrentWeaponDynamicItemData")) as Palforge.Sdk.Script.Pal.PalDynamicWeaponItemDataBase;
    }

    public Palforge.Sdk.Script.Pal.PalWeaponBase? GetCurrentWeaponActor()
    {
        return SdkEnv.Wrap(Call("GetCurrentWeaponActor")) as Palforge.Sdk.Script.Pal.PalWeaponBase;
    }

    public void DeactivateReticle()
    {
        Call("DeactivateReticle");
    }

    public void ActivateReticle(Palforge.Sdk.Script.Pal.PalItemId weaponItemId)
    {
        Call("ActivateReticle", SdkEnv.StructBytes(weaponItemId, 40));
    }
}
