// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUICharacterStatus : Palforge.Sdk.Script.Pal.PalUserWidgetOverlayUI
{
    internal PalUICharacterStatus(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUICharacterStatus");
    }

    public static new PalUICharacterStatus? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUICharacterStatus", outer) as PalUICharacterStatus;
    }

    public static new PalUICharacterStatus? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUICharacterStatus;
    }

    public void ToggleFavoritePal(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? targetHandle)
    {
        Call("ToggleFavoritePal", Bytes<nint>(targetHandle?.Address ?? 0));
    }

    public void RemoveActiveSkill(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? targetHandle, Palforge.Sdk.Script.Pal.EPalWazaID targetWazaID)
    {
        Call("RemoveActiveSkill", Bytes<nint>(targetHandle?.Address ?? 0), Bytes((ushort)targetWazaID));
    }

    public void DropCharacter(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? targetHandle)
    {
        Call("DropCharacter", Bytes<nint>(targetHandle?.Address ?? 0));
    }

    public void ChangeActiveSkill(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? targetHandle, Palforge.Sdk.Script.Pal.EPalWazaID changeWazaID, Palforge.Sdk.Script.Pal.EPalWazaID newWazaID)
    {
        Call("ChangeActiveSkill", Bytes<nint>(targetHandle?.Address ?? 0), Bytes((ushort)changeWazaID), Bytes((ushort)newWazaID));
    }

    public void AddActiveSkill(Palforge.Sdk.Script.Pal.PalIndividualCharacterHandle? targetHandle, Palforge.Sdk.Script.Pal.EPalWazaID newWazaID)
    {
        Call("AddActiveSkill", Bytes<nint>(targetHandle?.Address ?? 0), Bytes((ushort)newWazaID));
    }
}
