// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUICharacterSkinChanger : Palforge.Sdk.Script.Pal.PalUserWidgetOverlayUI
{
    public UnrealMap<string, Palforge.Sdk.Script.Pal.PalUICharacterSkinDisplayInfo> CachedSkinInfoMap =>
        new UnrealMap<string, Palforge.Sdk.Script.Pal.PalUICharacterSkinDisplayInfo>(this, 0x488, 0x20, 0x8, "CachedSkinInfoMap", static (context, element) => context.NameAt(element), static (context, element) => new Palforge.Sdk.Script.Pal.PalUICharacterSkinDisplayInfo(element, context), static (context, value) => context.NameBytes(value), static (context, value) => context.BytesAt(value.Address, 0x10), null, null);

    internal PalUICharacterSkinChanger(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUICharacterSkinChanger");
    }

    public static new PalUICharacterSkinChanger? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUICharacterSkinChanger", outer) as PalUICharacterSkinChanger;
    }

    public static new PalUICharacterSkinChanger? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUICharacterSkinChanger;
    }

    public void UpdateSkinInfoDelegateDelegateSignature()
    {
        Call("UpdateSkinInfoDelegate__DelegateSignature");
    }

    public void RequestRemoveSkin(Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? targetSlot)
    {
        Call("RequestRemoveSkin", Bytes<nint>(targetSlot?.Address ?? 0));
    }

    public void RequestGetSkinInfo()
    {
        Call("RequestGetSkinInfo");
    }

    public void RequestChangeSkin(string skinName, Palforge.Sdk.Script.Pal.PalIndividualCharacterSlot? targetSlot)
    {
        Call("RequestChangeSkin", SdkEnv.NameBytes(skinName), Bytes<nint>(targetSlot?.Address ?? 0));
    }
}
