// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIInventoryUseItemWindow : Palforge.Sdk.Script.Pal.PalUserWidgetOverlayUI
{
    internal PalUIInventoryUseItemWindow(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIInventoryUseItemWindow");
    }

    public static new PalUIInventoryUseItemWindow? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIInventoryUseItemWindow", outer) as PalUIInventoryUseItemWindow;
    }

    public static new PalUIInventoryUseItemWindow? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIInventoryUseItemWindow;
    }

    public void OnUseReviveItemForClient(Palforge.Sdk.Script.Pal.PalIndividualCharacterParameter? targetParameter)
    {
        Call("OnUseReviveItem_ForClient", Bytes<nint>(targetParameter?.Address ?? 0));
    }
}
