// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIMapObjectStatusIndicatorParameterTeamMission : Palforge.Sdk.Script.Pal.PalUIMapObjectStatusIndicatorParameterBase
{
    public Palforge.Sdk.Script.Pal.PalUIMapObjectCharacterTeamMissionModel? UIModel
    {
        get => WrapAt(0x40) as Palforge.Sdk.Script.Pal.PalUIMapObjectCharacterTeamMissionModel;
        set => WriteObjectAt(0x40, value);
    }

    internal PalUIMapObjectStatusIndicatorParameterTeamMission(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIMapObjectStatusIndicatorParameter_TeamMission");
    }

    public static new PalUIMapObjectStatusIndicatorParameterTeamMission? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIMapObjectStatusIndicatorParameter_TeamMission", outer) as PalUIMapObjectStatusIndicatorParameterTeamMission;
    }

    public static new PalUIMapObjectStatusIndicatorParameterTeamMission? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIMapObjectStatusIndicatorParameterTeamMission;
    }

    public Palforge.Sdk.Script.Pal.PalUIMapObjectCharacterTeamMissionModel? GetUIModel()
    {
        return SdkEnv.Wrap(Call("GetUIModel")) as Palforge.Sdk.Script.Pal.PalUIMapObjectCharacterTeamMissionModel;
    }
}
