// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalUIBuildModel : UObject
{
    public string ForceBuildPalBoxTextId
    {
        get => ReadNameAt(0x28);
        set => WriteNameAt(0x28, value);
    }

    internal PalUIBuildModel(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PalUIBuildModel");
    }

    public static PalUIBuildModel? New(UObject? outer = null)
    {
        return SdkEnv.New("PalUIBuildModel", outer) as PalUIBuildModel;
    }

    public static PalUIBuildModel? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PalUIBuildModel;
    }

    public void StartPaintMode()
    {
        Call("StartPaintMode");
    }

    public void StartDismantleMode()
    {
        Call("StartDismantleMode");
    }

    public void StartBuildObject(string buildObjectId)
    {
        Call("StartBuildObject", SdkEnv.NameBytes(buildObjectId));
    }

    public void OnOpenMenu()
    {
        Call("OnOpenMenu");
    }

    public void OnConfimAlertForceBuildPalBox(bool bDialogBool)
    {
        Call("OnConfimAlert_ForceBuildPalBox", Bytes<byte>(bDialogBool ? (byte)1 : (byte)0));
    }

    public void FinishPaintMode()
    {
        Call("FinishPaintMode");
    }

    public void FinishDismantleMode()
    {
        Call("FinishDismantleMode");
    }
}
