// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalWorkSuitabilityInfo : UStructValue
{
    public Palforge.Sdk.Script.Pal.EPalWorkSuitability WorkSuitability
    {
        get => (Palforge.Sdk.Script.Pal.EPalWorkSuitability)ReadAt<byte>(0x0);
        set => WriteAt(0x0, (byte)value);
    }

    public int Rank
    {
        get => ReadAt<int>(0x4);
        set => WriteAt(0x4, value);
    }

    internal PalWorkSuitabilityInfo(nint address, UnrealContext context) : base(address, context, "PalWorkSuitabilityInfo")
    {
    }

    private protected PalWorkSuitabilityInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalWorkSuitabilityInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<PalWorkSuitabilityInfo>("PalWorkSuitabilityInfo");
    }
}
