// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Pal;

public class PalWorldMapUISaveData : UStructValue
{
    public UnrealArray<byte> MaskTextureData =>
        new UnrealArray<byte>(this, 0x0, 0x1, "MaskTextureData", static (context, element) => context.ValueAt<byte>(element), static (context, value) => Bytes(value), null);

    internal PalWorldMapUISaveData(nint address, UnrealContext context) : base(address, context, "PalWorldMapUISaveData")
    {
    }

    private protected PalWorldMapUISaveData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PalWorldMapUISaveData? Allocate()
    {
        return SdkEnv.AllocateStruct<PalWorldMapUISaveData>("PalWorldMapUISaveData");
    }
}
