// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class AnimNodeControlRigBase : UStructValue
{
    public Palforge.Sdk.Script.Engine.PoseLink Source =>
        new Palforge.Sdk.Script.Engine.PoseLink(Address + 0x58, Context);

    public bool BResetInputPoseToInitial
    {
        get => ReadBoolAt(0x68, 0xFF);
        set => WriteBoolAt(0x68, 0xFF, value);
    }

    public bool BTransferInputPose
    {
        get => ReadBoolAt(0x69, 0xFF);
        set => WriteBoolAt(0x69, 0xFF, value);
    }

    public bool BTransferInputCurves
    {
        get => ReadBoolAt(0x6A, 0xFF);
        set => WriteBoolAt(0x6A, 0xFF, value);
    }

    public bool BTransferPoseInGlobalSpace
    {
        get => ReadBoolAt(0x6B, 0xFF);
        set => WriteBoolAt(0x6B, 0xFF, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Engine.BoneReference> InputBonesToTransfer =>
        new UnrealArray<Palforge.Sdk.Script.Engine.BoneReference>(this, 0x70, 0x10, "InputBonesToTransfer", static (context, element) => new Palforge.Sdk.Script.Engine.BoneReference(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public UObject? NodeMappingContainer
    {
        get => ReadWeakAt(0x240);
        set => WriteWeakAt(0x240, value);
    }

    public Palforge.Sdk.Script.ControlRig.ControlRigIOSettings InputSettings =>
        new Palforge.Sdk.Script.ControlRig.ControlRigIOSettings(Address + 0x248, Context);

    public Palforge.Sdk.Script.ControlRig.ControlRigIOSettings OutputSettings =>
        new Palforge.Sdk.Script.ControlRig.ControlRigIOSettings(Address + 0x24A, Context);

    public bool BExecute
    {
        get => ReadBoolAt(0x24C, 0xFF);
        set => WriteBoolAt(0x24C, 0xFF, value);
    }

    public UnrealArray<Palforge.Sdk.Script.ControlRig.ControlRigAnimNodeEventName> EventQueue =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.ControlRigAnimNodeEventName>(this, 0x258, 0x8, "EventQueue", static (context, element) => new Palforge.Sdk.Script.ControlRig.ControlRigAnimNodeEventName(element, context), static (context, value) => context.BytesAt(value.Address, 0x8), null);

    public UnrealArray<string> SourcePropertyNames =>
        new UnrealArray<string>(this, 0x10, 0x8, "SourcePropertyNames", static (context, element) => context.NameAt(element), static (context, value) => context.NameBytes(value), null);

    public UnrealArray<string> DestPropertyNames =>
        new UnrealArray<string>(this, 0x20, 0x8, "DestPropertyNames", static (context, element) => context.NameAt(element), static (context, value) => context.NameBytes(value), null);

    public UObject? TargetInstance
    {
        get => WrapAt(0x30);
        set => WriteObjectAt(0x30, value);
    }

    internal AnimNodeControlRigBase(nint address, UnrealContext context) : base(address, context, "AnimNode_ControlRigBase")
    {
    }

    private protected AnimNodeControlRigBase(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AnimNodeControlRigBase? Allocate()
    {
        return SdkEnv.AllocateStruct<AnimNodeControlRigBase>("AnimNode_ControlRigBase");
    }
}
