// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class ControlRigSettings : Palforge.Sdk.Script.DeveloperSettings.DeveloperSettings
{
    internal ControlRigSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ControlRigSettings");
    }

    public static new ControlRigSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("ControlRigSettings", outer) as ControlRigSettings;
    }

    public static new ControlRigSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ControlRigSettings;
    }
}
