// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class ControlRigValidator : UObject
{
    public UnrealArray<Palforge.Sdk.Script.ControlRig.ControlRigValidationPass?> Passes =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.ControlRigValidationPass?>(this, 0x28, 0x8, "Passes", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.ControlRig.ControlRigValidationPass, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal ControlRigValidator(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ControlRigValidator");
    }

    public static ControlRigValidator? New(UObject? outer = null)
    {
        return SdkEnv.New("ControlRigValidator", outer) as ControlRigValidator;
    }

    public static ControlRigValidator? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ControlRigValidator;
    }
}
