// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class CRSimPointConstraint : UStructValue
{
    public Palforge.Sdk.Script.ControlRig.ECRSimConstraintType Type
    {
        get => (Palforge.Sdk.Script.ControlRig.ECRSimConstraintType)ReadAt<byte>(0x0);
        set => WriteAt(0x0, (byte)value);
    }

    public int SubjectA
    {
        get => ReadAt<int>(0x4);
        set => WriteAt(0x4, value);
    }

    public int SubjectB
    {
        get => ReadAt<int>(0x8);
        set => WriteAt(0x8, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector DataA =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x10, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector DataB =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x28, Context);

    internal CRSimPointConstraint(nint address, UnrealContext context) : base(address, context, "CRSimPointConstraint")
    {
    }

    private protected CRSimPointConstraint(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CRSimPointConstraint? Allocate()
    {
        return SdkEnv.AllocateStruct<CRSimPointConstraint>("CRSimPointConstraint");
    }
}
