// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.ControlRig;

public enum ECRSimPointIntegrateType
{
    Verlet = 0,
    SemiExplicitEuler = 1,
    ECRSimPointIntegrateTypeMax = 2
}
