// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class MathRBFInterpolateQuatFloatTarget : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Quat Target =>
        new Palforge.Sdk.Script.CoreUObject.Quat(Address + 0x0, Context);

    public float Value
    {
        get => ReadAt<float>(0x20);
        set => WriteAt(0x20, value);
    }

    internal MathRBFInterpolateQuatFloatTarget(nint address, UnrealContext context) : base(address, context, "MathRBFInterpolateQuatFloat_Target")
    {
    }

    private protected MathRBFInterpolateQuatFloatTarget(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MathRBFInterpolateQuatFloatTarget? Allocate()
    {
        return SdkEnv.AllocateStruct<MathRBFInterpolateQuatFloatTarget>("MathRBFInterpolateQuatFloat_Target");
    }
}
