// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigDispatchPrint : UStructValue
{
    internal RigDispatchPrint(nint address, UnrealContext context) : base(address, context, "RigDispatch_Print")
    {
    }

    private protected RigDispatchPrint(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigDispatchPrint? Allocate()
    {
        return SdkEnv.AllocateStruct<RigDispatchPrint>("RigDispatch_Print");
    }
}
