// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigHierarchyCopyPasteContentPerElement : UStructValue
{
    public Palforge.Sdk.Script.ControlRig.RigElementKey Key =>
        new Palforge.Sdk.Script.ControlRig.RigElementKey(Address + 0x0, Context);

    public string Content
    {
        get => ReadStringAt(0x10);
        set => WriteStringAt(0x10, value);
    }

    public UnrealArray<Palforge.Sdk.Script.ControlRig.RigElementKey> Parents =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.RigElementKey>(this, 0x20, 0xC, "Parents", static (context, element) => new Palforge.Sdk.Script.ControlRig.RigElementKey(element, context), static (context, value) => context.BytesAt(value.Address, 0xC), null);

    public UnrealArray<Palforge.Sdk.Script.ControlRig.RigElementWeight> ParentWeights =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.RigElementWeight>(this, 0x30, 0xC, "ParentWeights", static (context, element) => new Palforge.Sdk.Script.ControlRig.RigElementWeight(element, context), static (context, value) => context.BytesAt(value.Address, 0xC), null);

    public Palforge.Sdk.Script.ControlRig.RigCurrentAndInitialTransform Pose =>
        new Palforge.Sdk.Script.ControlRig.RigCurrentAndInitialTransform(Address + 0x40, Context);

    internal RigHierarchyCopyPasteContentPerElement(nint address, UnrealContext context) : base(address, context, "RigHierarchyCopyPasteContentPerElement")
    {
    }

    private protected RigHierarchyCopyPasteContentPerElement(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigHierarchyCopyPasteContentPerElement? Allocate()
    {
        return SdkEnv.AllocateStruct<RigHierarchyCopyPasteContentPerElement>("RigHierarchyCopyPasteContentPerElement");
    }
}
