// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigTransformElement : UStructValue
{
    public Palforge.Sdk.Script.ControlRig.RigCurrentAndInitialTransform Pose =>
        new Palforge.Sdk.Script.ControlRig.RigCurrentAndInitialTransform(Address + 0xF0, Context);

    public Palforge.Sdk.Script.ControlRig.RigElementKey Key =>
        new Palforge.Sdk.Script.ControlRig.RigElementKey(Address + 0x8, Context);

    public string NameString
    {
        get => ReadStringAt(0x18);
        set => WriteStringAt(0x18, value);
    }

    public int Index
    {
        get => ReadAt<int>(0x28);
        set => WriteAt(0x28, value);
    }

    public int SubIndex
    {
        get => ReadAt<int>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public bool BSelected
    {
        get => ReadBoolAt(0x30, 0xFF);
        set => WriteBoolAt(0x30, 0xFF, value);
    }

    public int CreatedAtInstructionIndex
    {
        get => ReadAt<int>(0x34);
        set => WriteAt(0x34, value);
    }

    internal RigTransformElement(nint address, UnrealContext context) : base(address, context, "RigTransformElement")
    {
    }

    private protected RigTransformElement(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigTransformElement? Allocate()
    {
        return SdkEnv.AllocateStruct<RigTransformElement>("RigTransformElement");
    }
}
