// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathFloatMod : UStructValue
{
    public float A
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public float B
    {
        get => ReadAt<float>(0xC);
        set => WriteAt(0xC, value);
    }

    public float Result
    {
        get => ReadAt<float>(0x10);
        set => WriteAt(0x10, value);
    }

    internal RigUnitMathFloatMod(nint address, UnrealContext context) : base(address, context, "RigUnit_MathFloatMod")
    {
    }

    private protected RigUnitMathFloatMod(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathFloatMod? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathFloatMod>("RigUnit_MathFloatMod");
    }
}
