// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathFloatConstPi : UStructValue
{
    public float Value
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    internal RigUnitMathFloatConstPi(nint address, UnrealContext context) : base(address, context, "RigUnit_MathFloatConstPi")
    {
    }

    private protected RigUnitMathFloatConstPi(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathFloatConstPi? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathFloatConstPi>("RigUnit_MathFloatConstPi");
    }
}
