// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitClampFloat : UStructValue
{
    public float Value
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public float Min
    {
        get => ReadAt<float>(0xC);
        set => WriteAt(0xC, value);
    }

    public float Max
    {
        get => ReadAt<float>(0x10);
        set => WriteAt(0x10, value);
    }

    public float Result
    {
        get => ReadAt<float>(0x14);
        set => WriteAt(0x14, value);
    }

    internal RigUnitClampFloat(nint address, UnrealContext context) : base(address, context, "RigUnit_Clamp_Float")
    {
    }

    private protected RigUnitClampFloat(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitClampFloat? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitClampFloat>("RigUnit_Clamp_Float");
    }
}
