// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitConvertVectorToQuaternion : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector Input =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Quat Result =>
        new Palforge.Sdk.Script.CoreUObject.Quat(Address + 0x20, Context);

    internal RigUnitConvertVectorToQuaternion(nint address, UnrealContext context) : base(address, context, "RigUnit_ConvertVectorToQuaternion")
    {
    }

    private protected RigUnitConvertVectorToQuaternion(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitConvertVectorToQuaternion? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitConvertVectorToQuaternion>("RigUnit_ConvertVectorToQuaternion");
    }
}
