// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitSphereTraceByObjectTypes : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector Start =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector End =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x20, Context);

    public UnrealArray<byte> ObjectTypes =>
        new UnrealArray<byte>(this, 0x38, 0x1, "ObjectTypes", static (context, element) => context.ValueAt<byte>(element), static (context, value) => Bytes(value), null);

    public float Radius
    {
        get => ReadAt<float>(0x48);
        set => WriteAt(0x48, value);
    }

    public bool BHit
    {
        get => ReadBoolAt(0x4C, 0xFF);
        set => WriteBoolAt(0x4C, 0xFF, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector HitLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x50, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector HitNormal =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x68, Context);

    internal RigUnitSphereTraceByObjectTypes(nint address, UnrealContext context) : base(address, context, "RigUnit_SphereTraceByObjectTypes")
    {
    }

    private protected RigUnitSphereTraceByObjectTypes(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitSphereTraceByObjectTypes? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitSphereTraceByObjectTypes>("RigUnit_SphereTraceByObjectTypes");
    }
}
