// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitItemHarmonics : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.ControlRig.RigUnitHarmonicsTargetItem> Targets =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.RigUnitHarmonicsTargetItem>(this, 0x40, 0x10, "Targets", static (context, element) => new Palforge.Sdk.Script.ControlRig.RigUnitHarmonicsTargetItem(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public Palforge.Sdk.Script.CoreUObject.Vector WaveSpeed =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x50, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector WaveFrequency =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x68, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector WaveAmplitude =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x80, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector WaveOffset =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x98, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector WaveNoise =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0xB0, Context);

    public Palforge.Sdk.Script.ControlRig.EControlRigAnimEasingType WaveEase
    {
        get => (Palforge.Sdk.Script.ControlRig.EControlRigAnimEasingType)ReadAt<byte>(0xC8);
        set => WriteAt(0xC8, (byte)value);
    }

    public float WaveMinimum
    {
        get => ReadAt<float>(0xCC);
        set => WriteAt(0xCC, value);
    }

    public float WaveMaximum
    {
        get => ReadAt<float>(0xD0);
        set => WriteAt(0xD0, value);
    }

    public Palforge.Sdk.Script.AnimationCore.EEulerRotationOrder RotationOrder
    {
        get => (Palforge.Sdk.Script.AnimationCore.EEulerRotationOrder)ReadAt<byte>(0xD4);
        set => WriteAt(0xD4, (byte)value);
    }

    public Palforge.Sdk.Script.ControlRig.RigUnitBoneHarmonicsWorkData WorkData =>
        new Palforge.Sdk.Script.ControlRig.RigUnitBoneHarmonicsWorkData(Address + 0xD8, Context);

    public Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext ExecuteContext =>
        new Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext(Address + 0x8, Context);

    internal RigUnitItemHarmonics(nint address, UnrealContext context) : base(address, context, "RigUnit_ItemHarmonics")
    {
    }

    private protected RigUnitItemHarmonics(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitItemHarmonics? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitItemHarmonics>("RigUnit_ItemHarmonics");
    }
}
