// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathVectorIsNearlyEqual : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector A =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector B =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x20, Context);

    public float Tolerance
    {
        get => ReadAt<float>(0x38);
        set => WriteAt(0x38, value);
    }

    public bool Result
    {
        get => ReadBoolAt(0x3C, 0xFF);
        set => WriteBoolAt(0x3C, 0xFF, value);
    }

    internal RigUnitMathVectorIsNearlyEqual(nint address, UnrealContext context) : base(address, context, "RigUnit_MathVectorIsNearlyEqual")
    {
    }

    private protected RigUnitMathVectorIsNearlyEqual(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathVectorIsNearlyEqual? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathVectorIsNearlyEqual>("RigUnit_MathVectorIsNearlyEqual");
    }
}
