// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitAddParent : UStructValue
{
    public Palforge.Sdk.Script.ControlRig.RigElementKey Child =>
        new Palforge.Sdk.Script.ControlRig.RigElementKey(Address + 0x40, Context);

    public Palforge.Sdk.Script.ControlRig.RigElementKey Parent =>
        new Palforge.Sdk.Script.ControlRig.RigElementKey(Address + 0x4C, Context);

    public Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext ExecuteContext =>
        new Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext(Address + 0x8, Context);

    internal RigUnitAddParent(nint address, UnrealContext context) : base(address, context, "RigUnit_AddParent")
    {
    }

    private protected RigUnitAddParent(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitAddParent? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitAddParent>("RigUnit_AddParent");
    }
}
