// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathFloatAdd : UStructValue
{
    public float A
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public float B
    {
        get => ReadAt<float>(0xC);
        set => WriteAt(0xC, value);
    }

    public float Result
    {
        get => ReadAt<float>(0x10);
        set => WriteAt(0x10, value);
    }

    internal RigUnitMathFloatAdd(nint address, UnrealContext context) : base(address, context, "RigUnit_MathFloatAdd")
    {
    }

    private protected RigUnitMathFloatAdd(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathFloatAdd? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathFloatAdd>("RigUnit_MathFloatAdd");
    }
}
