// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitSphereTraceByTraceChannel : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector Start =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector End =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x20, Context);

    public byte TraceChannel
    {
        get => ReadAt<byte>(0x38);
        set => WriteAt(0x38, value);
    }

    public float Radius
    {
        get => ReadAt<float>(0x3C);
        set => WriteAt(0x3C, value);
    }

    public bool BHit
    {
        get => ReadBoolAt(0x40, 0xFF);
        set => WriteBoolAt(0x40, 0xFF, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector HitLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x48, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector HitNormal =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x60, Context);

    internal RigUnitSphereTraceByTraceChannel(nint address, UnrealContext context) : base(address, context, "RigUnit_SphereTraceByTraceChannel")
    {
    }

    private protected RigUnitSphereTraceByTraceChannel(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitSphereTraceByTraceChannel? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitSphereTraceByTraceChannel>("RigUnit_SphereTraceByTraceChannel");
    }
}
