// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitParentConstraint : UStructValue
{
    public Palforge.Sdk.Script.ControlRig.RigElementKey Child =>
        new Palforge.Sdk.Script.ControlRig.RigElementKey(Address + 0x40, Context);

    public bool BMaintainOffset
    {
        get => ReadBoolAt(0x4C, 0xFF);
        set => WriteBoolAt(0x4C, 0xFF, value);
    }

    public Palforge.Sdk.Script.AnimationCore.TransformFilter Filter =>
        new Palforge.Sdk.Script.AnimationCore.TransformFilter(Address + 0x4D, Context);

    public UnrealArray<Palforge.Sdk.Script.ControlRig.ConstraintParent> Parents =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.ConstraintParent>(this, 0x58, 0x10, "Parents", static (context, element) => new Palforge.Sdk.Script.ControlRig.ConstraintParent(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public Palforge.Sdk.Script.ControlRig.RigUnitParentConstraintAdvancedSettings AdvancedSettings =>
        new Palforge.Sdk.Script.ControlRig.RigUnitParentConstraintAdvancedSettings(Address + 0x68, Context);

    public float Weight
    {
        get => ReadAt<float>(0x6C);
        set => WriteAt(0x6C, value);
    }

    public Palforge.Sdk.Script.ControlRig.CachedRigElement ChildCache =>
        new Palforge.Sdk.Script.ControlRig.CachedRigElement(Address + 0x70, Context);

    public UnrealArray<Palforge.Sdk.Script.ControlRig.CachedRigElement> ParentCaches =>
        new UnrealArray<Palforge.Sdk.Script.ControlRig.CachedRigElement>(this, 0x90, 0x20, "ParentCaches", static (context, element) => new Palforge.Sdk.Script.ControlRig.CachedRigElement(element, context), static (context, value) => context.BytesAt(value.Address, 0x20), null);

    public Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext ExecuteContext =>
        new Palforge.Sdk.Script.ControlRig.ControlRigExecuteContext(Address + 0x8, Context);

    internal RigUnitParentConstraint(nint address, UnrealContext context) : base(address, context, "RigUnit_ParentConstraint")
    {
    }

    private protected RigUnitParentConstraint(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitParentConstraint? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitParentConstraint>("RigUnit_ParentConstraint");
    }
}
