// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathFloatDeg : UStructValue
{
    public float Value
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public float Result
    {
        get => ReadAt<float>(0xC);
        set => WriteAt(0xC, value);
    }

    internal RigUnitMathFloatDeg(nint address, UnrealContext context) : base(address, context, "RigUnit_MathFloatDeg")
    {
    }

    private protected RigUnitMathFloatDeg(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathFloatDeg? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathFloatDeg>("RigUnit_MathFloatDeg");
    }
}
