// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitMathVectorMakeRelative : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Vector Global =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Parent =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x20, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Local =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x38, Context);

    internal RigUnitMathVectorMakeRelative(nint address, UnrealContext context) : base(address, context, "RigUnit_MathVectorMakeRelative")
    {
    }

    private protected RigUnitMathVectorMakeRelative(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitMathVectorMakeRelative? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitMathVectorMakeRelative>("RigUnit_MathVectorMakeRelative");
    }
}
