// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ControlRig;

public class RigUnitKalmanTransform : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Transform Value =>
        new Palforge.Sdk.Script.CoreUObject.Transform(Address + 0x10, Context);

    public int BufferSize
    {
        get => ReadAt<int>(0x70);
        set => WriteAt(0x70, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Transform Result =>
        new Palforge.Sdk.Script.CoreUObject.Transform(Address + 0x80, Context);

    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Transform> Buffer =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Transform>(this, 0xE0, 0x60, "Buffer", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Transform(element, context), static (context, value) => context.BytesAt(value.Address, 0x60), null);

    public int LastInsertIndex
    {
        get => ReadAt<int>(0xF0);
        set => WriteAt(0xF0, value);
    }

    internal RigUnitKalmanTransform(nint address, UnrealContext context) : base(address, context, "RigUnit_KalmanTransform")
    {
    }

    private protected RigUnitKalmanTransform(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitKalmanTransform? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitKalmanTransform>("RigUnit_KalmanTransform");
    }
}
