// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AnimationCore;

public class FilterOptionPerAxis : UStructValue
{
    public bool BX
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    public bool BY
    {
        get => ReadBoolAt(0x1, 0xFF);
        set => WriteBoolAt(0x1, 0xFF, value);
    }

    public bool BZ
    {
        get => ReadBoolAt(0x2, 0xFF);
        set => WriteBoolAt(0x2, 0xFF, value);
    }

    internal FilterOptionPerAxis(nint address, UnrealContext context) : base(address, context, "FilterOptionPerAxis")
    {
    }

    private protected FilterOptionPerAxis(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static FilterOptionPerAxis? Allocate()
    {
        return SdkEnv.AllocateStruct<FilterOptionPerAxis>("FilterOptionPerAxis");
    }
}
