// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.LiveLinkComponents;

public class LiveLinkTransformController : Palforge.Sdk.Script.LiveLinkComponents.LiveLinkControllerBase
{
    public Palforge.Sdk.Script.LiveLinkComponents.LiveLinkTransformControllerData TransformData =>
        new Palforge.Sdk.Script.LiveLinkComponents.LiveLinkTransformControllerData(Address + 0x68, Context);

    internal LiveLinkTransformController(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("LiveLinkTransformController");
    }

    public static new LiveLinkTransformController? New(UObject? outer = null)
    {
        return SdkEnv.New("LiveLinkTransformController", outer) as LiveLinkTransformController;
    }

    public static new LiveLinkTransformController? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as LiveLinkTransformController;
    }
}
