// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Synthesis;

public enum EStereoDelaySourceEffect
{
    Normal = 0,
    Cross = 1,
    PingPong = 2,
    Count = 3,
    EStereoDelaySourceEffectMax = 4
}
