// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Synthesis;

public class SourceEffectEQPreset : Palforge.Sdk.Script.Engine.SoundEffectSourcePreset
{
    public Palforge.Sdk.Script.Synthesis.SourceEffectEQSettings Settings =>
        new Palforge.Sdk.Script.Synthesis.SourceEffectEQSettings(Address + 0xA0, Context);

    internal SourceEffectEQPreset(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SourceEffectEQPreset");
    }

    public static new SourceEffectEQPreset? New(UObject? outer = null)
    {
        return SdkEnv.New("SourceEffectEQPreset", outer) as SourceEffectEQPreset;
    }

    public static new SourceEffectEQPreset? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SourceEffectEQPreset;
    }

    public void SetSettings(Palforge.Sdk.Script.Synthesis.SourceEffectEQSettings inSettings)
    {
        Call("SetSettings", SdkEnv.StructBytes(inSettings, 16));
    }
}
