// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Chaos;

public enum EFieldVectorType
{
    VectorLinearForce = 0,
    VectorLinearVelocity = 1,
    VectorAngularVelocity = 2,
    VectorAngularTorque = 3,
    VectorPositionTarget = 4,
    VectorInitialLinearVelocity = 5,
    VectorInitialAngularVelocity = 6,
    VectorLinearImpulse = 7,
    VectorTargetMax = 8,
    VectorMax = 9
}
