// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Chaos;

public class RecordedFrame : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Transform> Transforms =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Transform>(this, 0x0, 0x60, "Transforms", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Transform(element, context), static (context, value) => context.BytesAt(value.Address, 0x60), null);

    public UnrealArray<int> TransformIndices =>
        new UnrealArray<int>(this, 0x10, 0x4, "TransformIndices", static (context, element) => context.ValueAt<int>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<int> PreviousTransformIndices =>
        new UnrealArray<int>(this, 0x20, 0x4, "PreviousTransformIndices", static (context, element) => context.ValueAt<int>(element), static (context, value) => Bytes(value), null);

    public UnrealArray<bool> DisabledFlags =>
        new UnrealArray<bool>(this, 0x30, 0x1, "DisabledFlags", static (context, element) => context.ValueAt<byte>(element) is not 0, static (context, value) => Bytes<byte>(value ? (byte)1 : (byte)0), null);

    public UnrealArray<Palforge.Sdk.Script.Chaos.SolverCollisionData> Collisions =>
        new UnrealArray<Palforge.Sdk.Script.Chaos.SolverCollisionData>(this, 0x40, 0xC0, "Collisions", static (context, element) => new Palforge.Sdk.Script.Chaos.SolverCollisionData(element, context), static (context, value) => context.BytesAt(value.Address, 0xC0), null);

    public UnrealArray<Palforge.Sdk.Script.Chaos.SolverBreakingData> Breakings =>
        new UnrealArray<Palforge.Sdk.Script.Chaos.SolverBreakingData>(this, 0x50, 0x58, "Breakings", static (context, element) => new Palforge.Sdk.Script.Chaos.SolverBreakingData(element, context), static (context, value) => context.BytesAt(value.Address, 0x58), null);

    public UnrealSet<Palforge.Sdk.Script.Chaos.SolverTrailingData> Trailings =>
        new UnrealSet<Palforge.Sdk.Script.Chaos.SolverTrailingData>(this, 0x60, 0x60, "Trailings", static (context, element) => new Palforge.Sdk.Script.Chaos.SolverTrailingData(element, context), static (context, value) => context.BytesAt(value.Address, 0x58), null);

    public float Timestamp
    {
        get => ReadAt<float>(0xB0);
        set => WriteAt(0xB0, value);
    }

    internal RecordedFrame(nint address, UnrealContext context) : base(address, context, "RecordedFrame")
    {
    }

    private protected RecordedFrame(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RecordedFrame? Allocate()
    {
        return SdkEnv.AllocateStruct<RecordedFrame>("RecordedFrame");
    }
}
