// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieRenderPipelineCore;

public class MoviePipelineShotOutputData : UStructValue
{
    public UObject? Shot
    {
        get => ReadWeakAt(0x0);
        set => WriteWeakAt(0x0, value);
    }

    public UnrealMap<Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelinePassIdentifier, Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelineRenderPassOutputData> RenderPassData =>
        new UnrealMap<Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelinePassIdentifier, Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelineRenderPassOutputData>(this, 0x8, 0x38, 0x20, "RenderPassData", static (context, element) => new Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelinePassIdentifier(element, context), static (context, element) => new Palforge.Sdk.Script.MovieRenderPipelineCore.MoviePipelineRenderPassOutputData(element, context), static (context, value) => context.BytesAt(value.Address, 0x20), static (context, value) => context.BytesAt(value.Address, 0x10), null, null);

    internal MoviePipelineShotOutputData(nint address, UnrealContext context) : base(address, context, "MoviePipelineShotOutputData")
    {
    }

    private protected MoviePipelineShotOutputData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MoviePipelineShotOutputData? Allocate()
    {
        return SdkEnv.AllocateStruct<MoviePipelineShotOutputData>("MoviePipelineShotOutputData");
    }
}
