// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.IKRig;

public class IKGoalCreatorInterface : Palforge.Sdk.Script.CoreUObject.Interface
{
    internal IKGoalCreatorInterface(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("IKGoalCreatorInterface");
    }

    public static new IKGoalCreatorInterface? New(UObject? outer = null)
    {
        return SdkEnv.New("IKGoalCreatorInterface", outer) as IKGoalCreatorInterface;
    }

    public static new IKGoalCreatorInterface? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as IKGoalCreatorInterface;
    }
}
