// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.IKRig;

public class RetargetChainMap : UStructValue
{
    public string SourceChain
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public string TargetChain
    {
        get => ReadNameAt(0x8);
        set => WriteNameAt(0x8, value);
    }

    internal RetargetChainMap(nint address, UnrealContext context) : base(address, context, "RetargetChainMap")
    {
    }

    private protected RetargetChainMap(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RetargetChainMap? Allocate()
    {
        return SdkEnv.AllocateStruct<RetargetChainMap>("RetargetChainMap");
    }
}
