// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AnimGraphRuntime;

public class Constraint : UStructValue
{
    public Palforge.Sdk.Script.Engine.BoneReference TargetBone =>
        new Palforge.Sdk.Script.Engine.BoneReference(Address + 0x0, Context);

    public Palforge.Sdk.Script.AnimGraphRuntime.EConstraintOffsetOption OffsetOption
    {
        get => (Palforge.Sdk.Script.AnimGraphRuntime.EConstraintOffsetOption)ReadAt<byte>(0x10);
        set => WriteAt(0x10, (byte)value);
    }

    public Palforge.Sdk.Script.AnimationCore.ETransformConstraintType TransformType
    {
        get => (Palforge.Sdk.Script.AnimationCore.ETransformConstraintType)ReadAt<byte>(0x11);
        set => WriteAt(0x11, (byte)value);
    }

    public Palforge.Sdk.Script.AnimationCore.FilterOptionPerAxis PerAxis =>
        new Palforge.Sdk.Script.AnimationCore.FilterOptionPerAxis(Address + 0x12, Context);

    internal Constraint(nint address, UnrealContext context) : base(address, context, "Constraint")
    {
    }

    private protected Constraint(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static Constraint? Allocate()
    {
        return SdkEnv.AllocateStruct<Constraint>("Constraint");
    }
}
