// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.HoudiniEngineRuntime;

public enum EHoudiniRuntimeSettingsSessionType
{
    HrsstInProcess = 0,
    HrsstSocket = 1,
    HrsstNamedPipe = 2,
    HrsstNone = 3,
    HrsstMax = 4
}
