// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.HoudiniEngineRuntime;

public class HoudiniParameterButtonStrip : Palforge.Sdk.Script.HoudiniEngineRuntime.HoudiniParameter
{
    public UnrealArray<string> Labels =>
        new UnrealArray<string>(this, 0x108, 0x10, "Labels", static (context, element) => context.StringAt(element), static (context, value) => context.StringValueBytes(value), static (context, bytes) => context.ReleaseStringValue(bytes));

    public uint Value
    {
        get => ReadAt<uint>(0x118);
        set => WriteAt(0x118, value);
    }

    public uint DefaultValue
    {
        get => ReadAt<uint>(0x11C);
        set => WriteAt(0x11C, value);
    }

    internal HoudiniParameterButtonStrip(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("HoudiniParameterButtonStrip");
    }

    public static new HoudiniParameterButtonStrip? New(UObject? outer = null)
    {
        return SdkEnv.New("HoudiniParameterButtonStrip", outer) as HoudiniParameterButtonStrip;
    }

    public static new HoudiniParameterButtonStrip? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as HoudiniParameterButtonStrip;
    }
}
