// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.CoreUObject;

public enum ELocalizedTextSourceCategory
{
    Game = 0,
    Engine = 1,
    Editor = 2,
    ELocalizedTextSourceCategoryMax = 3
}
