// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CoreUObject;

public class FallbackStruct : UStructValue
{
    internal FallbackStruct(nint address, UnrealContext context) : base(address, context, "FallbackStruct")
    {
    }

    private protected FallbackStruct(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static FallbackStruct? Allocate()
    {
        return SdkEnv.AllocateStruct<FallbackStruct>("FallbackStruct");
    }
}
