// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CoreUObject;

public class Int32Vector : UStructValue
{
    public int X
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    public int Y
    {
        get => ReadAt<int>(0x4);
        set => WriteAt(0x4, value);
    }

    public int Z
    {
        get => ReadAt<int>(0x8);
        set => WriteAt(0x8, value);
    }

    internal Int32Vector(nint address, UnrealContext context) : base(address, context, "Int32Vector")
    {
    }

    private protected Int32Vector(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static Int32Vector? Allocate()
    {
        return SdkEnv.AllocateStruct<Int32Vector>("Int32Vector");
    }
}
