// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CoreUObject;

public class MulticastInlineDelegatePropertyWrapper : Palforge.Sdk.Script.CoreUObject.MulticastDelegatePropertyWrapper
{
    internal MulticastInlineDelegatePropertyWrapper(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MulticastInlineDelegatePropertyWrapper");
    }

    public static new MulticastInlineDelegatePropertyWrapper? New(UObject? outer = null)
    {
        return SdkEnv.New("MulticastInlineDelegatePropertyWrapper", outer) as MulticastInlineDelegatePropertyWrapper;
    }

    public static new MulticastInlineDelegatePropertyWrapper? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MulticastInlineDelegatePropertyWrapper;
    }
}
