// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CoreUObject;

public class PrimaryAssetId : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.PrimaryAssetType PrimaryAssetType =>
        new Palforge.Sdk.Script.CoreUObject.PrimaryAssetType(Address + 0x0, Context);

    public string PrimaryAssetName
    {
        get => ReadNameAt(0x8);
        set => WriteNameAt(0x8, value);
    }

    internal PrimaryAssetId(nint address, UnrealContext context) : base(address, context, "PrimaryAssetId")
    {
    }

    private protected PrimaryAssetId(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PrimaryAssetId? Allocate()
    {
        return SdkEnv.AllocateStruct<PrimaryAssetId>("PrimaryAssetId");
    }
}
