// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GameplayTasks;

public class GameplayTaskTimeLimitedExecution : Palforge.Sdk.Script.GameplayTasks.GameplayTask
{
    internal GameplayTaskTimeLimitedExecution(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GameplayTask_TimeLimitedExecution");
    }

    public static new GameplayTaskTimeLimitedExecution? New(UObject? outer = null)
    {
        return SdkEnv.New("GameplayTask_TimeLimitedExecution", outer) as GameplayTaskTimeLimitedExecution;
    }

    public static new GameplayTaskTimeLimitedExecution? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GameplayTaskTimeLimitedExecution;
    }
}
