// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GameplayTasks;

public class GameplayTaskResource : UObject
{
    public int ManualResourceID
    {
        get => ReadAt<int>(0x28);
        set => WriteAt(0x28, value);
    }

    public sbyte AutoResourceID
    {
        get => ReadAt<sbyte>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public bool BManuallySetID
    {
        get => ReadBoolAt(0x30, 0x1);
        set => WriteBoolAt(0x30, 0x1, value);
    }

    internal GameplayTaskResource(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("GameplayTaskResource");
    }

    public static GameplayTaskResource? New(UObject? outer = null)
    {
        return SdkEnv.New("GameplayTaskResource", outer) as GameplayTaskResource;
    }

    public static GameplayTaskResource? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as GameplayTaskResource;
    }
}
