// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Foliage;

public class FoliageStatistics : Palforge.Sdk.Script.Engine.BlueprintFunctionLibrary
{
    internal FoliageStatistics(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("FoliageStatistics");
    }

    public static new FoliageStatistics? New(UObject? outer = null)
    {
        return SdkEnv.New("FoliageStatistics", outer) as FoliageStatistics;
    }

    public static new FoliageStatistics? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as FoliageStatistics;
    }

    public static int FoliageOverlappingSphereCount(UObject? worldContextObject, Palforge.Sdk.Script.Engine.StaticMesh? staticMesh, Palforge.Sdk.Script.CoreUObject.Vector centerPosition, float radius)
    {
        return As<int>(SdkEnv.CallStatic("FoliageStatistics", "FoliageOverlappingSphereCount", Bytes<nint>(worldContextObject?.Address ?? 0), Bytes<nint>(staticMesh?.Address ?? 0), SdkEnv.StructBytes(centerPosition, 24), Bytes(radius)));
    }

    public static int FoliageOverlappingBoxCount(UObject? worldContextObject, Palforge.Sdk.Script.Engine.StaticMesh? staticMesh, Palforge.Sdk.Script.CoreUObject.Box box)
    {
        return As<int>(SdkEnv.CallStatic("FoliageStatistics", "FoliageOverlappingBoxCount", Bytes<nint>(worldContextObject?.Address ?? 0), Bytes<nint>(staticMesh?.Address ?? 0), SdkEnv.StructBytes(box, 56)));
    }
}
