// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Umg;

public class Button : Palforge.Sdk.Script.Umg.ContentWidget
{
    public Palforge.Sdk.Script.SlateCore.ButtonStyle WidgetStyle =>
        new Palforge.Sdk.Script.SlateCore.ButtonStyle(Address + 0x170, Context);

    public Palforge.Sdk.Script.CoreUObject.LinearColor ColorAndOpacity =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x560, Context);

    public Palforge.Sdk.Script.CoreUObject.LinearColor BackgroundColor =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x570, Context);

    public byte ClickMethod
    {
        get => ReadAt<byte>(0x580);
        set => WriteAt(0x580, value);
    }

    public byte TouchMethod
    {
        get => ReadAt<byte>(0x581);
        set => WriteAt(0x581, value);
    }

    public byte PressMethod
    {
        get => ReadAt<byte>(0x582);
        set => WriteAt(0x582, value);
    }

    public bool IsFocusable
    {
        get => ReadBoolAt(0x583, 0xFF);
        set => WriteBoolAt(0x583, 0xFF, value);
    }

    internal Button(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("Button");
    }

    public static new Button? New(UObject? outer = null)
    {
        return SdkEnv.New("Button", outer) as Button;
    }

    public static new Button? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as Button;
    }

    public void SetTouchMethod(byte inTouchMethod)
    {
        Call("SetTouchMethod", Bytes(inTouchMethod));
    }

    public void SetStyle(Palforge.Sdk.Script.SlateCore.ButtonStyle inStyle)
    {
        Call("SetStyle", SdkEnv.StructBytes(inStyle, 1008));
    }

    public void SetPressMethod(byte inPressMethod)
    {
        Call("SetPressMethod", Bytes(inPressMethod));
    }

    public void SetColorAndOpacity(Palforge.Sdk.Script.CoreUObject.LinearColor inColorAndOpacity)
    {
        Call("SetColorAndOpacity", SdkEnv.StructBytes(inColorAndOpacity, 16));
    }

    public void SetClickMethod(byte inClickMethod)
    {
        Call("SetClickMethod", Bytes(inClickMethod));
    }

    public void SetBackgroundColor(Palforge.Sdk.Script.CoreUObject.LinearColor inBackgroundColor)
    {
        Call("SetBackgroundColor", SdkEnv.StructBytes(inBackgroundColor, 16));
    }

    public bool IsPressed()
    {
        return As<byte>(Call("IsPressed")) is not 0;
    }
}
