// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Umg;

public class ContentWidget : Palforge.Sdk.Script.Umg.PanelWidget
{
    internal ContentWidget(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("ContentWidget");
    }

    public static new ContentWidget? New(UObject? outer = null)
    {
        return SdkEnv.New("ContentWidget", outer) as ContentWidget;
    }

    public static new ContentWidget? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as ContentWidget;
    }

    public Palforge.Sdk.Script.Umg.PanelSlot? SetContent(Palforge.Sdk.Script.Umg.Widget? content)
    {
        return SdkEnv.Wrap(Call("SetContent", Bytes<nint>(content?.Address ?? 0))) as Palforge.Sdk.Script.Umg.PanelSlot;
    }

    public Palforge.Sdk.Script.Umg.PanelSlot? GetContentSlot()
    {
        return SdkEnv.Wrap(Call("GetContentSlot")) as Palforge.Sdk.Script.Umg.PanelSlot;
    }

    public Palforge.Sdk.Script.Umg.Widget? GetContent()
    {
        return SdkEnv.Wrap(Call("GetContent")) as Palforge.Sdk.Script.Umg.Widget;
    }
}
