// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Umg;

public class RichTextBlockDecorator : UObject
{
    internal RichTextBlockDecorator(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("RichTextBlockDecorator");
    }

    public static RichTextBlockDecorator? New(UObject? outer = null)
    {
        return SdkEnv.New("RichTextBlockDecorator", outer) as RichTextBlockDecorator;
    }

    public static RichTextBlockDecorator? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as RichTextBlockDecorator;
    }
}
