// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.EnhancedInput;

public class InputActionInstance : UStructValue
{
    public Palforge.Sdk.Script.EnhancedInput.InputAction? SourceAction
    {
        get => WrapAt(0x0) as Palforge.Sdk.Script.EnhancedInput.InputAction;
        set => WriteObjectAt(0x0, value);
    }

    public Palforge.Sdk.Script.EnhancedInput.ETriggerEvent TriggerEvent
    {
        get => (Palforge.Sdk.Script.EnhancedInput.ETriggerEvent)ReadAt<byte>(0x13);
        set => WriteAt(0x13, (byte)value);
    }

    public float LastTriggeredWorldTime
    {
        get => ReadAt<float>(0x14);
        set => WriteAt(0x14, value);
    }

    public UnrealArray<Palforge.Sdk.Script.EnhancedInput.InputTrigger?> Triggers =>
        new UnrealArray<Palforge.Sdk.Script.EnhancedInput.InputTrigger?>(this, 0x18, 0x8, "Triggers", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.EnhancedInput.InputTrigger, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UnrealArray<Palforge.Sdk.Script.EnhancedInput.InputModifier?> Modifiers =>
        new UnrealArray<Palforge.Sdk.Script.EnhancedInput.InputModifier?>(this, 0x28, 0x8, "Modifiers", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.EnhancedInput.InputModifier, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public float ElapsedProcessedTime
    {
        get => ReadAt<float>(0x58);
        set => WriteAt(0x58, value);
    }

    public float ElapsedTriggeredTime
    {
        get => ReadAt<float>(0x5C);
        set => WriteAt(0x5C, value);
    }

    internal InputActionInstance(nint address, UnrealContext context) : base(address, context, "InputActionInstance")
    {
    }

    private protected InputActionInstance(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static InputActionInstance? Allocate()
    {
        return SdkEnv.AllocateStruct<InputActionInstance>("InputActionInstance");
    }
}
