// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Party;

public class SocialChatChannel : UObject
{
    internal SocialChatChannel(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("SocialChatChannel");
    }

    public static SocialChatChannel? New(UObject? outer = null)
    {
        return SdkEnv.New("SocialChatChannel", outer) as SocialChatChannel;
    }

    public static SocialChatChannel? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as SocialChatChannel;
    }
}
