// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class AISenseConfig : UObject
{
    public Palforge.Sdk.Script.CoreUObject.Color DebugColor =>
        new Palforge.Sdk.Script.CoreUObject.Color(Address + 0x28, Context);

    public float MaxAge
    {
        get => ReadAt<float>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public bool BStartsEnabled
    {
        get => ReadBoolAt(0x30, 0x1);
        set => WriteBoolAt(0x30, 0x1, value);
    }

    internal AISenseConfig(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AISenseConfig");
    }

    public static AISenseConfig? New(UObject? outer = null)
    {
        return SdkEnv.New("AISenseConfig", outer) as AISenseConfig;
    }

    public static AISenseConfig? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AISenseConfig;
    }
}
