// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class AIStimulus : UStructValue
{
    public float Age
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public float ExpirationAge
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    public float Strength
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector StimulusLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x10, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector ReceiverLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x28, Context);

    public string Tag
    {
        get => ReadNameAt(0x40);
        set => WriteNameAt(0x40, value);
    }

    public bool BSuccessfullySensed
    {
        get => ReadBoolAt(0x54, 0x2);
        set => WriteBoolAt(0x54, 0x2, value);
    }

    internal AIStimulus(nint address, UnrealContext context) : base(address, context, "AIStimulus")
    {
    }

    private protected AIStimulus(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static AIStimulus? Allocate()
    {
        return SdkEnv.AllocateStruct<AIStimulus>("AIStimulus");
    }
}
