// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class BTServiceBlueprintBase : Palforge.Sdk.Script.AIModule.BTService
{
    public Palforge.Sdk.Script.AIModule.AIController? AIOwner
    {
        get => WrapAt(0x70) as Palforge.Sdk.Script.AIModule.AIController;
        set => WriteObjectAt(0x70, value);
    }

    public Palforge.Sdk.Script.Engine.Actor? ActorOwner
    {
        get => WrapAt(0x78) as Palforge.Sdk.Script.Engine.Actor;
        set => WriteObjectAt(0x78, value);
    }

    public bool BShowPropertyDetails
    {
        get => ReadBoolAt(0x90, 0x1);
        set => WriteBoolAt(0x90, 0x1, value);
    }

    public bool BShowEventDetails
    {
        get => ReadBoolAt(0x90, 0x2);
        set => WriteBoolAt(0x90, 0x2, value);
    }

    internal BTServiceBlueprintBase(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("BTService_BlueprintBase");
    }

    public static new BTServiceBlueprintBase? New(UObject? outer = null)
    {
        return SdkEnv.New("BTService_BlueprintBase", outer) as BTServiceBlueprintBase;
    }

    public static new BTServiceBlueprintBase? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as BTServiceBlueprintBase;
    }

    public void ReceiveTickAI(Palforge.Sdk.Script.AIModule.AIController? ownerController, Palforge.Sdk.Script.Engine.Pawn? controlledPawn, float deltaSeconds)
    {
        Call("ReceiveTickAI", Bytes<nint>(ownerController?.Address ?? 0), Bytes<nint>(controlledPawn?.Address ?? 0), Bytes(deltaSeconds));
    }

    public void ReceiveTick(Palforge.Sdk.Script.Engine.Actor? ownerActor, float deltaSeconds)
    {
        Call("ReceiveTick", Bytes<nint>(ownerActor?.Address ?? 0), Bytes(deltaSeconds));
    }

    public void ReceiveSearchStartAI(Palforge.Sdk.Script.AIModule.AIController? ownerController, Palforge.Sdk.Script.Engine.Pawn? controlledPawn)
    {
        Call("ReceiveSearchStartAI", Bytes<nint>(ownerController?.Address ?? 0), Bytes<nint>(controlledPawn?.Address ?? 0));
    }

    public void ReceiveSearchStart(Palforge.Sdk.Script.Engine.Actor? ownerActor)
    {
        Call("ReceiveSearchStart", Bytes<nint>(ownerActor?.Address ?? 0));
    }

    public void ReceiveDeactivationAI(Palforge.Sdk.Script.AIModule.AIController? ownerController, Palforge.Sdk.Script.Engine.Pawn? controlledPawn)
    {
        Call("ReceiveDeactivationAI", Bytes<nint>(ownerController?.Address ?? 0), Bytes<nint>(controlledPawn?.Address ?? 0));
    }

    public void ReceiveDeactivation(Palforge.Sdk.Script.Engine.Actor? ownerActor)
    {
        Call("ReceiveDeactivation", Bytes<nint>(ownerActor?.Address ?? 0));
    }

    public void ReceiveActivationAI(Palforge.Sdk.Script.AIModule.AIController? ownerController, Palforge.Sdk.Script.Engine.Pawn? controlledPawn)
    {
        Call("ReceiveActivationAI", Bytes<nint>(ownerController?.Address ?? 0), Bytes<nint>(controlledPawn?.Address ?? 0));
    }

    public void ReceiveActivation(Palforge.Sdk.Script.Engine.Actor? ownerActor)
    {
        Call("ReceiveActivation", Bytes<nint>(ownerActor?.Address ?? 0));
    }

    public bool IsServiceActive()
    {
        return As<byte>(Call("IsServiceActive")) is not 0;
    }
}
