// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class BTTaskMakeNoise : Palforge.Sdk.Script.AIModule.BTTaskNode
{
    public float Loudnes
    {
        get => ReadAt<float>(0x70);
        set => WriteAt(0x70, value);
    }

    internal BTTaskMakeNoise(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("BTTask_MakeNoise");
    }

    public static new BTTaskMakeNoise? New(UObject? outer = null)
    {
        return SdkEnv.New("BTTask_MakeNoise", outer) as BTTaskMakeNoise;
    }

    public static new BTTaskMakeNoise? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as BTTaskMakeNoise;
    }
}
