// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class CrowdFollowingComponent : Palforge.Sdk.Script.AIModule.PathFollowingComponent
{
    public Palforge.Sdk.Script.CoreUObject.Vector CrowdAgentMoveDirection =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x2D0, Context);

    internal CrowdFollowingComponent(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CrowdFollowingComponent");
    }

    public static new CrowdFollowingComponent? New(UObject? outer = null)
    {
        return SdkEnv.New("CrowdFollowingComponent", outer) as CrowdFollowingComponent;
    }

    public static new CrowdFollowingComponent? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CrowdFollowingComponent;
    }

    public void SuspendCrowdSteering(bool bSuspend)
    {
        Call("SuspendCrowdSteering", Bytes<byte>(bSuspend ? (byte)1 : (byte)0));
    }
}
