// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.AIModule;

public enum EEnvTestWeight
{
    None = 0,
    Square = 1,
    Inverse = 2,
    Unused = 3,
    Constant = 4,
    Skip = 5,
    EEnvTestWeightMax = 6
}
