// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class EnvQueryTestOverlap : Palforge.Sdk.Script.AIModule.EnvQueryTest
{
    public Palforge.Sdk.Script.AIModule.EnvOverlapData OverlapData =>
        new Palforge.Sdk.Script.AIModule.EnvOverlapData(Address + 0x1F8, Context);

    internal EnvQueryTestOverlap(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("EnvQueryTest_Overlap");
    }

    public static new EnvQueryTestOverlap? New(UObject? outer = null)
    {
        return SdkEnv.New("EnvQueryTest_Overlap", outer) as EnvQueryTestOverlap;
    }

    public static new EnvQueryTestOverlap? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as EnvQueryTestOverlap;
    }
}
