// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AIModule;

public class PawnAction : UObject
{
    public Palforge.Sdk.Script.AIModule.PawnAction? ChildAction
    {
        get => WrapAt(0x28) as Palforge.Sdk.Script.AIModule.PawnAction;
        set => WriteObjectAt(0x28, value);
    }

    public Palforge.Sdk.Script.AIModule.PawnAction? ParentAction
    {
        get => WrapAt(0x30) as Palforge.Sdk.Script.AIModule.PawnAction;
        set => WriteObjectAt(0x30, value);
    }

    public Palforge.Sdk.Script.AIModule.PawnActionsComponent? OwnerComponent
    {
        get => WrapAt(0x38) as Palforge.Sdk.Script.AIModule.PawnActionsComponent;
        set => WriteObjectAt(0x38, value);
    }

    public UObject? Instigator
    {
        get => WrapAt(0x40);
        set => WriteObjectAt(0x40, value);
    }

    public Palforge.Sdk.Script.AIModule.BrainComponent? BrainComp
    {
        get => WrapAt(0x48) as Palforge.Sdk.Script.AIModule.BrainComponent;
        set => WriteObjectAt(0x48, value);
    }

    public bool BAllowNewSameClassInstance
    {
        get => ReadBoolAt(0x80, 0x1);
        set => WriteBoolAt(0x80, 0x1, value);
    }

    public bool BReplaceActiveSameClassInstance
    {
        get => ReadBoolAt(0x80, 0x2);
        set => WriteBoolAt(0x80, 0x2, value);
    }

    public bool BShouldPauseMovement
    {
        get => ReadBoolAt(0x80, 0x4);
        set => WriteBoolAt(0x80, 0x4, value);
    }

    public bool BAlwaysNotifyOnFinished
    {
        get => ReadBoolAt(0x80, 0x8);
        set => WriteBoolAt(0x80, 0x8, value);
    }

    public bool BDoParallelTick
    {
        get => ReadBoolAt(0x80, 0x10);
        set => WriteBoolAt(0x80, 0x10, value);
    }

    internal PawnAction(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("PawnAction");
    }

    public static PawnAction? New(UObject? outer = null)
    {
        return SdkEnv.New("PawnAction", outer) as PawnAction;
    }

    public static PawnAction? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as PawnAction;
    }

    public byte GetActionPriority()
    {
        return As<byte>(Call("GetActionPriority"));
    }

    public void Finish(byte withResult)
    {
        Call("Finish", Bytes(withResult));
    }

    public static Palforge.Sdk.Script.AIModule.PawnAction? CreateActionInstance(UObject? worldContextObject, UObject? actionClass)
    {
        return SdkEnv.Wrap(SdkEnv.CallStatic("PawnAction", "CreateActionInstance", Bytes<nint>(worldContextObject?.Address ?? 0), Bytes<nint>(actionClass?.Address ?? 0))) as Palforge.Sdk.Script.AIModule.PawnAction;
    }
}
