// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GameFeatures;

public class GameFeatureComponentEntry : UStructValue
{
    public string ActorClass
    {
        get => ReadSoftPathAt(0x0);
        set => WriteSoftPathAt(0x0, value);
    }

    public string ComponentClass
    {
        get => ReadSoftPathAt(0x30);
        set => WriteSoftPathAt(0x30, value);
    }

    public bool BClientComponent
    {
        get => ReadBoolAt(0x60, 0x1);
        set => WriteBoolAt(0x60, 0x1, value);
    }

    public bool BServerComponent
    {
        get => ReadBoolAt(0x60, 0x2);
        set => WriteBoolAt(0x60, 0x2, value);
    }

    internal GameFeatureComponentEntry(nint address, UnrealContext context) : base(address, context, "GameFeatureComponentEntry")
    {
    }

    private protected GameFeatureComponentEntry(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static GameFeatureComponentEntry? Allocate()
    {
        return SdkEnv.AllocateStruct<GameFeatureComponentEntry>("GameFeatureComponentEntry");
    }
}
