// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MovieScene;

public enum EMovieScenePlayerStatus
{
    Stopped = 0,
    Playing = 1,
    Scrubbing = 2,
    Jumping = 3,
    Stepping = 4,
    Paused = 5,
    Max = 6
}
