// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MovieScene;

public enum EMovieSceneBlendType
{
    Invalid = 0,
    Absolute = 1,
    Additive = 2,
    Relative = 4,
    AdditiveFromBase = 8,
    EMovieSceneBlendTypeMax = 9
}
