// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneSequenceCompilerMaskStruct : UStructValue
{
    public bool BHierarchy
    {
        get => ReadBoolAt(0x0, 0x1);
        set => WriteBoolAt(0x0, 0x1, value);
    }

    public bool BEvaluationTemplate
    {
        get => ReadBoolAt(0x0, 0x2);
        set => WriteBoolAt(0x0, 0x2, value);
    }

    public bool BEvaluationTemplateField
    {
        get => ReadBoolAt(0x0, 0x4);
        set => WriteBoolAt(0x0, 0x4, value);
    }

    public bool BEntityComponentField
    {
        get => ReadBoolAt(0x0, 0x8);
        set => WriteBoolAt(0x0, 0x8, value);
    }

    internal MovieSceneSequenceCompilerMaskStruct(nint address, UnrealContext context) : base(address, context, "MovieSceneSequenceCompilerMaskStruct")
    {
    }

    private protected MovieSceneSequenceCompilerMaskStruct(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneSequenceCompilerMaskStruct? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneSequenceCompilerMaskStruct>("MovieSceneSequenceCompilerMaskStruct");
    }
}
