// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneSequence : Palforge.Sdk.Script.MovieScene.MovieSceneSignedObject
{
    public Palforge.Sdk.Script.MovieScene.MovieSceneCompiledData? CompiledData
    {
        get => WrapAt(0x58) as Palforge.Sdk.Script.MovieScene.MovieSceneCompiledData;
        set => WriteObjectAt(0x58, value);
    }

    public Palforge.Sdk.Script.MovieScene.EMovieSceneCompletionMode DefaultCompletionMode
    {
        get => (Palforge.Sdk.Script.MovieScene.EMovieSceneCompletionMode)ReadAt<byte>(0x60);
        set => WriteAt(0x60, (byte)value);
    }

    public bool BParentContextsAreSignificant
    {
        get => ReadBoolAt(0x61, 0xFF);
        set => WriteBoolAt(0x61, 0xFF, value);
    }

    public bool BPlayableDirectly
    {
        get => ReadBoolAt(0x62, 0xFF);
        set => WriteBoolAt(0x62, 0xFF, value);
    }

    public Palforge.Sdk.Script.MovieScene.EMovieSceneSequenceFlags SequenceFlags
    {
        get => (Palforge.Sdk.Script.MovieScene.EMovieSceneSequenceFlags)ReadAt<byte>(0x63);
        set => WriteAt(0x63, (byte)value);
    }

    internal MovieSceneSequence(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneSequence");
    }

    public static new MovieSceneSequence? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneSequence", outer) as MovieSceneSequence;
    }

    public static new MovieSceneSequence? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneSequence;
    }

    public Palforge.Sdk.Script.MovieScene.MovieSceneTimecodeSource? GetEarliestTimecodeSource()
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.MovieScene.MovieSceneTimecodeSource>(this, "GetEarliestTimecodeSource", "MovieSceneTimecodeSource");
    }

    public Palforge.Sdk.Script.MovieScene.MovieSceneObjectBindingID? FindBindingByTag(string inBindingName)
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.MovieScene.MovieSceneObjectBindingID>(this, "FindBindingByTag", "MovieSceneObjectBindingID", SdkEnv.NameBytes(inBindingName));
    }
}
