// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneTrackInstanceInstantiator : Palforge.Sdk.Script.MovieScene.MovieSceneEntityInstantiatorSystem
{
    internal MovieSceneTrackInstanceInstantiator(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneTrackInstanceInstantiator");
    }

    public static new MovieSceneTrackInstanceInstantiator? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneTrackInstanceInstantiator", outer) as MovieSceneTrackInstanceInstantiator;
    }

    public static new MovieSceneTrackInstanceInstantiator? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneTrackInstanceInstantiator;
    }
}
