// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneEvaluationFieldEntityKey : UStructValue
{
    public UObject? EntityOwner
    {
        get => ReadWeakAt(0x0);
        set => WriteWeakAt(0x0, value);
    }

    public uint EntityID
    {
        get => ReadAt<uint>(0x8);
        set => WriteAt(0x8, value);
    }

    internal MovieSceneEvaluationFieldEntityKey(nint address, UnrealContext context) : base(address, context, "MovieSceneEvaluationFieldEntityKey")
    {
    }

    private protected MovieSceneEvaluationFieldEntityKey(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneEvaluationFieldEntityKey? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneEvaluationFieldEntityKey>("MovieSceneEvaluationFieldEntityKey");
    }
}
