// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneBindingProxy : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Guid BindingId =>
        new Palforge.Sdk.Script.CoreUObject.Guid(Address + 0x0, Context);

    public Palforge.Sdk.Script.MovieScene.MovieSceneSequence? Sequence
    {
        get => WrapAt(0x10) as Palforge.Sdk.Script.MovieScene.MovieSceneSequence;
        set => WriteObjectAt(0x10, value);
    }

    internal MovieSceneBindingProxy(nint address, UnrealContext context) : base(address, context, "MovieSceneBindingProxy")
    {
    }

    private protected MovieSceneBindingProxy(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneBindingProxy? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneBindingProxy>("MovieSceneBindingProxy");
    }
}
