// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieScene;

public class MovieSceneTrackIdentifier : UStructValue
{
    public uint Value
    {
        get => ReadAt<uint>(0x0);
        set => WriteAt(0x0, value);
    }

    internal MovieSceneTrackIdentifier(nint address, UnrealContext context) : base(address, context, "MovieSceneTrackIdentifier")
    {
    }

    private protected MovieSceneTrackIdentifier(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneTrackIdentifier? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneTrackIdentifier>("MovieSceneTrackIdentifier");
    }
}
