// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MeshModelingTools;

public class CSGMeshesToolBuilder : Palforge.Sdk.Script.ModelingComponents.BaseCreateFromSelectedToolBuilder
{
    internal CSGMeshesToolBuilder(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CSGMeshesToolBuilder");
    }

    public static new CSGMeshesToolBuilder? New(UObject? outer = null)
    {
        return SdkEnv.New("CSGMeshesToolBuilder", outer) as CSGMeshesToolBuilder;
    }

    public static new CSGMeshesToolBuilder? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CSGMeshesToolBuilder;
    }
}
