// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Niagara;

public enum ENiagaraDebugPlaybackMode
{
    Play = 0,
    Loop = 1,
    Paused = 2,
    Step = 3,
    ENiagaraDebugPlaybackModeMax = 4
}
