// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Niagara;

public enum ENiagaraModuleDependencyScriptConstraint
{
    SameScript = 0,
    AllScripts = 1,
    ENiagaraModuleDependencyScriptConstraintMax = 2
}
