// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.Niagara;

public enum ENiagaraCVarConditionResponse
{
    None = 0,
    Enable = 1,
    Disable = 2,
    ENiagaraCVarConditionResponseMax = 3
}
