// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class MovieSceneNiagaraSystemSpawnSection : Palforge.Sdk.Script.MovieScene.MovieSceneSection
{
    public Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionStartBehavior SectionStartBehavior
    {
        get => (Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionStartBehavior)ReadAt<int>(0xF0);
        set => WriteAt(0xF0, (int)value);
    }

    public Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionEvaluateBehavior SectionEvaluateBehavior
    {
        get => (Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionEvaluateBehavior)ReadAt<int>(0xF4);
        set => WriteAt(0xF4, (int)value);
    }

    public Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionEndBehavior SectionEndBehavior
    {
        get => (Palforge.Sdk.Script.Niagara.ENiagaraSystemSpawnSectionEndBehavior)ReadAt<int>(0xF8);
        set => WriteAt(0xF8, (int)value);
    }

    public Palforge.Sdk.Script.Niagara.ENiagaraAgeUpdateMode AgeUpdateMode
    {
        get => (Palforge.Sdk.Script.Niagara.ENiagaraAgeUpdateMode)ReadAt<byte>(0xFC);
        set => WriteAt(0xFC, (byte)value);
    }

    public bool BAllowScalability
    {
        get => ReadBoolAt(0xFD, 0xFF);
        set => WriteBoolAt(0xFD, 0xFF, value);
    }

    internal MovieSceneNiagaraSystemSpawnSection(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneNiagaraSystemSpawnSection");
    }

    public static new MovieSceneNiagaraSystemSpawnSection? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneNiagaraSystemSpawnSection", outer) as MovieSceneNiagaraSystemSpawnSection;
    }

    public static new MovieSceneNiagaraSystemSpawnSection? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneNiagaraSystemSpawnSection;
    }
}
