// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraComponentPropertyBinding : UStructValue
{
    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding AttributeBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x0, Context);

    public string PropertyName
    {
        get => ReadNameAt(0x58);
        set => WriteNameAt(0x58, value);
    }

    public Palforge.Sdk.Script.Niagara.NiagaraTypeDefinition PropertyType =>
        new Palforge.Sdk.Script.Niagara.NiagaraTypeDefinition(Address + 0x60, Context);

    public string MetadataSetterName
    {
        get => ReadNameAt(0x70);
        set => WriteNameAt(0x70, value);
    }

    public UnrealMap<string, string> PropertySetterParameterDefaults =>
        new UnrealMap<string, string>(this, 0x78, 0x28, 0x10, "PropertySetterParameterDefaults", static (context, element) => context.StringAt(element), static (context, element) => context.StringAt(element), static (context, value) => context.StringValueBytes(value), static (context, value) => context.StringValueBytes(value), static (context, bytes) => context.ReleaseStringValue(bytes), static (context, bytes) => context.ReleaseStringValue(bytes));

    internal NiagaraComponentPropertyBinding(nint address, UnrealContext context) : base(address, context, "NiagaraComponentPropertyBinding")
    {
    }

    private protected NiagaraComponentPropertyBinding(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NiagaraComponentPropertyBinding? Allocate()
    {
        return SdkEnv.AllocateStruct<NiagaraComponentPropertyBinding>("NiagaraComponentPropertyBinding");
    }
}
