// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraTypeDefinitionHandle : UStructValue
{
    public int RegisteredTypeIndex
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    internal NiagaraTypeDefinitionHandle(nint address, UnrealContext context) : base(address, context, "NiagaraTypeDefinitionHandle")
    {
    }

    private protected NiagaraTypeDefinitionHandle(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NiagaraTypeDefinitionHandle? Allocate()
    {
        return SdkEnv.AllocateStruct<NiagaraTypeDefinitionHandle>("NiagaraTypeDefinitionHandle");
    }
}
