// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraSimCacheVariable : UStructValue
{
    public Palforge.Sdk.Script.Niagara.NiagaraVariableBase Variable =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableBase(Address + 0x0, Context);

    public ushort FloatOffset
    {
        get => ReadAt<ushort>(0xC);
        set => WriteAt(0xC, value);
    }

    public ushort FloatCount
    {
        get => ReadAt<ushort>(0xE);
        set => WriteAt(0xE, value);
    }

    public ushort HalfOffset
    {
        get => ReadAt<ushort>(0x10);
        set => WriteAt(0x10, value);
    }

    public ushort HalfCount
    {
        get => ReadAt<ushort>(0x12);
        set => WriteAt(0x12, value);
    }

    public ushort Int32Offset
    {
        get => ReadAt<ushort>(0x14);
        set => WriteAt(0x14, value);
    }

    public ushort Int32Count
    {
        get => ReadAt<ushort>(0x16);
        set => WriteAt(0x16, value);
    }

    internal NiagaraSimCacheVariable(nint address, UnrealContext context) : base(address, context, "NiagaraSimCacheVariable")
    {
    }

    private protected NiagaraSimCacheVariable(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NiagaraSimCacheVariable? Allocate()
    {
        return SdkEnv.AllocateStruct<NiagaraSimCacheVariable>("NiagaraSimCacheVariable");
    }
}
