// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraPreviewAxisInterpParamVector : Palforge.Sdk.Script.Niagara.NiagaraPreviewAxisInterpParamBase
{
    public Palforge.Sdk.Script.CoreUObject.Vector Min =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x38, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Max =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x50, Context);

    internal NiagaraPreviewAxisInterpParamVector(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraPreviewAxis_InterpParamVector");
    }

    public static new NiagaraPreviewAxisInterpParamVector? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraPreviewAxis_InterpParamVector", outer) as NiagaraPreviewAxisInterpParamVector;
    }

    public static new NiagaraPreviewAxisInterpParamVector? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraPreviewAxisInterpParamVector;
    }
}
