// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraComponentRendererProperties : Palforge.Sdk.Script.Niagara.NiagaraRendererProperties
{
    public UObject? ComponentType
    {
        get => WrapAt(0xE0);
        set => WriteObjectAt(0xE0, value);
    }

    public uint ComponentCountLimit
    {
        get => ReadAt<uint>(0xE8);
        set => WriteAt(0xE8, value);
    }

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding EnabledBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0xF0, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding RendererVisibilityTagBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x148, Context);

    public bool BAssignComponentsOnParticleID
    {
        get => ReadBoolAt(0x1A0, 0xFF);
        set => WriteBoolAt(0x1A0, 0xFF, value);
    }

    public bool BCreateComponentFirstParticleFrame
    {
        get => ReadBoolAt(0x1A1, 0xFF);
        set => WriteBoolAt(0x1A1, 0xFF, value);
    }

    public bool BOnlyActivateNewlyAquiredComponents
    {
        get => ReadBoolAt(0x1A2, 0xFF);
        set => WriteBoolAt(0x1A2, 0xFF, value);
    }

    public int RendererVisibility
    {
        get => ReadAt<int>(0x1A4);
        set => WriteAt(0x1A4, value);
    }

    public Palforge.Sdk.Script.Engine.SceneComponent? TemplateComponent
    {
        get => WrapAt(0x1A8) as Palforge.Sdk.Script.Engine.SceneComponent;
        set => WriteObjectAt(0x1A8, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraComponentPropertyBinding> PropertyBindings =>
        new UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraComponentPropertyBinding>(this, 0x1B0, 0xC8, "PropertyBindings", static (context, element) => new Palforge.Sdk.Script.Niagara.NiagaraComponentPropertyBinding(element, context), static (context, value) => context.BytesAt(value.Address, 0xC8), null);

    internal NiagaraComponentRendererProperties(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraComponentRendererProperties");
    }

    public static new NiagaraComponentRendererProperties? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraComponentRendererProperties", outer) as NiagaraComponentRendererProperties;
    }

    public static new NiagaraComponentRendererProperties? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraComponentRendererProperties;
    }
}
