// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraBakerOutput : UObject
{
    public string OutputName
    {
        get => ReadStringAt(0x28);
        set => WriteStringAt(0x28, value);
    }

    internal NiagaraBakerOutput(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraBakerOutput");
    }

    public static NiagaraBakerOutput? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraBakerOutput", outer) as NiagaraBakerOutput;
    }

    public static NiagaraBakerOutput? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraBakerOutput;
    }
}
