// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraDataInterfaceVector4Curve : Palforge.Sdk.Script.Niagara.NiagaraDataInterfaceCurveBase
{
    public Palforge.Sdk.Script.Engine.RichCurve XCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0x70, Context);

    public Palforge.Sdk.Script.Engine.RichCurve YCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0xF0, Context);

    public Palforge.Sdk.Script.Engine.RichCurve ZCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0x170, Context);

    public Palforge.Sdk.Script.Engine.RichCurve WCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0x1F0, Context);

    internal NiagaraDataInterfaceVector4Curve(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraDataInterfaceVector4Curve");
    }

    public static new NiagaraDataInterfaceVector4Curve? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraDataInterfaceVector4Curve", outer) as NiagaraDataInterfaceVector4Curve;
    }

    public static new NiagaraDataInterfaceVector4Curve? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraDataInterfaceVector4Curve;
    }
}
