// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraStatScope : UStructValue
{
    public string FullName
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public string FriendlyName
    {
        get => ReadNameAt(0x8);
        set => WriteNameAt(0x8, value);
    }

    internal NiagaraStatScope(nint address, UnrealContext context) : base(address, context, "NiagaraStatScope")
    {
    }

    private protected NiagaraStatScope(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static NiagaraStatScope? Allocate()
    {
        return SdkEnv.AllocateStruct<NiagaraStatScope>("NiagaraStatScope");
    }
}
