// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraBakerSettings : UObject
{
    public float StartSeconds
    {
        get => ReadAt<float>(0x28);
        set => WriteAt(0x28, value);
    }

    public float DurationSeconds
    {
        get => ReadAt<float>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public int FramesPerSecond
    {
        get => ReadAt<int>(0x30);
        set => WriteAt(0x30, value);
    }

    public bool BPreviewLooping
    {
        get => ReadBoolAt(0x34, 0x1);
        set => WriteBoolAt(0x34, 0x1, value);
    }

    public Palforge.Sdk.Script.CoreUObject.IntPoint FramesPerDimension =>
        new Palforge.Sdk.Script.CoreUObject.IntPoint(Address + 0x38, Context);

    public UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerOutput?> Outputs =>
        new UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerOutput?>(this, 0x40, 0x8, "Outputs", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Niagara.NiagaraBakerOutput, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerCameraSettings> CameraSettings =>
        new UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerCameraSettings>(this, 0x50, 0x50, "CameraSettings", static (context, element) => new Palforge.Sdk.Script.Niagara.NiagaraBakerCameraSettings(element, context), static (context, value) => context.BytesAt(value.Address, 0x50), null);

    public int CurrentCameraIndex
    {
        get => ReadAt<int>(0x60);
        set => WriteAt(0x60, value);
    }

    public string BakeQualityLevel
    {
        get => ReadNameAt(0x64);
        set => WriteNameAt(0x64, value);
    }

    public bool BRenderComponentOnly
    {
        get => ReadBoolAt(0x6C, 0x1);
        set => WriteBoolAt(0x6C, 0x1, value);
    }

    public UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerTextureSettings> OutputTextures =>
        new UnrealArray<Palforge.Sdk.Script.Niagara.NiagaraBakerTextureSettings>(this, 0x70, 0x40, "OutputTextures", static (context, element) => new Palforge.Sdk.Script.Niagara.NiagaraBakerTextureSettings(element, context), static (context, value) => context.BytesAt(value.Address, 0x40), null);

    public Palforge.Sdk.Script.Niagara.ENiagaraBakerViewMode CameraViewportMode
    {
        get => (Palforge.Sdk.Script.Niagara.ENiagaraBakerViewMode)ReadAt<int>(0x80);
        set => WriteAt(0x80, (int)value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector CameraViewportLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x88, Context);

    public Palforge.Sdk.Script.CoreUObject.Rotator CameraViewportRotation =>
        new Palforge.Sdk.Script.CoreUObject.Rotator(Address + 0x130, Context);

    public float CameraOrbitDistance
    {
        get => ReadAt<float>(0x1D8);
        set => WriteAt(0x1D8, value);
    }

    public float CameraFOV
    {
        get => ReadAt<float>(0x1DC);
        set => WriteAt(0x1DC, value);
    }

    public float CameraOrthoWidth
    {
        get => ReadAt<float>(0x1E0);
        set => WriteAt(0x1E0, value);
    }

    public bool BUseCameraAspectRatio
    {
        get => ReadBoolAt(0x1E4, 0x1);
        set => WriteBoolAt(0x1E4, 0x1, value);
    }

    public float CameraAspectRatio
    {
        get => ReadAt<float>(0x1E8);
        set => WriteAt(0x1E8, value);
    }

    internal NiagaraBakerSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraBakerSettings");
    }

    public static NiagaraBakerSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraBakerSettings", outer) as NiagaraBakerSettings;
    }

    public static NiagaraBakerSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraBakerSettings;
    }
}
