// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraPreviewAxisInterpParamVector4 : Palforge.Sdk.Script.Niagara.NiagaraPreviewAxisInterpParamBase
{
    public Palforge.Sdk.Script.CoreUObject.Vector4 Min =>
        new Palforge.Sdk.Script.CoreUObject.Vector4(Address + 0x40, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector4 Max =>
        new Palforge.Sdk.Script.CoreUObject.Vector4(Address + 0x60, Context);

    internal NiagaraPreviewAxisInterpParamVector4(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraPreviewAxis_InterpParamVector4");
    }

    public static new NiagaraPreviewAxisInterpParamVector4? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraPreviewAxis_InterpParamVector4", outer) as NiagaraPreviewAxisInterpParamVector4;
    }

    public static new NiagaraPreviewAxisInterpParamVector4? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraPreviewAxisInterpParamVector4;
    }
}
