// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Niagara;

public class NiagaraLightRendererProperties : Palforge.Sdk.Script.Niagara.NiagaraRendererProperties
{
    public bool BUseInverseSquaredFalloff
    {
        get => ReadBoolAt(0xE0, 0x1);
        set => WriteBoolAt(0xE0, 0x1, value);
    }

    public bool BAffectsTranslucency
    {
        get => ReadBoolAt(0xE0, 0x2);
        set => WriteBoolAt(0xE0, 0x2, value);
    }

    public bool BAlphaScalesBrightness
    {
        get => ReadBoolAt(0xE0, 0x4);
        set => WriteBoolAt(0xE0, 0x4, value);
    }

    public bool BOverrideInverseExposureBlend
    {
        get => ReadBoolAt(0xE0, 0x8);
        set => WriteBoolAt(0xE0, 0x8, value);
    }

    public float RadiusScale
    {
        get => ReadAt<float>(0xE4);
        set => WriteAt(0xE4, value);
    }

    public float DefaultExponent
    {
        get => ReadAt<float>(0xE8);
        set => WriteAt(0xE8, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector3f ColorAdd =>
        new Palforge.Sdk.Script.CoreUObject.Vector3f(Address + 0xEC, Context);

    public float InverseExposureBlend
    {
        get => ReadAt<float>(0xF8);
        set => WriteAt(0xF8, value);
    }

    public int RendererVisibility
    {
        get => ReadAt<int>(0xFC);
        set => WriteAt(0xFC, value);
    }

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding LightRenderingEnabledBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x100, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding LightExponentBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x158, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding PositionBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x1B0, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding ColorBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x208, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding RadiusBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x260, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding VolumetricScatteringBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x2B8, Context);

    public Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding RendererVisibilityTagBinding =>
        new Palforge.Sdk.Script.Niagara.NiagaraVariableAttributeBinding(Address + 0x310, Context);

    internal NiagaraLightRendererProperties(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("NiagaraLightRendererProperties");
    }

    public static new NiagaraLightRendererProperties? New(UObject? outer = null)
    {
        return SdkEnv.New("NiagaraLightRendererProperties", outer) as NiagaraLightRendererProperties;
    }

    public static new NiagaraLightRendererProperties? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as NiagaraLightRendererProperties;
    }
}
