// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.PPSkyCreatorPlugin;

public class PPSkyCreatorSkyLightSettings : UStructValue
{
    public float Intensity
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public float NightIntensity
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    public Palforge.Sdk.Script.CoreUObject.LinearColor LightColor =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.LinearColor LowerHemisphereColor =>
        new Palforge.Sdk.Script.CoreUObject.LinearColor(Address + 0x18, Context);

    public float CloudAmbientOcclusionStrength
    {
        get => ReadAt<float>(0x28);
        set => WriteAt(0x28, value);
    }

    internal PPSkyCreatorSkyLightSettings(nint address, UnrealContext context) : base(address, context, "PPSkyCreatorSkyLightSettings")
    {
    }

    private protected PPSkyCreatorSkyLightSettings(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static PPSkyCreatorSkyLightSettings? Allocate()
    {
        return SdkEnv.AllocateStruct<PPSkyCreatorSkyLightSettings>("PPSkyCreatorSkyLightSettings");
    }
}
