// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Dlss;

public class DLSSSettings : UObject
{
    public bool BAllowOTAUpdate
    {
        get => ReadBoolAt(0x28, 0xFF);
        set => WriteBoolAt(0x28, 0xFF, value);
    }

    public uint NVIDIANGXApplicationId
    {
        get => ReadAt<uint>(0x2C);
        set => WriteAt(0x2C, value);
    }

    public byte BiasCurrentColorStencilValue
    {
        get => ReadAt<byte>(0x30);
        set => WriteAt(0x30, value);
    }

    public bool BEnableDLSSD3D12
    {
        get => ReadBoolAt(0x31, 0xFF);
        set => WriteBoolAt(0x31, 0xFF, value);
    }

    public bool BEnableDLSSD3D11
    {
        get => ReadBoolAt(0x32, 0xFF);
        set => WriteBoolAt(0x32, 0xFF, value);
    }

    public bool BEnableDLSSVulkan
    {
        get => ReadBoolAt(0x33, 0xFF);
        set => WriteBoolAt(0x33, 0xFF, value);
    }

    public bool BShowDLSSIncompatiblePluginsToolsWarnings
    {
        get => ReadBoolAt(0x34, 0xFF);
        set => WriteBoolAt(0x34, 0xFF, value);
    }

    public bool BEnableDLSSInEditorViewports
    {
        get => ReadBoolAt(0x35, 0xFF);
        set => WriteBoolAt(0x35, 0xFF, value);
    }

    public bool BEnableDLSSInPlayInEditorViewports
    {
        get => ReadBoolAt(0x36, 0xFF);
        set => WriteBoolAt(0x36, 0xFF, value);
    }

    public bool BShowDLSSSDebugOnScreenMessages
    {
        get => ReadBoolAt(0x37, 0xFF);
        set => WriteBoolAt(0x37, 0xFF, value);
    }

    public string GenericDLSSSRBinaryPath
    {
        get => ReadStringAt(0x38);
        set => WriteStringAt(0x38, value);
    }

    public bool BGenericDLSSSRBinaryExists
    {
        get => ReadBoolAt(0x48, 0xFF);
        set => WriteBoolAt(0x48, 0xFF, value);
    }

    public string CustomDLSSSRBinaryPath
    {
        get => ReadStringAt(0x50);
        set => WriteStringAt(0x50, value);
    }

    public bool BCustomDLSSSRBinaryExists
    {
        get => ReadBoolAt(0x60, 0xFF);
        set => WriteBoolAt(0x60, 0xFF, value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSPreset DLAAPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSPreset)ReadAt<byte>(0x61);
        set => WriteAt(0x61, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSPreset DLSSQualityPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSPreset)ReadAt<byte>(0x63);
        set => WriteAt(0x63, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSPreset DLSSBalancedPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSPreset)ReadAt<byte>(0x64);
        set => WriteAt(0x64, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSPreset DLSSPerformancePreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSPreset)ReadAt<byte>(0x65);
        set => WriteAt(0x65, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSPreset DLSSUltraPerformancePreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSPreset)ReadAt<byte>(0x66);
        set => WriteAt(0x66, (byte)value);
    }

    public string GenericDLSSRRBinaryPath
    {
        get => ReadStringAt(0x68);
        set => WriteStringAt(0x68, value);
    }

    public bool BGenericDLSSRRBinaryExists
    {
        get => ReadBoolAt(0x78, 0xFF);
        set => WriteBoolAt(0x78, 0xFF, value);
    }

    public string CustomDLSSRRBinaryPath
    {
        get => ReadStringAt(0x80);
        set => WriteStringAt(0x80, value);
    }

    public bool BCustomDLSSRRBinaryExists
    {
        get => ReadBoolAt(0x90, 0xFF);
        set => WriteBoolAt(0x90, 0xFF, value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSRRPreset DLAARRPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSRRPreset)ReadAt<byte>(0x91);
        set => WriteAt(0x91, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSRRPreset DLSSRRQualityPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSRRPreset)ReadAt<byte>(0x93);
        set => WriteAt(0x93, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSRRPreset DLSSRRBalancedPreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSRRPreset)ReadAt<byte>(0x94);
        set => WriteAt(0x94, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSRRPreset DLSSRRPerformancePreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSRRPreset)ReadAt<byte>(0x95);
        set => WriteAt(0x95, (byte)value);
    }

    public Palforge.Sdk.Script.Dlss.EDLSSRRPreset DLSSRRUltraPerformancePreset
    {
        get => (Palforge.Sdk.Script.Dlss.EDLSSRRPreset)ReadAt<byte>(0x96);
        set => WriteAt(0x96, (byte)value);
    }

    internal DLSSSettings(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("DLSSSettings");
    }

    public static DLSSSettings? New(UObject? outer = null)
    {
        return SdkEnv.New("DLSSSettings", outer) as DLSSSettings;
    }

    public static DLSSSettings? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as DLSSSettings;
    }
}
