// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ApexDestruction;

public class DestructibleSpecialHierarchyDepths : UStructValue
{
    public int SupportDepth
    {
        get => ReadAt<int>(0x0);
        set => WriteAt(0x0, value);
    }

    public int MinimumFractureDepth
    {
        get => ReadAt<int>(0x4);
        set => WriteAt(0x4, value);
    }

    public bool BEnableDebris
    {
        get => ReadBoolAt(0x8, 0xFF);
        set => WriteBoolAt(0x8, 0xFF, value);
    }

    public int DebrisDepth
    {
        get => ReadAt<int>(0xC);
        set => WriteAt(0xC, value);
    }

    public int EssentialDepth
    {
        get => ReadAt<int>(0x10);
        set => WriteAt(0x10, value);
    }

    internal DestructibleSpecialHierarchyDepths(nint address, UnrealContext context) : base(address, context, "DestructibleSpecialHierarchyDepths")
    {
    }

    private protected DestructibleSpecialHierarchyDepths(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static DestructibleSpecialHierarchyDepths? Allocate()
    {
        return SdkEnv.AllocateStruct<DestructibleSpecialHierarchyDepths>("DestructibleSpecialHierarchyDepths");
    }
}
