// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AndroidFileServer;

public class AndroidFileServerBPLibrary : Palforge.Sdk.Script.Engine.BlueprintFunctionLibrary
{
    internal AndroidFileServerBPLibrary(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("AndroidFileServerBPLibrary");
    }

    public static new AndroidFileServerBPLibrary? New(UObject? outer = null)
    {
        return SdkEnv.New("AndroidFileServerBPLibrary", outer) as AndroidFileServerBPLibrary;
    }

    public static new AndroidFileServerBPLibrary? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as AndroidFileServerBPLibrary;
    }

    public static bool StopFileServer(bool bUSB, bool bNetwork)
    {
        return As<byte>(SdkEnv.CallStatic("AndroidFileServerBPLibrary", "StopFileServer", Bytes<byte>(bUSB ? (byte)1 : (byte)0), Bytes<byte>(bNetwork ? (byte)1 : (byte)0))) is not 0;
    }

    public static bool StartFileServer(bool bUSB, bool bNetwork, int port)
    {
        return As<byte>(SdkEnv.CallStatic("AndroidFileServerBPLibrary", "StartFileServer", Bytes<byte>(bUSB ? (byte)1 : (byte)0), Bytes<byte>(bNetwork ? (byte)1 : (byte)0), Bytes(port))) is not 0;
    }

    public static byte IsFileServerRunning()
    {
        return As<byte>(SdkEnv.CallStatic("AndroidFileServerBPLibrary", "IsFileServerRunning"));
    }
}
