// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GeometryCollectionNodes;

public class CloseGeometryOnCollectionDataflowNode : UStructValue
{
    public Palforge.Sdk.Script.Chaos.ManagedArrayCollection Collection =>
        new Palforge.Sdk.Script.Chaos.ManagedArrayCollection(Address + 0xD0, Context);

    public bool BActive
    {
        get => ReadBoolAt(0xC8, 0xFF);
        set => WriteBoolAt(0xC8, 0xFF, value);
    }

    internal CloseGeometryOnCollectionDataflowNode(nint address, UnrealContext context) : base(address, context, "CloseGeometryOnCollectionDataflowNode")
    {
    }

    private protected CloseGeometryOnCollectionDataflowNode(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static CloseGeometryOnCollectionDataflowNode? Allocate()
    {
        return SdkEnv.AllocateStruct<CloseGeometryOnCollectionDataflowNode>("CloseGeometryOnCollectionDataflowNode");
    }
}
