// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.GeometryCollectionNodes;

public class ExpandBoundingBoxDataflowNode : UStructValue
{
    public Palforge.Sdk.Script.CoreUObject.Box BoundingBox =>
        new Palforge.Sdk.Script.CoreUObject.Box(Address + 0xD0, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Min =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x108, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Max =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x120, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector Center =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x138, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector HalfExtents =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x150, Context);

    public float Volume
    {
        get => ReadAt<float>(0x168);
        set => WriteAt(0x168, value);
    }

    public bool BActive
    {
        get => ReadBoolAt(0xC8, 0xFF);
        set => WriteBoolAt(0xC8, 0xFF, value);
    }

    internal ExpandBoundingBoxDataflowNode(nint address, UnrealContext context) : base(address, context, "ExpandBoundingBoxDataflowNode")
    {
    }

    private protected ExpandBoundingBoxDataflowNode(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static ExpandBoundingBoxDataflowNode? Allocate()
    {
        return SdkEnv.AllocateStruct<ExpandBoundingBoxDataflowNode>("ExpandBoundingBoxDataflowNode");
    }
}
