// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CommonUser;

public class CommonUserSubsystem : Palforge.Sdk.Script.Engine.GameInstanceSubsystem
{
    public UnrealMap<int, Palforge.Sdk.Script.CommonUser.CommonUserInfo?> LocalUserInfos =>
        new UnrealMap<int, Palforge.Sdk.Script.CommonUser.CommonUserInfo?>(this, 0xD0, 0x18, 0x8, "LocalUserInfos", static (context, element) => context.ValueAt<int>(element), static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.CommonUser.CommonUserInfo, static (context, value) => Bytes(value), static (context, value) => Bytes<nint>(value?.Address ?? 0), null, null);

    internal CommonUserSubsystem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("CommonUserSubsystem");
    }

    public static new CommonUserSubsystem? New(UObject? outer = null)
    {
        return SdkEnv.New("CommonUserSubsystem", outer) as CommonUserSubsystem;
    }

    public static new CommonUserSubsystem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as CommonUserSubsystem;
    }

    public bool TryToLoginForOnlinePlay(int localPlayerIndex)
    {
        return As<byte>(Call("TryToLoginForOnlinePlay", Bytes(localPlayerIndex))) is not 0;
    }

    public bool TryToInitializeUser(Palforge.Sdk.Script.CommonUser.CommonUserInitializeParams @params)
    {
        return As<byte>(Call("TryToInitializeUser", SdkEnv.StructBytes(@params, 40))) is not 0;
    }

    public bool TryToInitializeForLocalPlay(int localPlayerIndex, Palforge.Sdk.Script.CoreUObject.InputDeviceId primaryInputDevice, bool bCanUseGuestLogin)
    {
        return As<byte>(Call("TryToInitializeForLocalPlay", Bytes(localPlayerIndex), SdkEnv.StructBytes(primaryInputDevice, 4), Bytes<byte>(bCanUseGuestLogin ? (byte)1 : (byte)0))) is not 0;
    }

    public bool ShouldWaitForStartInput()
    {
        return As<byte>(Call("ShouldWaitForStartInput")) is not 0;
    }

    public void SetMaxLocalPlayers(int inMaxLocalPLayers)
    {
        Call("SetMaxLocalPlayers", Bytes(inMaxLocalPLayers));
    }

    public void ResetUserState()
    {
        Call("ResetUserState");
    }

    public bool HasTraitTag(Palforge.Sdk.Script.GameplayTags.GameplayTag traitTag)
    {
        return As<byte>(Call("HasTraitTag", SdkEnv.StructBytes(traitTag, 8))) is not 0;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForUniqueNetId(Palforge.Sdk.Script.Engine.UniqueNetIdRepl netId)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForUniqueNetId", SdkEnv.StructBytes(netId, 48))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForPlatformUserIndex(int platformUserIndex)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForPlatformUserIndex", Bytes(platformUserIndex))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForPlatformUser(Palforge.Sdk.Script.CoreUObject.PlatformUserId platformUser)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForPlatformUser", SdkEnv.StructBytes(platformUser, 4))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForLocalPlayerIndex(int localPlayerIndex)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForLocalPlayerIndex", Bytes(localPlayerIndex))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForInputDevice(Palforge.Sdk.Script.CoreUObject.InputDeviceId inputDevice)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForInputDevice", SdkEnv.StructBytes(inputDevice, 4))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public Palforge.Sdk.Script.CommonUser.CommonUserInfo? GetUserInfoForControllerId(int controllerId)
    {
        return SdkEnv.Wrap(Call("GetUserInfoForControllerId", Bytes(controllerId))) as Palforge.Sdk.Script.CommonUser.CommonUserInfo;
    }

    public int GetNumLocalPlayers()
    {
        return As<int>(Call("GetNumLocalPlayers"));
    }

    public int GetMaxLocalPlayers()
    {
        return As<int>(Call("GetMaxLocalPlayers"));
    }

    public Palforge.Sdk.Script.CommonUser.ECommonUserInitializationState GetLocalPlayerInitializationState(int localPlayerIndex)
    {
        return (Palforge.Sdk.Script.CommonUser.ECommonUserInitializationState)As<byte>(Call("GetLocalPlayerInitializationState", Bytes(localPlayerIndex)));
    }

    public bool CancelUserInitialization(int localPlayerIndex)
    {
        return As<byte>(Call("CancelUserInitialization", Bytes(localPlayerIndex))) is not 0;
    }
}
