// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.SequencerScripting;

public class MovieSceneScriptingBoolKey : Palforge.Sdk.Script.SequencerScripting.MovieSceneScriptingKey
{
    internal MovieSceneScriptingBoolKey(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneScriptingBoolKey");
    }

    public static new MovieSceneScriptingBoolKey? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneScriptingBoolKey", outer) as MovieSceneScriptingBoolKey;
    }

    public static new MovieSceneScriptingBoolKey? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneScriptingBoolKey;
    }

    public void SetValue(bool inNewValue)
    {
        Call("SetValue", Bytes<byte>(inNewValue ? (byte)1 : (byte)0));
    }

    public void SetTime(Palforge.Sdk.Script.CoreUObject.FrameNumber newFrameNumber, float subFrame, Palforge.Sdk.Script.SequencerScripting.ESequenceTimeUnit timeUnit)
    {
        Call("SetTime", SdkEnv.StructBytes(newFrameNumber, 4), Bytes(subFrame), Bytes((byte)timeUnit));
    }

    public bool GetValue()
    {
        return As<byte>(Call("GetValue")) is not 0;
    }

    public Palforge.Sdk.Script.CoreUObject.FrameTime? GetTime(Palforge.Sdk.Script.SequencerScripting.ESequenceTimeUnit timeUnit)
    {
        return SdkEnv.CallForStruct<Palforge.Sdk.Script.CoreUObject.FrameTime>(this, "GetTime", "FrameTime", Bytes((byte)timeUnit));
    }
}
