// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.FieldSystemEngine;

public class UniformScalar : Palforge.Sdk.Script.FieldSystemEngine.FieldNodeFloat
{
    public float Magnitude
    {
        get => ReadAt<float>(0xA0);
        set => WriteAt(0xA0, value);
    }

    internal UniformScalar(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("UniformScalar");
    }

    public static new UniformScalar? New(UObject? outer = null)
    {
        return SdkEnv.New("UniformScalar", outer) as UniformScalar;
    }

    public static new UniformScalar? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as UniformScalar;
    }

    public Palforge.Sdk.Script.FieldSystemEngine.UniformScalar? SetUniformScalar(float magnitude)
    {
        return SdkEnv.Wrap(Call("SetUniformScalar", Bytes(magnitude))) as Palforge.Sdk.Script.FieldSystemEngine.UniformScalar;
    }
}
