// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieSceneTracks;

public class MovieSceneParticleSectionTemplate : UStructValue
{
    public Palforge.Sdk.Script.MovieSceneTracks.MovieSceneParticleChannel ParticleKeys =>
        new Palforge.Sdk.Script.MovieSceneTracks.MovieSceneParticleChannel(Address + 0x20, Context);

    public Palforge.Sdk.Script.MovieScene.EMovieSceneCompletionMode CompletionMode
    {
        get => (Palforge.Sdk.Script.MovieScene.EMovieSceneCompletionMode)ReadAt<byte>(0x10);
        set => WriteAt(0x10, (byte)value);
    }

    public UObject? SourceSectionPtr
    {
        get => ReadWeakAt(0x14);
        set => WriteWeakAt(0x14, value);
    }

    internal MovieSceneParticleSectionTemplate(nint address, UnrealContext context) : base(address, context, "MovieSceneParticleSectionTemplate")
    {
    }

    private protected MovieSceneParticleSectionTemplate(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MovieSceneParticleSectionTemplate? Allocate()
    {
        return SdkEnv.AllocateStruct<MovieSceneParticleSectionTemplate>("MovieSceneParticleSectionTemplate");
    }
}
