// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieSceneTracks;

public class MovieSceneDeferredComponentMovementSystem : Palforge.Sdk.Script.MovieScene.MovieSceneEntitySystem
{
    internal MovieSceneDeferredComponentMovementSystem(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneDeferredComponentMovementSystem");
    }

    public static new MovieSceneDeferredComponentMovementSystem? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneDeferredComponentMovementSystem", outer) as MovieSceneDeferredComponentMovementSystem;
    }

    public static new MovieSceneDeferredComponentMovementSystem? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneDeferredComponentMovementSystem;
    }
}
