// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MovieSceneTracks;

public class MovieSceneCVarSection : Palforge.Sdk.Script.MovieScene.MovieSceneSection
{
    public Palforge.Sdk.Script.MovieSceneTracks.MovieSceneCVarOverrides ConsoleVariables =>
        new Palforge.Sdk.Script.MovieSceneTracks.MovieSceneCVarOverrides(Address + 0xF8, Context);

    internal MovieSceneCVarSection(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("MovieSceneCVarSection");
    }

    public static new MovieSceneCVarSection? New(UObject? outer = null)
    {
        return SdkEnv.New("MovieSceneCVarSection", outer) as MovieSceneCVarSection;
    }

    public static new MovieSceneCVarSection? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as MovieSceneCVarSection;
    }

    public void SetFromString(string inString)
    {
        Call("SetFromString", StringArgument(inString));
    }

    public string GetString()
    {
        return SdkEnv.Text(Call("GetString"));
    }
}
