// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CameraCalibrationCore;

public class DistortionFocusPoint : UStructValue
{
    public float Focus
    {
        get => ReadAt<float>(0x8);
        set => WriteAt(0x8, value);
    }

    public Palforge.Sdk.Script.Engine.RichCurve MapBlendingCurve =>
        new Palforge.Sdk.Script.Engine.RichCurve(Address + 0x10, Context);

    public UnrealArray<Palforge.Sdk.Script.CameraCalibrationCore.DistortionZoomPoint> ZoomPoints =>
        new UnrealArray<Palforge.Sdk.Script.CameraCalibrationCore.DistortionZoomPoint>(this, 0x90, 0x18, "ZoomPoints", static (context, element) => new Palforge.Sdk.Script.CameraCalibrationCore.DistortionZoomPoint(element, context), static (context, value) => context.BytesAt(value.Address, 0x18), null);

    internal DistortionFocusPoint(nint address, UnrealContext context) : base(address, context, "DistortionFocusPoint")
    {
    }

    private protected DistortionFocusPoint(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static DistortionFocusPoint? Allocate()
    {
        return SdkEnv.AllocateStruct<DistortionFocusPoint>("DistortionFocusPoint");
    }
}
