// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CameraCalibrationCore;

public class DistortionData : UStructValue
{
    public UnrealArray<Palforge.Sdk.Script.CoreUObject.Vector2D> DistortedUVs =>
        new UnrealArray<Palforge.Sdk.Script.CoreUObject.Vector2D>(this, 0x0, 0x10, "DistortedUVs", static (context, element) => new Palforge.Sdk.Script.CoreUObject.Vector2D(element, context), static (context, value) => context.BytesAt(value.Address, 0x10), null);

    public float OverscanFactor
    {
        get => ReadAt<float>(0x10);
        set => WriteAt(0x10, value);
    }

    internal DistortionData(nint address, UnrealContext context) : base(address, context, "DistortionData")
    {
    }

    private protected DistortionData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static DistortionData? Allocate()
    {
        return SdkEnv.AllocateStruct<DistortionData>("DistortionData");
    }
}
