// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CameraCalibrationCore;

public class FocalLengthPointInfo : UStructValue
{
    public Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo FocalLengthInfo =>
        new Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo(Address + 0x8, Context);

    public float Focus
    {
        get => ReadAt<float>(0x0);
        set => WriteAt(0x0, value);
    }

    public float Zoom
    {
        get => ReadAt<float>(0x4);
        set => WriteAt(0x4, value);
    }

    internal FocalLengthPointInfo(nint address, UnrealContext context) : base(address, context, "FocalLengthPointInfo")
    {
    }

    private protected FocalLengthPointInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static FocalLengthPointInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<FocalLengthPointInfo>("FocalLengthPointInfo");
    }
}
