// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.CameraCalibrationCore;

public class LensFile : UObject
{
    public Palforge.Sdk.Script.CameraCalibrationCore.LensInfo LensInfo =>
        new Palforge.Sdk.Script.CameraCalibrationCore.LensInfo(Address + 0x30, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.ELensDataMode DataMode
    {
        get => (Palforge.Sdk.Script.CameraCalibrationCore.ELensDataMode)ReadAt<byte>(0x70);
        set => WriteAt(0x70, (byte)value);
    }

    public UnrealMap<string, string> UserMetadata =>
        new UnrealMap<string, string>(this, 0x78, 0x28, 0x10, "UserMetadata", static (context, element) => context.StringAt(element), static (context, element) => context.StringAt(element), static (context, value) => context.StringValueBytes(value), static (context, value) => context.StringValueBytes(value), static (context, bytes) => context.ReleaseStringValue(bytes), static (context, bytes) => context.ReleaseStringValue(bytes));

    public Palforge.Sdk.Script.CameraCalibrationCore.EncodersTable EncodersTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.EncodersTable(Address + 0xC8, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.DistortionTable DistortionTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.DistortionTable(Address + 0x1C8, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthTable FocalLengthTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthTable(Address + 0x1E8, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.ImageCenterTable ImageCenterTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.ImageCenterTable(Address + 0x208, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.NodalOffsetTable NodalOffsetTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.NodalOffsetTable(Address + 0x228, Context);

    public Palforge.Sdk.Script.CameraCalibrationCore.STMapTable STMapTable =>
        new Palforge.Sdk.Script.CameraCalibrationCore.STMapTable(Address + 0x248, Context);

    public UnrealArray<Palforge.Sdk.Script.Engine.TextureRenderTarget2D?> UndistortionDisplacementMapHolders =>
        new UnrealArray<Palforge.Sdk.Script.Engine.TextureRenderTarget2D?>(this, 0x278, 0x8, "UndistortionDisplacementMapHolders", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.TextureRenderTarget2D, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    public UnrealArray<Palforge.Sdk.Script.Engine.TextureRenderTarget2D?> DistortionDisplacementMapHolders =>
        new UnrealArray<Palforge.Sdk.Script.Engine.TextureRenderTarget2D?>(this, 0x288, 0x8, "DistortionDisplacementMapHolders", static (context, element) => context.ObjectAt(element) as Palforge.Sdk.Script.Engine.TextureRenderTarget2D, static (context, value) => Bytes<nint>(value?.Address ?? 0), null);

    internal LensFile(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static UClass? StaticClass()
    {
        return SdkEnv.StaticClass("LensFile");
    }

    public static LensFile? New(UObject? outer = null)
    {
        return SdkEnv.New("LensFile", outer) as LensFile;
    }

    public static LensFile? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as LensFile;
    }

    public void RemoveZoomPoint(Palforge.Sdk.Script.CameraCalibrationCore.ELensDataCategory inDataCategory, float inFocus, float inZoom)
    {
        Call("RemoveZoomPoint", Bytes((byte)inDataCategory), Bytes(inFocus), Bytes(inZoom));
    }

    public void RemoveFocusPoint(Palforge.Sdk.Script.CameraCalibrationCore.ELensDataCategory inDataCategory, float inFocus)
    {
        Call("RemoveFocusPoint", Bytes((byte)inDataCategory), Bytes(inFocus));
    }

    public bool HasSamples(Palforge.Sdk.Script.CameraCalibrationCore.ELensDataCategory inDataCategory)
    {
        return As<byte>(Call("HasSamples", Bytes((byte)inDataCategory))) is not 0;
    }

    public bool HasIrisEncoderMapping()
    {
        return As<byte>(Call("HasIrisEncoderMapping")) is not 0;
    }

    public bool HasFocusEncoderMapping()
    {
        return As<byte>(Call("HasFocusEncoderMapping")) is not 0;
    }

    public int GetTotalPointNum(Palforge.Sdk.Script.CameraCalibrationCore.ELensDataCategory inDataCategory)
    {
        return As<int>(Call("GetTotalPointNum", Bytes((byte)inDataCategory)));
    }

    public bool GetSTMapPoint(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.STMapInfo outSTMapInfo)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outSTMapInfo, 16) };
        var destinations = new nint[] { 0, 0, outSTMapInfo.Address };
        var result = Call("GetSTMapPoint", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool GetNodalOffsetPoint(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.NodalPointOffset outNodalPointOffset)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outNodalPointOffset, 64) };
        var destinations = new nint[] { 0, 0, outNodalPointOffset.Address };
        var result = Call("GetNodalOffsetPoint", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool GetImageCenterPoint(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.ImageCenterInfo outImageCenterInfo)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outImageCenterInfo, 16) };
        var destinations = new nint[] { 0, 0, outImageCenterInfo.Address };
        var result = Call("GetImageCenterPoint", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool GetFocalLengthPoint(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo outFocalLengthInfo)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outFocalLengthInfo, 16) };
        var destinations = new nint[] { 0, 0, outFocalLengthInfo.Address };
        var result = Call("GetFocalLengthPoint", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool GetDistortionPoint(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.DistortionInfo outDistortionInfo)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outDistortionInfo, 16) };
        var destinations = new nint[] { 0, 0, outDistortionInfo.Address };
        var result = Call("GetDistortionPoint", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public float EvaluateNormalizedIris(float inNormalizedValue)
    {
        return As<float>(Call("EvaluateNormalizedIris", Bytes(inNormalizedValue)));
    }

    public float EvaluateNormalizedFocus(float inNormalizedValue)
    {
        return As<float>(Call("EvaluateNormalizedFocus", Bytes(inNormalizedValue)));
    }

    public bool EvaluateNodalPointOffset(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.NodalPointOffset outEvaluatedValue)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outEvaluatedValue, 64) };
        var destinations = new nint[] { 0, 0, outEvaluatedValue.Address };
        var result = Call("EvaluateNodalPointOffset", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool EvaluateImageCenterParameters(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.ImageCenterInfo outEvaluatedValue)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outEvaluatedValue, 16) };
        var destinations = new nint[] { 0, 0, outEvaluatedValue.Address };
        var result = Call("EvaluateImageCenterParameters", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool EvaluateFocalLength(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo outEvaluatedValue)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outEvaluatedValue, 16) };
        var destinations = new nint[] { 0, 0, outEvaluatedValue.Address };
        var result = Call("EvaluateFocalLength", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool EvaluateDistortionParameters(float inFocus, float inZoom, Palforge.Sdk.Script.CameraCalibrationCore.DistortionInfo outEvaluatedValue)
    {
        var arguments = new byte[][] { Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(outEvaluatedValue, 16) };
        var destinations = new nint[] { 0, 0, outEvaluatedValue.Address };
        var result = Call("EvaluateDistortionParameters", arguments, destinations, out var outputs);
        return As<byte>(result) is not 0;
    }

    public bool EvaluateDistortionData(float inFocus, float inZoom, Palforge.Sdk.Script.CoreUObject.Vector2D inFilmback, Palforge.Sdk.Script.CameraCalibrationCore.LensDistortionModelHandlerBase? inLensHandler)
    {
        return As<byte>(Call("EvaluateDistortionData", Bytes(inFocus), Bytes(inZoom), SdkEnv.StructBytes(inFilmback, 16), Bytes<nint>(inLensHandler?.Address ?? 0))) is not 0;
    }

    public void ClearData(Palforge.Sdk.Script.CameraCalibrationCore.ELensDataCategory inDataCategory)
    {
        Call("ClearData", Bytes((byte)inDataCategory));
    }

    public void ClearAll()
    {
        Call("ClearAll");
    }

    public void AddSTMapPoint(float newFocus, float newZoom, Palforge.Sdk.Script.CameraCalibrationCore.STMapInfo newPoint)
    {
        Call("AddSTMapPoint", Bytes(newFocus), Bytes(newZoom), SdkEnv.StructBytes(newPoint, 16));
    }

    public void AddNodalOffsetPoint(float newFocus, float newZoom, Palforge.Sdk.Script.CameraCalibrationCore.NodalPointOffset newPoint)
    {
        Call("AddNodalOffsetPoint", Bytes(newFocus), Bytes(newZoom), SdkEnv.StructBytes(newPoint, 64));
    }

    public void AddImageCenterPoint(float newFocus, float newZoom, Palforge.Sdk.Script.CameraCalibrationCore.ImageCenterInfo newPoint)
    {
        Call("AddImageCenterPoint", Bytes(newFocus), Bytes(newZoom), SdkEnv.StructBytes(newPoint, 16));
    }

    public void AddFocalLengthPoint(float newFocus, float newZoom, Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo newFocalLength)
    {
        Call("AddFocalLengthPoint", Bytes(newFocus), Bytes(newZoom), SdkEnv.StructBytes(newFocalLength, 16));
    }

    public void AddDistortionPoint(float newFocus, float newZoom, Palforge.Sdk.Script.CameraCalibrationCore.DistortionInfo newPoint, Palforge.Sdk.Script.CameraCalibrationCore.FocalLengthInfo newFocalLength)
    {
        Call("AddDistortionPoint", Bytes(newFocus), Bytes(newZoom), SdkEnv.StructBytes(newPoint, 16), SdkEnv.StructBytes(newFocalLength, 16));
    }
}
