// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.Constraints;

public class TickableScaleConstraint : Palforge.Sdk.Script.Constraints.TickableTransformConstraint
{
    public Palforge.Sdk.Script.CoreUObject.Vector OffsetScale =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x98, Context);

    internal TickableScaleConstraint(nint address, UnrealContext context) : base(address, context)
    {
    }

    public static new UClass? StaticClass()
    {
        return SdkEnv.StaticClass("TickableScaleConstraint");
    }

    public static new TickableScaleConstraint? New(UObject? outer = null)
    {
        return SdkEnv.New("TickableScaleConstraint", outer) as TickableScaleConstraint;
    }

    public static new TickableScaleConstraint? Load(string path)
    {
        return SdkEnv.LoadAsset(path) as TickableScaleConstraint;
    }
}
