// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MetasoundFrontend;

public enum EMetasoundFrontendNodeStyleDisplayVisibility
{
    Visible = 0,
    Hidden = 1,
    EMetasoundFrontendNodeStyleDisplayVisibilityMax = 2
}
