// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.TypedElementRuntime;

public class TypedElementIsSelectedOptions : UStructValue
{
    public bool BAllowIndirect
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    internal TypedElementIsSelectedOptions(nint address, UnrealContext context) : base(address, context, "TypedElementIsSelectedOptions")
    {
    }

    private protected TypedElementIsSelectedOptions(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static TypedElementIsSelectedOptions? Allocate()
    {
        return SdkEnv.AllocateStruct<TypedElementIsSelectedOptions>("TypedElementIsSelectedOptions");
    }
}
