// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.AssetRegistry;

public class TagAndValue : UStructValue
{
    public string Tag
    {
        get => ReadNameAt(0x0);
        set => WriteNameAt(0x0, value);
    }

    public string Value
    {
        get => ReadStringAt(0x8);
        set => WriteStringAt(0x8, value);
    }

    internal TagAndValue(nint address, UnrealContext context) : base(address, context, "TagAndValue")
    {
    }

    private protected TagAndValue(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static TagAndValue? Allocate()
    {
        return SdkEnv.AllocateStruct<TagAndValue>("TagAndValue");
    }
}
