// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.WwiseResourceLoader;

public class WwiseSharedPlatformId : UStructValue
{
    internal WwiseSharedPlatformId(nint address, UnrealContext context) : base(address, context, "WwiseSharedPlatformId")
    {
    }

    private protected WwiseSharedPlatformId(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static WwiseSharedPlatformId? Allocate()
    {
        return SdkEnv.AllocateStruct<WwiseSharedPlatformId>("WwiseSharedPlatformId");
    }
}
