// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.FullBodyIK;

public class RigUnitFullbodyIKWorkData : UStructValue
{
    internal RigUnitFullbodyIKWorkData(nint address, UnrealContext context) : base(address, context, "RigUnit_FullbodyIK_WorkData")
    {
    }

    private protected RigUnitFullbodyIKWorkData(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static RigUnitFullbodyIKWorkData? Allocate()
    {
        return SdkEnv.AllocateStruct<RigUnitFullbodyIKWorkData>("RigUnit_FullbodyIK_WorkData");
    }
}
