// <auto-generated/>
#nullable enable
namespace Palforge.Sdk.Script.MaterialShaderQualitySettings;

public enum EMobileShadowQuality
{
    NoFiltering = 0,
    Pcf1x1 = 1,
    Pcf3x3 = 2,
    Pcf5x5 = 3,
    EMobileShadowQualityMax = 4
}
