// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.MaterialShaderQualitySettings;

public class MaterialQualityOverrides : UStructValue
{
    public bool BDiscardQualityDuringCook
    {
        get => ReadBoolAt(0x0, 0xFF);
        set => WriteBoolAt(0x0, 0xFF, value);
    }

    public bool BEnableOverride
    {
        get => ReadBoolAt(0x1, 0xFF);
        set => WriteBoolAt(0x1, 0xFF, value);
    }

    public bool BForceFullyRough
    {
        get => ReadBoolAt(0x2, 0xFF);
        set => WriteBoolAt(0x2, 0xFF, value);
    }

    public bool BForceNonMetal
    {
        get => ReadBoolAt(0x3, 0xFF);
        set => WriteBoolAt(0x3, 0xFF, value);
    }

    public bool BForceDisableLMDirectionality
    {
        get => ReadBoolAt(0x4, 0xFF);
        set => WriteBoolAt(0x4, 0xFF, value);
    }

    public bool BForceDisablePreintegratedGF
    {
        get => ReadBoolAt(0x5, 0xFF);
        set => WriteBoolAt(0x5, 0xFF, value);
    }

    public bool BDisableMaterialNormalCalculation
    {
        get => ReadBoolAt(0x6, 0xFF);
        set => WriteBoolAt(0x6, 0xFF, value);
    }

    public Palforge.Sdk.Script.MaterialShaderQualitySettings.EMobileShadowQuality MobileShadowQuality
    {
        get => (Palforge.Sdk.Script.MaterialShaderQualitySettings.EMobileShadowQuality)ReadAt<byte>(0x7);
        set => WriteAt(0x7, (byte)value);
    }

    internal MaterialQualityOverrides(nint address, UnrealContext context) : base(address, context, "MaterialQualityOverrides")
    {
    }

    private protected MaterialQualityOverrides(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static MaterialQualityOverrides? Allocate()
    {
        return SdkEnv.AllocateStruct<MaterialQualityOverrides>("MaterialQualityOverrides");
    }
}
