// <auto-generated/>
#nullable enable
using Palforge.Unreal.Reflection;
using Palforge.Unreal.Sdk;

namespace Palforge.Sdk.Script.ReplicationGraph;

public class LastLocationGatherInfo : UStructValue
{
    public Palforge.Sdk.Script.Engine.NetConnection? Connection
    {
        get => WrapAt(0x0) as Palforge.Sdk.Script.Engine.NetConnection;
        set => WriteObjectAt(0x0, value);
    }

    public Palforge.Sdk.Script.CoreUObject.Vector LastLocation =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x8, Context);

    public Palforge.Sdk.Script.CoreUObject.Vector LastOutOfRangeLocationCheck =>
        new Palforge.Sdk.Script.CoreUObject.Vector(Address + 0x20, Context);

    internal LastLocationGatherInfo(nint address, UnrealContext context) : base(address, context, "LastLocationGatherInfo")
    {
    }

    private protected LastLocationGatherInfo(nint address, UnrealContext context, string? structName) : base(address, context, structName)
    {
    }

    public static LastLocationGatherInfo? Allocate()
    {
        return SdkEnv.AllocateStruct<LastLocationGatherInfo>("LastLocationGatherInfo");
    }
}
